### ISSUE TITLE
Switching config files between MC and data

### ISSUE THREAD

**Issue by veelken** [cms-nanoAOD/cmssw#102]
Dear all,

can you remind me how the config file https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/test/nano_cfg.py needs to be modified when running it on data ?

It seems to me that assumptions are made in different places in the config files (e.g. https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/test/nano_cfg.py#L39-L43 , but also when processing genParticle collections in https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/python/nano_cff.py ). 

Is there a global flag that allows to switch all config files to data or how do you run nanoAOD production jobs for data ?

**Comment by gpetruc** [comment]
The supported procedure is to generate the configuration files with cmsDriver, specifying `--mc` or `--data`.

**Comment by veelken** [comment]
Hi Giovanni,

ok, but how would a user switch between MC and data in case he needs to modify https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/test/nano_cfg.py in order to add additional branches to the nanoAOD (e.g. for reconstructing boosted hadronic tops) ?

Thank you,


Christian

**Comment by arizzi** [comment]
it is there in the comments:
https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/test/nano_cfg.py#L41

anyhow I'd suggest to use cmsDriver as explained in the WorkBookNanoAOD and then edit the resulting config.

**Comment by veelken** [comment]
Hi Andrea,

hmh, I don't see how the comment in https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/test/nano_cfg.py#L41 would e.g. switch on and off the 'L2L3Residual' jet energy corrections defined in https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/python/jets_cff.py .

Ok, I will create 2 separate config files for data and MC, modify them, and then check the python dump.

Cheers,


Christian

**Comment by arizzi** [comment]
my understanding is that in recent CMSSW L2L3Residual for mc contains a dummy payload (with ones).

**Comment by arizzi** [comment]
see the comment in the code example here https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookJetEnergyCorrections#CMSSW_7_6_4_and_above

**Comment by veelken** [comment]
Ok, thanks!

**Comment by arizzi** [comment]
btw, there are other changes I think in egamma code that I'm not sure are handled if you do not use cmsDriver... so I'd suggest to really use cmsDriver!
