### ISSUE TITLE
Error messages about reclustered jets

### ISSUE THREAD

**Issue by veelken** [cms-nanoAOD/cmssw#103]
Hi,

when I run 'cmsRun nano_cfg.py' in CMSSW 9_4_4, I get many error messages of the type attached below [*] (about one error message per 100 events processed).
Is this expected ?

Cheers,

Christian

- - - - - - - - -

[*]

%MSG-e MissingJetConstituent:  JetFlavourClustering:genJetFlavourAssociation  05-Feb-2018 17:28:30 EET Run: 1 Event: 41829503
Jet constituent required for jet reclustering is missing. Reclustered jets are not guaranteed to reproduce the original jets!
%MSG
%MSG-e JetPtMismatch:  JetFlavourClustering:genJetFlavourAssociation  05-Feb-2018 17:28:30 EET Run: 1 Event: 41829503
The reclustered and original jet 7 have different Pt's (2.93164 vs 10.261 GeV, respectively).
Please check that the jet algorithm and jet size match those used for the original jet collection and also make sure the original jets are uncorrected. In addition, make sure you are not using CaloJets which are presently not supported.

In extremely rare instances the mismatch could be caused by a difference in the machine precision in which case make sure the original jet collection is produced and reclustering is performed in the same job.
%MSG

**Comment by arizzi** [comment]
can you try with the cmsDriver version, is it the same?

**Comment by veelken** [comment]
Hi Andrea,

I confirm that I get the same error when I create the config file with cmsDriver.
I send you the commands and output attached below. I am running in CMSSW 9_4_4.

Cheers,


Christian

- - - - - - - - -

cmsDriver.py test92X -s NANO --mc --eventcontent NANOAODSIM --datatier NANOAODSIM --filein file:///hdfs/cms/store/mc/RunIISummer17MiniAOD/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/MINIAODSIM/92X_upgrade2017_realistic_Candidate_forECALStudies_ext1-v1/70000/FC9F9AAD-29A4-E711-8FCD-0CC47A4D7670.root --no_exec --conditions auto:phase1_2017_realistic --number=-1 --era Run2_2017,run2_nanoAOD_92X

cmsRun test92X_NANO.py

%MSG-e MissingJetConstituent:  JetFlavourClustering:genJetFlavourAssociation  06-Feb-2018 10:11:06 EET Run: 1 Event: 57551683
Jet constituent required for jet reclustering is missing. Reclustered jets are not guaranteed to reproduce the original jets!
%MSG
%MSG-w JetPtMismatchAtLowPt:  JetFlavourClustering:genJetFlavourAssociation  06-Feb-2018 10:11:06 EET Run: 1 Event: 57551683
The reclustered and original jet 2 have different Pt's (1.47824 vs 9.61056 GeV, respectively).
Please check that the jet algorithm and jet size match those used for the original jet collection and also make sure the original jets are uncorrected. In addition, make sure you are not using CaloJets which are presently not supported.
Since the mismatch is at low Pt (Pt<10 GeV), it is ignored and only a warning is issued.

In extremely rare instances the mismatch could be caused by a difference in the machine precision in which case make sure the original jet collection is produced and reclustering is performed in the same job.
%MSG

**Comment by arizzi** [comment]
Hi,
are you sure the same GT is used for MC production and nanoaod?

**Comment by veelken** [comment]
Yes, I think so. Why would the genJet reconstruction even depend on the global tag ?

**Comment by gpetruc** [comment]
Hi,
Do you see this also on 94X inputs?
In 92X and older releases, I think jet flavour is re-run from miniAOD and
the code complains that this is not perfect as some gen particles are
missing (it should happen only at at large rapidity, if you have some time
you could try track down the warning and add the rapidity to the printout
to check whether it's the case).
That said, I've seen warning messages of that sort also during standard
reco or miniAOD production, so I wouldn't worry too much about it: I don't
think any physics result should hinge on percent-level precision of the gen
jet flavour at 10 GeV of pt.

**Comment by veelken** [comment]
Hi Giovanni,

I confirm that I see the same error when running on a miniAOD file produced with CMSSW 9_4_x.
The rate of the MissingJetConstituent: JetFlavourClustering and JetPtMismatchAtLowPt: JetFlavourClustering error is still about one error per 100 events processed.

When running on 94X inputs, I get a new error [*]. The NullTransverseMomentum:   JetFlavourClustering occurs about once per 10-20 events processed.

I think this needs to be fixed (or understood and confirmed to be harmless, than suppressed) before we can start to submit crabJobs for large samples, as the log files will be very large otherwise.

Cheers,


Christian

- - - - - - - - 

[*]

%MSG
Begin processing the 1901st record. Run 1, Event 66792578, LumiSection 38331 at 06-Feb-2018 17:14:55.377 EET
%MSG-w NullTransverseMomentum:   JetFlavourClustering:genJetAK8FlavourAssociation 06-Feb-2018 17:14:55 EET  Run: 1 Event: 66792632
dropping input candidate with pt=0
%MSG

**Comment by arizzi** [comment]
can you post the full log?
Are you sure it is every 10 events rather than every 1000 ? (it seems we print the event number every 100 events)

**Comment by arizzi** [comment]
anyhow the rate I see is compatible with the rate of warnings we have in other cmssw steps...

**Comment by gpetruc** [comment]
Seems to me it comes from #21 from Markus Seidel @intrepid42 maybe Christian you can follow up with him?

**Comment by veelken** [comment]
Hi,

please find attached the full log file.

I inferred the rates of occurrence by checking how often I see the different error messages as function of the number of events processed.

I see that PR #21 is about Rivet. I don’t really plan to investigate what is happening with Rivet in detail, but if you can send me something concrete to check (e.g. to disable Rivet and check if the error messages disappear), I am willing to do these checks.

Cheers,


Christian

**Comment by arizzi** [comment]
was this followed up?

**Comment by intrepid42** [comment]
Hi, if I remember correctly 94X MiniAod includes the FlavourAssociation for AK4 genJets but not for AK8, that's why the module still has to be run, unfortunately.

This would not happen if we would just use the jets from Rivet but these come without parton flavor. I tried to add the hadron flavor information of the Rivet jets to the genJets but the collections are not guaranteed to be the same as Rivet can only recluster from the packedGenParticles with |eta|<5.0.

**Comment by vlimant** [comment]
ping / reopen if needed
