### ISSUE TITLE
b jet energy regression not working properly?

### ISSUE THREAD

**Issue by arizzi** [cms-nanoAOD/cmssw#105]
@cvernier 
it seems to me the improvements of the Jet_bReg  wrt Jet_pt are not as large as expected.
Probably we have a bug in some of the input variables.

Can you please cross check that the inputs are correct, here :
https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/plugins/BJetEnergyRegressionMVA.cc
and here:
https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/python/jets_cff.py#L160-L170

**Comment by arizzi** [comment]
@scooperstein reported that the wrong weights are been used. can you please post the file with the new weights ?

**Comment by gpetruc** [comment]
is this fixed by https://github.com/cms-data/PhysicsTools-NanoAOD/pull/3 (available in 9_4_6 or later) ?

**Comment by arizzi** [comment]
likely but not 100% sure (verifying it)

**Comment by gpetruc** [comment]
i believe it should be fixed in the past PR.
re-open if needed
