### ISSUE TITLE
new muon IDs

### ISSUE THREAD

**Issue by arizzi** [cms-nanoAOD/cmssw#106]
do we need to include some new IDs?

**Comment by arizzi** [comment]
@drkovalskyi can you make a PR to this repo adding the new IDs in NANO? 

Is there a 94X MAOD equivalent of 
https://github.com/cms-sw/cmssw/pull/22420 ?

**Comment by drkovalskyi** [comment]
nanoAOD should just copy values from miniAOD, i.e. it should not recompute. If it's not implemented this way it needs to be fixed. Do we plan to produce nanoAOD at T0?

There is no plan to back port to 94X, since it's not expected to be used for the full Run2 re-reco.

**Comment by arizzi** [comment]
PATMuonProducer runs at level of reminiaod, not rereco and the Selectors are in DF so I'm not sure what rereco has to do with it.
Why shouldn't this go in reminiaod ? can you clarify?

Can those new ID also be compute from MINIAOD? if so I do not se why they should not be in nanoaod.

In the PR you wrote that SUSY and others are using those working points, so why not including in nano?

NanoAOD can just copy the value from MINIAOD PATMuon if stored, or compute on the fly, with PAT code if available. No wheel reinvented here.

**Comment by drkovalskyi** [comment]
> PATMuonProducer runs at level of reminiaod, not rereco and the Selectors are in DF so I'm not sure what rereco has to do with it.
> Why shouldn't this go in reminiaod ? can you clarify?

Unless there is a clear use case, we won't back port anything. Whoever needs new selectors needs them in all Run2 data and the next opportunity to put it all together in a set of consistent datasets is the final re-reco of Run2. So while it has nothing to do with re-reco as a process, it's mostly a question of planning for major campaigns.

> Can those new ID also be compute from MINIAOD? if so I do not se why they should not be in nanoaod.
We need AOD as input. I don't think all inputs are available in miniAOD.

> In the PR you wrote that SUSY and others are using those working points, so why not including in nano?
If nanoAOD copies the value all the changes in 10_1_X miniAOD will be available in 10_1_X nanoAOD.

> NanoAOD can just copy the value from MINIAOD PATMuon if stored, or compute on the fly, with PAT code if available. No wheel reinvented here.
What is it at the moment? Is it a copy? If yes, we have no problem and it's all good for 10_1_X and later releases. If not and nanoAOD will be produced at T0, we have to fix the code.

**Comment by drkovalskyi** [comment]
I'm not aware of any re-miniAOD campaigns in near future that would allow to get a complete Run2016+Run2017 with consistent content. We were late for current cycle. The next is in a year from now and it won't be with 94X release. So no backport.

Regarding nanoAOD content I will need to find time to look into it and implement the change.

**Comment by arizzi** [comment]
you submitted that PR 2 weeks ago, there was definitely time to have it included in 94X for the reminiaod of 2016 and 2017 that we are making in a few days/week....
