### ISSUE TITLE
new MVA-based Tau-Ids

### ISSUE THREAD

**Issue by mbluj** [cms-nanoAOD/cmssw#107]
The MVA-based Tau-IDs are going to be retrained with 94X Fall17 samples and then should be evaluated using MiniAOD Taus (skimmedTaus) and added to NanoAOD.
An initial implementation, based on MVA training with 92X Summer17 samples, will be PR'ed soon (by @mbluj) to start discussion and speed revision of the final implementation.

**Comment by arizzi** [comment]
I assume this referes to what entered V2 so I close
