### ISSUE TITLE
Review FatJet & SubJet with B2G

### ISSUE THREAD

**Issue by arizzi** [cms-nanoAOD/cmssw#11]
There were requests to store additional SubJets rather than just softdrop.

It should be clarified if this is really needed and/or if the time to compute them from MiniAOD is too slow.

**Comment by arizzi** [comment]
cms-sw/cmssw#20638 should address the needs in input.
waiting for the miniAOD PR to close the issue
(the NanoAOD part is anyhow already available here:
https://github.com/rappoccio/cmssw/commit/42440dbc05408522e964df0f7a16e5976e4e53cf )

**Comment by rappoccio** [comment]
What other subjets? Pruned? Soft drop with beta = 1? beta = 2?

**Comment by arizzi** [comment]
@clelange  suggested it on the spreadsheet. I think pruned

**Comment by arizzi** [comment]
and how about Hbb tagger?

**Comment by rappoccio** [comment]
Hbb is also using soft drop, I thought... In the last few years the only taggers other than soft drop beta=0 is soft drop with beta=1 for moderately boosted top quarks, unless I missed something? 

@clelange, any ideas here?

**Comment by arizzi** [comment]
I mean Hbb tagger needs to be precomputed... should we run it on MiniAOD or while making NanoAOD?

**Comment by rappoccio** [comment]
For the Hbb discriminator I think adding it to miniAOD would be better, if we can afford it. I don't think it is so computationally intensive, right?

**Comment by arizzi** [comment]
I guess not... the only point against is that it is still a developed and retrained thing... perhaps they want more flexibility than "once every reminiaod"

**Comment by rappoccio** [comment]
Good point... I suppose we can add it in, and if things are retrained we will just have to recompute each re-nanoAOD.

**Comment by clelange** [comment]
Regarding subjets:
- The two soft-dropped ones (beta = 0) should do for analyses targeting boosted W/Z, Hbb and probably also top, if one does not want to resolve the W from the top. For H->WW->4q one would want to have 4 subjets (which are at least the result of the splitting of one of the two initial subjets)

For Hbb:
- I expect it to be retrained, so being able to rerun it at nanoAOD level would be very useful.

**Comment by arizzi** [comment]
btw they need the tau axis, do we have them stored in miniaod or should we recluster to get them?

**Comment by rappoccio** [comment]
@clelange: Can we not just get away with storing tau4/tau3  or tau4/tau2? Do we really need the splitting of the W subjets? It will be very expensive to do this, if only one analysis may or may not use it, it won't be worthwhile to keep it. 

@arizzi we don't store the tau axes... we would have to run XCone or something like that.

**Comment by arizzi** [comment]
I'm not sure how they do it in the pfBoostedDoubleSVAK8TagInfos 
@ferencek can you comment on the Hbb needs?

**Comment by clelange** [comment]
@rappoccio To be pragmatic, let's store the first two subjets only, since they are needed for subjet b-tagging studies. For the others the taux/y values will probably do.

Regarding the Hbb tagger, it took me quite some effort to rerun it without full CMSSW since one needs the B field etc. - see
https://github.com/CERN-PH-CMG/cmgtools-lite/blob/80X/VVResonances/src/CandidateBoostedDoubleSecondaryVertexComputerLight.cc
and also
https://github.com/CERN-PH-CMG/cmgtools-lite/blob/80X/VVResonances/src/IPProducerLight.cc
https://github.com/CERN-PH-CMG/cmgtools-lite/blob/80X/VVResonances/src/SecondaryVertexProducerLight.cc
With full CMSSW, as I understand is here the case, this is easier. It can be rerun from miniAOD.

**Comment by arizzi** [comment]
for Hbb I've some config in VHbb-heppy
https://github.com/vhbb/cmssw/blob/vhbbHeppy80X/VHbbAnalysis/Heppy/test/combined_cmssw.py#L314

I can try to import from there

**Comment by ferencek** [comment]
The Hbb double-b discriminator is already being stored in slimmed AK8 jets and can also be re-run from MiniAOD. So if needed, it could be easily re-run as part of re-NanoAOD. The tau axes are computed internally on-the-fly so there is no need to store them in MiniAOD.

**Comment by arizzi** [comment]
thanks dinko, I'll add the existing float!

Il 25 set 2017 9:33 PM, "Dinko Ferencek" <notifications@github.com> ha
scritto:

**Comment by arizzi** [comment]
pfBoostedDoubleSecondaryVertexAK8BJetTags right?

**Comment by ferencek** [comment]
@arizzi, yes

**Comment by arizzi** [comment]
@rappoccio can you prepare a PR with your 
rappoccio/cmssw@42440db

**Comment by rappoccio** [comment]
@arizzi Sure, where to? cms-nanoAOD? Is there a branch that is up to date with 940pre3?

**Comment by arizzi** [comment]
cms-nanoAOD/master is in sync with pre3 since this morning

Il 25 ott 2017 3:26 PM, "rappoccio" <notifications@github.com> ha scritto:

**Comment by rappoccio** [comment]
Done at #52.
