### ISSUE TITLE
EGamma energy scale and resolution corrections

### ISSUE THREAD

**Issue by veelken** [cms-nanoAOD/cmssw#112]
Implement/merge EGamma POG recipe on twiki
https://twiki.cern.ch/twiki/bin/viewauth/CMS/EGMSmearer#ECAL_scale_and_resolution_correc

**Comment by arizzi** [comment]
we should have the e/gamma code ported in  official CMSSW.
We are working on an analysis-release strategy with O&C to get this done easily

**Comment by arizzi** [comment]
this was included in V2 miniaod and available in new nanoaod
