### ISSUE TITLE
Maybe exclude gen-level W-s and Z-s from the mass cut?

### ISSUE THREAD

**Issue by ktht** [cms-nanoAOD/cmssw#114]
In events where e.g. H->WW, at least one of the W-s goes to off shell, sometimes so much so that their masses drop below 10 GeV (this actually happens ~4% of the time in ttH, H->WW events). When trying to recover these masses from a lookup table, we accidentally would put such low-mass W-s on a mass shell. Why not exclude W-s (and Z-s for the same reason) from this mass-cut?

https://github.com/cms-nanoAOD/cmssw/blob/b26c4ccfeba8e9c7ad205465d5fbb8ec0d510268/PhysicsTools/NanoAOD/python/genparticles_cff.py#L44

**Comment by arizzi** [comment]
yes, please make a PR whitelisting W,Z, H

**Comment by ktht** [comment]
I don't think that H mass goes below 10 GeV b/c its width is O(MeV).
