### ISSUE TITLE
Production crashes in RunIISummer16NanoAOD campaign

### ISSUE THREAD

**Issue by gpetruc** [cms-nanoAOD/cmssw#117]
- [HN prep-ops/4865](https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/4865.html) in [JME-RunIISummer16NanoAOD-00002](https://cms-pdmv.cern.ch/mcm/requests?prepid=JME-RunIISummer16NanoAOD-00002&page=0&shown=127) SingleNeutrino
- [HN prep-ops/4924](https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/4924.html) in [SMP-RunIISummer16NanoAOD-00147](https://cms-pdmv.cern.ch/mcm/requests?prepid=SMP-RunIISummer16NanoAOD-00147&page=0&shown=127) , WJets fxfx.

**Comment by arizzi** [comment]
is it fixed by this https://github.com/cms-sw/cmssw/pull/22440 ?

**Comment by perrozzi** [comment]
yes it should. master pr is merged, 94x will be soon

**Comment by arizzi** [comment]
@gpetruc are we going to submit NANO PRs to MAOD branch to be in sync on 945 or we want to make our own analysis release?

**Comment by arizzi** [comment]
NB: the only (real) PR merged in nano that is not yet in 94X is #116

**Comment by gpetruc** [comment]
checked with  `cmsDriver.py test_mc_80X -s NANO --mc --eventcontent NANOAODSIM --datatier NANOAODSIM --conditions auto:run2_mc -n 10 --era Run2_2016,run2_miniAOD_80XLegacy --filein das:/SingleNeutrino/RunIISummer16MiniAODv2-PUMoriond17_magnetOff_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM` and it works.
For SMP-RunIISummer16NanoAOD-00147 the bug is in the input, so I think we can close this issue.
