### ISSUE TITLE
photon supercluster eta not in nanoaod?

### ISSUE THREAD

**Issue by AndrewLevin** [cms-nanoAOD/cmssw#121]
The photon supercluster eta is not currently stored in, and it is not possible to reproduce it with, the nanoaod. I think we want to have this variable for barrel/endcap/gap classification.

**Comment by arizzi** [comment]
please make a PR that adds a single bit "isEB" for that

**Comment by arizzi** [comment]
or two bits if you also have to encode the gap

**Comment by AndrewLevin** [comment]
Here is the pull request:

https://github.com/cms-nanoAOD/cmssw/pull/123
