### ISSUE TITLE
Electron ID: HLT emulation bit

### ISSUE THREAD

**Issue by peruzzim** [cms-nanoAOD/cmssw#139]
We should have a precalculated bit to apply an offline emulation of electron HLT requirements.
To be discussed how it has to be derived and optimized.
The 2016 electron HLT-safe ID derived by EGM POG is not recommended anymore, both for the second part of 2016 and for 2017.

**Comment by lenzip** [comment]
Hello, is this the reason why Electron_cutBased_HLTPreSel is not in the 31Mar2018 nanoAOD?
What should one use instead as an interim solution?

**Comment by arizzi** [comment]
I think egm asked not to use it... @peruzzim  can confirm

**Comment by peruzzim** [comment]
I confirm - we are following up with experts in a separate thread

**Comment by peruzzim** [comment]
No plan to have a central definition for 2017, closing
