### ISSUE TITLE
(Small) bug in definition of HLT trigger filter bits for electrons

### ISSUE THREAD

**Issue by veelken** [cms-nanoAOD/cmssw#142]
The bit coding for the WPLoose and WPTights electron trigger bits in  
   https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/triggerObjects_cff.py#L32
is swapped: according to the documentation in the following line, 
   2=WPLoose, 4=WPTight

**Comment by rdewanje** [comment]
I just corrected the "qualityBitsDoc" line for Electron objects setting bits: "2 = 1e (WPTight), 4 = 1e (WPLoose)" in the PR

**Comment by ktht** [comment]
Fixed in https://github.com/cms-nanoAOD/cmssw/pull/163, though there's still https://github.com/cms-nanoAOD/cmssw/pull/162 open which already had the fix included

**Comment by arizzi** [comment]
hmm I'm afraid 163 made 162 conflicting...

Il ven 4 mag 2018, 00:32 Karl Ehatäht <notifications@github.com> ha scritto:

**Comment by veelken** [comment]
The issue reported in this thread is fixed by PR #162 -> closing this issue.
