### ISSUE TITLE
Regular expressions in "triggerObjects_cff.py" inadequate for e-mu,  mu-mu, 3mu, 3e, 2mu-e and 2e-mu HLT paths

### ISSUE THREAD

**Issue by rdewanje** [cms-nanoAOD/cmssw#148]
The regular expressions given in the file:
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/triggerObjects_cff.py

for electron and muon objects viz.

https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/triggerObjects_cff.py#L32

and

https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/triggerObjects_cff.py#L49

are not adequate for the following HLT Paths:

HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_v* 
HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v* 
HLT_Mu12_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ_v* 
HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_Mass3p8_v4 
HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ 
HLT_Ele16_Ele12_Ele8_CaloIdL_TrackIdL_v*
HLT_TripleMu_12_10_5_v*
HLT_Mu8_DiEle12_CaloIdL_TrackIdL_v*
HLT_DiMu9_Ele9_CaloIdL_TrackIdL_DZ_v*  

This is because their last hlt filter names cannot be matched to any of the reg-exps provided in the "qualityBits" string parameter. For details see this attached xlsx sheet.
[List_HLT.xlsx](https://github.com/cms-nanoAOD/cmssw/files/1855900/List_HLT.xlsx)

**Comment by arizzi** [comment]
can you propose a fix (in form of a PR) ?

**Comment by veelken** [comment]
Hi Andrea,

Ram and I will prepare a PR. Does the syntax in 
    https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/triggerObjects_cff.py#L49
support the syntax
   (part1|part2)
so that we can use the same bit to match different "versions" of the HLT filter name of e.g. the e+mu trigger ?
Otherwise we will need to use bit 1 for the "old" name of the HLT filter and bit 2 for the "new" name of the HLT filter of the e+mu trigger.

**Comment by arizzi** [comment]
@gpetruc knows better the syntax... or you can have a look at the code..

**Comment by arizzi** [comment]
please use the proper Era Switches to support MC campaigns
94X MiniAOD v1
94X MiniAOD v2
80X MiniAOD
and 92X , 80X  for data

**Comment by gpetruc** [comment]
I don't know if `filter("name")` supports regexps (you can try).
the alternative is to replace `N*filter("foo|bar")` with `(? filter("foo") || filter("bar") ? N : 0)` which will work.

**Comment by arizzi** [comment]
@rdewanje @veelken did this enter some PR? if so can we close? if not, any ETA for a PR?

**Comment by veelken** [comment]
Please don't close this issue yet. The work on the HLT filters needs some more time, because we found a problem in the HLT muon filter config (reported in the HN thread: https://hypernews.cern.ch/HyperNews/CMS/get/muon-hlt/593.html ) that we need to understand better.

**Comment by gpetruc** [comment]
Any update on this topic?
