### ISSUE TITLE
Update Type-1 corrected PFMET with new JEC

### ISSUE THREAD

**Issue by veelken** [cms-nanoAOD/cmssw#151]
Hi,

right now, we take the Type-1 corrected PFMET from the 'slimmedMETs' collection ( https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/python/met_cff.py#L20 ), which means that the (old) JEC used when producing the miniAOD are used to compute the Type-1 PFMET corrections. I think we should recompute the Type-1 corrected PFMET with the new JEC, similar to what we do for jets ( in https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/python/jets_cff.py#L115 ).

**Comment by arizzi** [comment]
make sense, anyhow the next centeal productio ln will be starting from miniaod v3 having already the right JECs

**Comment by peruzzim** [comment]
Can you please open a PR to fix this as soon as https://github.com/cms-nanoAOD/cmssw/pull/153#issue-179519175 is understood? Thanks

**Comment by peruzzim** [comment]
https://github.com/cms-nanoAOD/cmssw/pull/153#issue-179519175 is being investigated, @veelken could you please already implement this in nanoAOD and open a PR, so we have this side of the functionality ready?
