### ISSUE TITLE
Too big blocks in NanoAOD from the 05Feb2018 production

### ISSUE THREAD

**Issue by mbluj** [cms-nanoAOD/cmssw#154]
The issue is as follows: some datasets (or more precisely data blocks in the datasets) of NanoAOD samples from the 05Feb2018 production cannot be read with crab due to too high number of lumisections contained in them, see an example crab error message below [1]. Files in the samples look correct, so I think it has something to do with merging which probably requires additional tuning to not build too big blocks. The parent MiniAOD samples are readable with crab.

The (probably incomplete) list of samples with the problem is given below [2].

Finally, there is a crab workaround of the "huge number of lumis" issue [3], but it is not very practical.

---
[1] Block /DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-herwigpp_30M/RunIISummer16NanoAOD-PUMoriond17_05Feb2018_94X_mcRun2_asymptotic_v2-v1/NANOAODSIM#1c4613fa-1112-11e8-a129-02163e01877e contains more than 100000 lumis and cannot be processed for splitting. For memory/time contraint big blocks are not allowed. Use another dataset as input.

[2] Samples with blocks containing too many lumis:
DY1JetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
DYJetsToLL_M-50_TuneCUETP8M1_13TeV-madgraphMLM-herwigpp_30M
ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1
TT_TuneCUETP8M2T4_13TeV-powheg-pythia8
W3JetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
WJetsToLNu_TuneCUETP8M1_13TeV-madgraphMLM-pythia8

[3] https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ#crab_submit_fails_with_Block_con

**Comment by arizzi** [comment]
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/3553.html

**Comment by mbluj** [comment]
In the liked HNs thread any solution of the issues is presented, expect already mentioned, but not very practical crab workaround.

**Comment by arizzi** [comment]
meanwhile they are working on the fix 
https://github.com/dmwm/CRABServer/issues/5645

**Comment by mbluj** [comment]
OK, sounds good. But, is there anything preventing to produce datasets with smaller blocks with less than 100000 lumis? Split by lumi (or by event lumi aware) is quite useful.

**Comment by arizzi** [comment]
it is not nanoaod specific, I think the problem is the size of the data to handle... I suggest you follow up on the computing thread or crab server issue if you have suggestions for the computing guys
