### ISSUE TITLE
PhysicsTools/NanoAOD/data not committed

### ISSUE THREAD

**Issue by tstreble** [cms-nanoAOD/cmssw#158]
The repository PhysicsTools/NanoAOD/data is not committed in the git repository but is needed when running the 94X example sequence mentioned on the twiki
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookNanoAOD#Recipe_for_CMSSW_9_4_X_and_the_c
(for the muon and electron ttH MVA weights for instance)
Is it planned to have this committed centrally?

**Comment by gpetruc** [comment]
It's an external in the release, so CMSSW should find the files if you use the proper release (9_4_6 at the moment).
If you want to test it on an older release checking out a newer NanoAOD  version, you can check out the external data from  https://github.com/cms-data/PhysicsTools-NanoAOD with
````
        mkdir -p $CMSSW_BASE/external/$SCRAM_ARCH/data
        git clone https://github.com/cms-data/PhysicsTools-NanoAOD.git $CMSSW_BASE/external/$SCRAM_ARCH/data/PhysicsTools/NanoAOD/data
````

**Comment by tstreble** [comment]
Ok thanks a lot for the suggestion
Maybe it's worth to update the twiki to reference 9_4_6 instead of 9_4_5_cand1 in the example config then
