### ISSUE TITLE
80X MET Filters

### ISSUE THREAD

**Issue by shane-breeze** [cms-nanoAOD/cmssw#159]
For 2016 data, the recommended MET filter flags are those stated in [1]. From the documentation [2] for the 80X nanoaod content, how can I easily cut on these flags? Some of them are simply stored in nanoAOD; however, I couldn't find these: "Bad PF Muon Filter" and "Bad Charged Hadron Filter".

Do these flags just have different name, e.g. Flag_muonBadTrackFilter?

Is the reconstruction issues related to these flags fixed in the version of MiniAOD used here?

To recreate these flags I believe we need the PF candidates which are not stored.

[1] https://twiki.cern.ch/twiki/bin/view/CMS/MissingETOptionalFiltersRun2#Moriond_2017
[2] https://cms-nanoaod-integration.web.cern.ch/integration/master/mc80X_doc.html

**Comment by arizzi** [comment]
@gpetruc can you comment on muonBadTrackFilter relation with  "Bad PF Muon Filter" and "Bad Charged Hadron Filter" ? 

will we have the updated set of filters in the 80X legacy reminiaod?

**Comment by gpetruc** [comment]
For the legacy re-miniAOD in 94X to be done on the legacy 80X re-reco all the flags should be available (and, given the fix at reconstruction level, their impact should also be less), as they're available in 92X and later.

For 80X 03Feb2017, indeed it looks like the two mentioned filters have to be run at NanoAOD production step, someone should make a PR for it using era modifiers.

**Comment by arizzi** [comment]
@shane-breeze  can you implement the changes and make a PR ?

**Comment by shane-breeze** [comment]
Sure thing. Making the PR now
