### ISSUE TITLE
weird behavior of the LHE_Njets

### ISSUE THREAD

**Issue by gitytakahas** [cms-nanoAOD/cmssw#166]
Dear all, 

I checked LHE_Njets variable by running over this single file (*).
As expected, I see all events have 1. 

However, if I ran over two files in a row (**), then, I got 1 for the first file, but from the second file, I got unreasonable value, such as 251563401473.

Do you have any idea why this happens ? or where I should fix ? 
This might be related to the following warning message from treeReaderArrayTools.py, at the beginning of the even loop. 

> treeReaderArrayTools.py:69: RuntimeWarning: creating executor for unknown type "unsigned char*"
  ret = _vr.Get()[0]

But I see similar error for event number variable, but it shows reasonable value even for the second file. 

Thanks for your help, 
Yuta

(*)
'root://cms-xrd-global.cern.ch//store/mc/RunIIFall17NanoAOD/DY1JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/NANOAODSIM/PU2017_12Apr2018_94X_mc2017_realistic_v14_ext1-v1/00000/88F83F15-B242-E811-808E-001E67792488.root'

(**)
(*) + 'root://cms-xrd-global.cern.ch//store/mc/RunIIFall17NanoAOD/DY1JetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/NANOAODSIM/PU2017_12Apr2018_94X_mc2017_realistic_v14_ext1-v1/10000/0A5AB04B-4B42-E811-AD7F-A4BF0112BDE6.root'

**Comment by gpetruc** [comment]
Hi Yuta,
No idea, but I don't think the treeReaderArrayTools have ever been tested running on multiple files at once. I would assume all data structures would have to be re-created when the file changes
Giovanni

**Comment by gpetruc** [comment]
Hi Yuta,
Did you by chance investigate this further, or have any follow-up PR for nanoAOD-tools?

**Comment by peruzzim** [comment]
Only affects nanoAOD-tools, closing here.
