### ISSUE TITLE
Missing variables for electrons

### ISSUE THREAD

**Issue by arizzi** [cms-nanoAOD/cmssw#17]
track deltaPt?
what else?

**Comment by gpetruc** [comment]
also sync heep stuff with https://github.com/cms-sw/cmssw/pull/20550#issuecomment-334402018 ?

**Comment by gpetruc** [comment]
@emanueledimarco @peruzzim can one of you two pick this up?

**Comment by arizzi** [comment]
@veelken also asked for additional variables

- dEta
- dPhi
- 1/clusterEnergy - 1/trackMomentum

>

**Comment by veelken** [comment]
We need to check with EGamma experts if:
1) superCluster().eta()-eta() is the same as deltaEtaSuperClusterTrackAtVtx()
2) if track deltaPt is the same as (or equivalent to) 1/clusterEnergy - 1/trackMomentum

I will post the first question to the EGamma Hypernews.

**Comment by arizzi** [comment]
@veelken nanoaod egamma experts are reading this thread, no need to post on HN

**Comment by veelken** [comment]
I already posted: https://hypernews.cern.ch/HyperNews/CMS/get/egamma-elecid/123.html

**Comment by emanueledimarco** [comment]
if the need is to emulate the selection at the HLT, one could use the pre-computd bit of the HLT-safe ID of [this twiki]( https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedElectronIdentificationRun2#HLT_safe_selection_for_2016_data). 
The bit is already saved in the nanoAOD, and it can be used in AND with any other cut-based electron ID or also to cover selections using MVA selection, to mitigate the effects of trigger inefficiency given the offline selection (in any case the offline variables doesn't match 100% with the HLT ones: cluster shapes match well, deltaEta/deltaPhi not very good).

**Comment by arizzi** [comment]
@emanueledimarco @peruzzim are we set with egamma requests? IIRC deltaPt has to be added

**Comment by peruzzim** [comment]
done in #63 - can be closed when the PR is merged

**Comment by peruzzim** [comment]
HEEP v7.0 added in #65 @Sam-Harper . Nothing more to add for the moment, closing.
