### ISSUE TITLE
Electron supercluster eta 

### ISSUE THREAD

**Issue by gitytakahas** [cms-nanoAOD/cmssw#170]
Hi, 

I would like to kindly request to add super cluster eta of the electron, as the scale factors have been derived based on this quantity. 
Let me know if this can be easily done in your side. Otherwise, I'll try to do it and request PR. 

Thanks,
Yuta

**Comment by gpetruc** [comment]
You can use `Electron_eta + Electron_deltaEtaSC`.
We store it that way because it is more efficient size wise.
