### ISSUE TITLE
What is CaloMET?

### ISSUE THREAD

**Issue by shane-breeze** [cms-nanoAOD/cmssw#172]
What's the `CaloMET` attribute in nanoAOD?

I've had a look at the documentation and it's not so clear to me. If I look at events with isolated muons pT>30 GeV, and compare `CaloMET` to the (`PF`) `MET` they look similar apart from maybe the resolution with no large bias. So if this is the MET from calorimeter deposits, how come it seems to 'see' the muons in an event?

**Comment by gpetruc** [comment]
It is supposed to be equal to the caloMETPt() of the slimmedMETs from miniAOD

My understanding from the miniAOD config is that it should be the calo MET without muon corrections, but I'd let @gouskos / @zdemirag to confirm.

**Comment by zdemirag** [comment]
in the offline reconstruction, calo met is muon corrected:

process.caloMetM = cms.EDProducer("MuonMET",
    metTypeInputTag = cms.InputTag("CaloMET"),
    muonMETDepositValueMapInputTag = cms.InputTag("muonMETValueMapProducer","muCorrData"),
    muonsInputTag = cms.InputTag("muons"),
    uncorMETInputTag = cms.InputTag("caloMet")
)
