### ISSUE TITLE
Rounding different bw electron pts and jet pts?

### ISSUE THREAD

**Issue by mgratti** [cms-nanoAOD/cmssw#184]
Hi,

is it expected that the rounding is implemented only on some variables, e.g. `Jet_pt` is rounded and `Electron_pt` is not?

Thanks,
Maria Giulia

**Comment by gpetruc** [comment]
yes, the rounding is specified indepenently for different variables depending on the precision needed (eg electrons are measured more precisely than jets) and disk size cost (on average there's more jets x event than electrons)
