### ISSUE TITLE
Documentation & tools for adding extra weights to signal samples

### ISSUE THREAD

**Issue by gpetruc** [cms-nanoAOD/cmssw#190]
For dedicated studies people may want to re-produce privately signal samples with extended sets of weights (e.g. all PDF sets).

It would be good to provide some documentation and possibly tools to simplify this (e.g. customize functions).

We could also extend the weight sets for some central samples that are not large and can be clearly identified as signal from LHE / GEN information, but not for the O(10B) full campaign - an example of this is the Madgraph5 coupling reweighting weights.

This is a follow-up of the discussion in #189. @intrepid42

**Comment by intrepid42** [comment]
Ok, do you think this could be done by producing friend trees? That should be faster than reproducing the complete nanoAOD for the analyses concerned.

**Comment by EmyrClement** [comment]
Is there any progress on the documentation (or tools) for including additional PDF weights?

**Comment by mseidel42** [comment]
Hi, just adding some additional thoughts here:

* I think a mantissa size of 8 should be sufficient for generator weights. Even a precision of 4 just gives errors <1% on the weighted distributions, see this part of plot for lepton pt in W decays:
![image](https://user-images.githubusercontent.com/1311783/58107055-6692bd80-7be9-11e9-9649-ff8c1fd209f0.png)
(green: precision=14, black: precision=8, purple: precision=4)

* I see that the weights are stored as weight/w0, so they should normally be around 1. Maximum weight/w0 I saw in a ttbar file was 300, so a 4-bit exponent would do fine..

* Is there a mechanism to read/store the metadata easily? It would be very useful to have the names of the stored weights accessible

**Comment by kdlong** [comment]
To add to this: we are working on changing the format of the weights at GEN level. I think it is more productive to put effort into making the products stored in EDM more clear before trying to parse what is there in the current non-optimal organization. 

Specifically we think introducing new products with the weight storage modified (likely to have separate vectors for each class of weights: scale/PDF/matrix element/PS) and the LHE header already parsed by the LHEProducer is the best approach.

A bit more info here: https://indico.cern.ch/event/821719/#5-fixing-weights

We plan to have this for physics samples in the ultra legacy. For some early POG samples we would need to fall back to the previous approach.

@kpedro88 and @agrohsje

**Comment by kdlong** [comment]
Related question: is it feasible to configure a sample in central production to run in a mode that would keep more weights, if an analysis knows in advance that they will use a larger set of variations?

**Comment by vlimant** [comment]
ping / reopen if needed
