### ISSUE TITLE
FastSim support

### ISSUE THREAD

**Issue by danbarto** [cms-nanoAOD/cmssw#198]
Producing nanoAOD from FastSim isn't supported currently, see e.g. https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/5690.html
In order to work, triggerObjectTables and l1bits have to be removed from the sequence. One can use the existing '--fast' flag in cmsDriver to switch to a dedicated FastSim sequence. I can open a PR with those changes later.

Currently one can (only?) apply the FastSim JECs on nanoAOD tool level. Is there a way to already apply them in the nanoAOD step?

**Comment by peruzzim** [comment]
#240 + JEC are now read and applied from the GT
