### ISSUE TITLE
HLT_IsoTkMu27_v* trigger bit

### ISSUE THREAD

**Issue by nanlu06** [cms-nanoAOD/cmssw#201]
Dear All,

I have a quick question on the trigger bit information stored in nanoAOD. Does the trigger bit in nanoAOD include HLT_IsoTkMu27_v*? I see there is "HLT_IsoMu27" in the nanoAOD.

I wanted to ask this because for the Higgs to mu mu analysis, the trigger requirement is HLT_IsoMu27_v* OR HLT_IsoTkMu27_v* (analysis twiki page: https://twiki.cern.ch/twiki/bin/viewauth/CMS/HiggsToMuMuRunII#Synchronization)

Many thanks for your help in advance.

Best Regards,

Nan

**Comment by gpetruc** [comment]
all HLT bits available in the input data or MC sample are stored.
