### ISSUE TITLE
VID compressed bitmap for Electron cut-based id with Spring15 tuning

### ISSUE THREAD

**Issue by mgratti** [cms-nanoAOD/cmssw#203]
As the Spring15 tuning is the SUSY recommendation for cut-based id for era 2016, I would like to add the VID compressed bitmap also for this tuning.

**Comment by mgratti** [comment]
This issue is connected with #196, but extends it, as I previously added only the integer for the decision of the working point.
The VID compressed bitmap is needed since  part of the SUS recommendation is to switch off the cuts on PFiso.

**Comment by gpetruc** [comment]
Considering that the Spring15 is not a recommendation of E/gamma and it's being added only for SUS, then if SUS use a different variant of it I think it would make more sense to just add the SUS variant (and label it e.g. CutBasedIdSpring15SusyNoPFIso) rather than add the obsolete ID that people shouldn't use and require people to compute the SUS id from the bitmap.

**Comment by mgratti** [comment]
That makes sense, but it doesn't seem obvious to implement, at least to me.
Any suggestion?

**Comment by mgratti** [comment]
However, as far as I understand, also for 2017, SUS plans to remove the cut on PF iso, so SUS people should learn to compute from the bitmap anyway.

**Comment by peruzzim** [comment]
Will be re-examined once we come to a wider agreement among POGs and PAGs on which IDs to support.

**Comment by mgratti** [comment]
Hi, I think this should be reconsidered, because as far as I understand, there is already an agreement between Egamma POG and SUS PAG to use Spring15 as baseline recommendation for 2016. 
@gzevi may want to comment on this.

**Comment by gzevi** [comment]
Hi, how large is the size increase from the VID bitmaps? Perhaps an alternative would be to simply add the two missing variables needed for cut-based electron ID, and be done with it. You already have: hoe, convVeto, eInvMinusPInv, sieie, dxy, dz, used by lepton ID. You also have dzErr, dxyErr, and ip3d, which perhaps are used by other analyses or energy corrections . For cut-based ID, you are only missing 2 out of 8 variables, deltaPhiSuperClusterTrackAtVtx and dEtaInSeed defined here [1]. If this helps, these could be saved only for a subset of electrons.
Thanks.

[1] http://cmslxr.fnal.gov/source/RecoEgamma/ElectronIdentification/plugins/cuts/GsfEleDEtaInSeedCut.cc#0030

**Comment by mgratti** [comment]
From a small test on 100 MC evts, the increase in size for doubling the vid bitmaps for electrons is +0.06%.
The actual increase due to the addition of the Spring15 vid bitmap will be a bit higher, because the number of bits required to make a compressed bitmap out of the Spring15 cuts is higher than 32, so cannot be contained in a normal integer, but would need a long int.
