### ISSUE TITLE
Missing MVAIso Tau-IDs in 2018 Nano with 10_2_X

### ISSUE THREAD

**Issue by mbluj** [cms-nanoAOD/cmssw#205]
As title says: MVAIso Tau-IDs are missing in NanoAOD with 10_2_X for 2018 data/MC. 
The issue is understood to originate from a missing default configuration for eras different than a set of specific 94X eras which is an obvious bug. It is going to be fixed soon by @mbluj (myself). 
Question is: which branch should be used for the fix, `master-cmsswmaster`?

**Comment by peruzzim** [comment]
We are in the process of creating a new branch based on 10_2_X, could you please test your integration locally on a recent 10_2_X release, but wait to open a PR? Thanks

**Comment by mbluj** [comment]
> We are in the process of creating a new branch based on 10_2_X, could you
> please test your integration locally on a recent 10_2_X release, but wait
> to open a PR? Thanks
>
OK, sure.

**Comment by mbluj** [comment]
Hello, 
is a new branch `master-102X` the one to which is should commit?
Do you think if there is still a chance to have this tau-ID fix for 2018 production which is about to be restarted? If so, what are deadlines?
Thanks.
