### ISSUE TITLE
QGL in miniAOD outdated

### ISSUE THREAD

**Issue by kschweiger** [cms-nanoAOD/cmssw#211]
I noticed, that the QGL that is run in miniAOD (training is loaded from the GT) is outdated. An example would be the GT used for the Fall17MiniAODv2 production [1]. It seems to still point to the v1 version listed here [2]
I got feedback from the QGL experts, that the latest training for the QGL is [3] (listed as **v2b** in [2]). And should be used in the 80X era and onwards. 

I can take care of implementing of the modification. As far as I see, it would require some code that points to a different db file than in the GT. But i have a question about managing the file. What would be the procedure to get/save the newer db file? To my knowledge it is not part of the CMSSW repo so it either has to be loaded on runtime or saved in a `data` folder or similar.

Cheers,
Korbinian

[1] https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/gts/94X_mc2017_realistic_v14
[2] https://twiki.cern.ch/twiki/bin/viewauth/CMS/QGDataBaseVersion
[3] https://github.com/cms-jet/QGLDatabase/blob/master/SQLiteFiles/QGL_cmssw8020_v2.db
[4] https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/python/jets_cff.py#L514-L515

**Comment by arizzi** [comment]
if the data structure is uploadable to the DB, why not creating the proper GT and accessing the file from DB ??

**Comment by kschweiger** [comment]
I brought this the the attention of the experts and will follow up when there are news about this.

**Comment by peruzzim** [comment]
@kschweiger is the code ready to pick it up if the new training gets into the GT?
It seems to me we're not rerunning it in all cases.

**Comment by kschweiger** [comment]
Currently not. But I can make a PR

**Comment by peruzzim** [comment]
Yes please

**Comment by kschweiger** [comment]
Which branch should I use as reference? `master-94X`, `master-102X`or `master`?

**Comment by peruzzim** [comment]
master-102X starting from a 10_2_6 release area, see
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookNanoAOD

**Comment by peruzzim** [comment]
#271 #334
