### ISSUE TITLE
Egamma 2017 Photon ID's 

### ISSUE THREAD

**Issue by scarletnorberg** [cms-nanoAOD/cmssw#255]
Hello comparing with the numbers that are in the current NanoAOD code and the twiki page. I believe that the cuts are from the 92X production and we are now in the 94X version. Here is where I was looking:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/CutBasedPhotonIdentificationRun2#Working%20points%20for%2094X%20and%20later. Are there plans to update these cuts?

**Comment by peruzzim** [comment]
@scarletnorberg which EGM ID are you referring to? The nanoAOD code now calls the VID from EGM.
The Fall17 V2 photon ID is being integrated now (#254), is this what you're referring to?

**Comment by peruzzim** [comment]
@guitargeek @michelif @Sam-Harper @lsoffi @swagata87

**Comment by scarletnorberg** [comment]
Hello I missed the PR for the Fall17 V2 this is what I am referring to. Thanks.
