### ISSUE TITLE
Information to determine whether isolatedtrack is not a lost track

### ISSUE THREAD

**Issue by mgratti** [cms-nanoAOD/cmssw#256]
I can't find a way to determine whether an `IsoTrack` is a pf candidate or a lost track.
My understanding is that the `isPFcand` only requires that the reference to a pf candidate is non null, but this doesn't seem enough to avoid the contribution from losttracks or to distinguish from them.

is there a way to test this something on the line of 
https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/PatAlgos/plugins/PATIsolatedTrackProducer.cc#L239

at the nanoAOD production level ?

**Comment by peruzzim** [comment]
It looks like you want to check if the candidate referenced by IsolatedTrack::packedCandRef() is in the packed PF candidates or lost track collection.

See how the variable `refToCand` is set and passed to the constructor of IsolatedTrack here:
https://github.com/cms-sw/cmssw/blob/CMSSW_10_4_0_pre1/PhysicsTools/PatAlgos/plugins/PATIsolatedTrackProducer.cc#L295-L318
https://github.com/cms-sw/cmssw/blob/CMSSW_10_4_0_pre1/PhysicsTools/PatAlgos/plugins/PATIsolatedTrackProducer.cc#L473-L477

and gets stored here:
https://github.com/cms-sw/cmssw/blob/CMSSW_10_4_0_pre1/DataFormats/PatCandidates/interface/IsolatedTrack.h#L36
