### ISSUE TITLE
Add SubJet_hadronFlavour

### ISSUE THREAD

**Issue by peruzzim** [cms-nanoAOD/cmssw#268]

**Comment by peruzzim** [comment]
is this still desired? @XavierAtCERN please provide a prototype implementation

**Comment by mariadalfonso** [comment]
closing this as "SubJet_hadronFlavour" it has been added 
 
https://cms-nanoaod-integration.web.cern.ch/integration/cms-swmaster/mc106Xul18_doc.html#SubJet
