### ISSUE TITLE
Run updated MET filter for noisy EE crystals

### ISSUE THREAD

**Issue by peruzzim** [cms-nanoAOD/cmssw#269]
@zdemirag @ahinzmann

**Comment by ahinzmann** [comment]
@lathomas and @eioannou Can you open a PR to add the config sniplet for the filter (without adding it to any sequence) to the cmssw/master in the cms-sw repository (i.e. not the nanoAOD one)?

**Comment by lathomas** [comment]
https://github.com/cms-sw/cmssw/pull/25436
