### ISSUE TITLE
Fall17 v2 electron id for era 94X2016

### ISSUE THREAD

**Issue by mgratti** [cms-nanoAOD/cmssw#272]
Hi, sorry to come back to this, but it looks like recommendations for electron ids are evolving 
and there is a concrete possibility that  Fall17 v2 is going to be recommended also for 2016. Can I add the vid nested bitmap for Fall17 v2 electron id for 94X2016?

**Comment by peruzzim** [comment]
please see #267 (to be fixed because it does not run at the moment)

should be discussed how widely and strongly this is recommended by EGM because at the moment it's not on track to make it to the first production  @michelif @Sam-Harper @lsoffi @swagata87

**Comment by lsoffi** [comment]
Hi, as we have stated today [https://indico.cern.ch/event/777545/contributions/3234587/attachments/1766655/2868714/micheli_EG_cmsweek_20181206_4.pdf] Fall17V2 is what EGM recommend to use also for 2016 if the analysis is starting now. If the analysis is already ongoing using 2016 80X ID one is still fine. So things are not evolving. I hope this make it clear how widely and strongly EGM recommend this ID.

**Comment by Sam-Harper** [comment]
> please see #267 (to be fixed because it does not run at the moment)
> 
> should be discussed how widely and strongly this is recommended by EGM because at the moment it's not on track to make it to the first production @michelif @Sam-Harper @lsoffi @swagata87

Its fixed. Sorry, too many balls in the air

**Comment by Sam-Harper** [comment]
Now pushed.  Now on this, as Livia says we would like this. However we are late and the nano can not wait indefinitely so if it misses the deadline, we can put in the next itteration.

**Comment by peruzzim** [comment]
Ok, thanks. We will try to make it happen profiting from the fact that a central validation round has still to take place, and production should start with 2017 that is not affected by this.

**Comment by peruzzim** [comment]
requested to be queued for integration here https://github.com/cms-sw/cmssw/issues/25425#issuecomment-444830591

**Comment by Sam-Harper** [comment]
thanks Marco. Again we dont want to be unreasonable here though so if we're too slow, well thats our fault and the train leaves without us
