### ISSUE TITLE
Crash of multithered run with master-102X on top of 10_2_6

### ISSUE THREAD

**Issue by mbluj** [cms-nanoAOD/cmssw#277]
NanoAOD from master-102X run multithread crashes. It happens probably due to Rivet plugin. 
This crash can be reproduced with master-102X (as for 12/12/2018) topic-merged on top of plain 10_2_6:
```
cmsrel CMSSW_10_2_6
cd CMSSW_10_2_6/src/
cmsenv
git cms-merge-topic cms-nanoAOD:master-102X
```
with configuration for 94X MiniAODv2 inputs by cmsDriver:
```
msDriver.py test94X --fileout file:RunIIAutumn18NanoAOD.root --mc --eventcontent NANOAODSIM --datatier NANOAODSIM --conditions auto:phase1_2017_realistic --step NANO --nThreads 2 --era Run2_2017,run2_nanoAOD_94XMiniAODv2 -n -1 --no_exec
```
Single thread version runs fine.

**Comment by mbluj** [comment]
Example output attached here: [out_test94XMiniAODv2_NANO_2thrds.log](https://github.com/cms-nanoAOD/cmssw/files/2673977/out_test94XMiniAODv2_NANO_2thrds.log)

**Comment by peruzzim** [comment]
The plugin seems coded in a non-thread-safe way. Will need to be temporarily disabled.

**Comment by ktht** [comment]
I can sometimes reproduce the problem in CMSSW 10_2_10 release. When I run on unlimited number of ttH events (`process.maxEvents.input = cms.untracked.int32(-1)` I get the following error:

```
----- Begin Fatal Exception 20-Mar-2019 23:31:03 EET-----------------------
An exception of category 'BadAlloc' occurred while
   [0] Processing  Event run: 1 lumi: 329 event: 46581 stream: 0
   [1] Running path 'nanoAOD_step'
   [2] Calling method for module HTXSRivetProducer/'rivetProducerHTXS'
Exception Message:
A std::bad_alloc exception was thrown.
The job has probably exhausted the virtual memory available to the process.
----- End Fatal Exception -------------------------------------------------
```

When running in `gdb` I get a massive stacktrace (see [this file](https://github.com/cms-nanoAOD/cmssw/files/2990391/rivet_fail.txt)) and the following error:
```
cmsRun: FinalState.cc:77: virtual bool Rivet::FinalState::accept(const Rivet::Particle&) const: Assertion `p.genParticle() == __null || p.genParticle()->status() == 1' failed.
```

I suspect that maybe this line isn't the most thread-safe way of checking for the first event:
https://github.com/cms-nanoAOD/cmssw/blob/ac5914ab1d4192f231b58665c5f040f794177fd5/GeneratorInterface/RivetInterface/plugins/HTXSRivetProducer.cc#L125

I experimented with simple CAS and it seemed to resolve the issue but now I cannot reproduce the problem anymore...

**Comment by peruzzim** [comment]
I'm afraid the way the module is written is inherently not thread-safe. Actually it's not clear whether that is the only unsafe module, or if also running two copies of `GenParticles2HepMCConverter` creates issues.

GEN was made aware of the problem. Until they fix it, I'm afraid all what we could do is remove it from the standard running configuration (as we have done for the ongoing production, with customise commands).
