### ISSUE TITLE
VID bitmap for electron HEEP ID

### ISSUE THREAD

**Issue by sethcooper** [cms-nanoAOD/cmssw#278]
Hi,

Would it be possible to add a VID compressed bitmap for the electron HEEP ID cut variables?

Cheers,
Seth

**Comment by peruzzim** [comment]
is this still desired? for which version of the HEEP ID? there is a new one being introduced now by EGM (7.1) @Sam-Harper

**Comment by Sam-Harper** [comment]
I would go for 7.1, although 7.0 and 7.1 are almost identical here (lower et cut) and scales with calo rather then ep-comped energy for the isolation.
