### ISSUE TITLE
No trigger objects for muons on the 2016 NanoAOD ?

### ISSUE THREAD

**Issue by dellaric** [cms-nanoAOD/cmssw#283]
Dear experts,

when looking at the recent NanoAOD processing, 14Dec2018, we happened to notice the absence of trigger objects associated to muons in the Run2016 data, in particular for both SingleMuon and DoubleMuon datasets (1).

In other words, the condition TrigObj_id == 13 happens to be always false. The previous Run2016 NanoAOD processing, 22Aug2018, seems to behave just like the 14Dec2018 one.

The old Run2016 NanoAOD 05Feb2018 as well as the Summer2016 NanoAOD MC seem instead to be both fine, while the Summer2016 NanoAODv3 MC again seems to have no trigger objects for muons (2).

The 2017 & 2018 NanoAOD for both data and MC look fine, i.e. they contain trigger objects for muons.

Is this a known problem ?

best regards,
Giuseppe. (for the Trieste group)
@dellaric @fabiocos @adarold @federicovazzoler @wvieri

(1)
root -l root://xrootd-cms.infn.it//store/data/Run2016D/SingleMuon/NANOAOD/Nano14Dec2018-v1/280000/33B16096-0961-B347-8476-F9E2258A3E9C.root
root [0] 
Attaching file root://xrootd-cms.infn.it//store/data/Run2016D/SingleMuon/NANOAOD/Nano14Dec2018-v1/280000/33B16096-0961-B347-8476-F9E2258A3E9C.root as _file0...
(TFile *) 0x383f810
root [1] Events->Draw("1.*TrigObj_filterBits:1.*TrigObj_id","TrigObj_id==13","colz")
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
(long long) 0

root -l root://xrootd-cms.infn.it//store/data/Run2016D/SingleMuon/NANOAOD/22Aug2018-v1/100000/5E522C88-34A9-E811-A1E2-68CC6EA5BE7A.root
root [0] 
Attaching file root://xrootd-cms.infn.it//store/data/Run2016D/SingleMuon/NANOAOD/22Aug2018-v1/100000/5E522C88-34A9-E811-A1E2-68CC6EA5BE7A.root as _file0...
(TFile *) 0x327b160
root [1] Events->Draw("1.*TrigObj_filterBits:1.*TrigObj_id","TrigObj_id==13","colz")
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
(long long) 0

(2)
root -l root://xrootd-cms.infn.it//store/data/Run2016E/DoubleMuon/NANOAOD/05Feb2018-v1/00000/F88FC831-6E0C-E811-8625-90E2BAD4912C.root
root [0] 
Attaching file root://xrootd-cms.infn.it//store/data/Run2016E/DoubleMuon/NANOAOD/05Feb2018-v1/00000/F88FC831-6E0C-E811-8625-90E2BAD4912C.root as _file0...
(TFile *) 0x33421c0
root [1] Events->Draw("1.*TrigObj_filterBits:1.*TrigObj_id","TrigObj_id==13","colz")
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
(long long) 56496

root -l root://xrootd-cms.infn.it//store/mc/RunIISummer16NanoAOD/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/PUMoriond17_05Feb2018_94X_mcRun2_asymptotic_v2_ext2-v1/00000/40F73612-D010-E811-AAC3-549F358EB762.root
root [0] 
Attaching file root://xrootd-cms.infn.it//store/mc/RunIISummer16NanoAOD/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/PUMoriond17_05Feb2018_94X_mcRun2_asymptotic_v2_ext2-v1/00000/40F73612-D010-E811-AAC3-549F358EB762.root as _file0...
(TFile *) 0x38ae320
root [1] Events->Draw("1.*TrigObj_filterBits:1.*TrigObj_id","TrigObj_id==13","colz")
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
(long long) 2707716

root -l root://xrootd-cms.infn.it//store/mc/RunIISummer16NanoAODv3/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v3_ext2-v1/270000/42A20D0E-51C9-E811-80A6-A4BF0102A5F9.root
root [0] 
Attaching file root://xrootd-cms.infn.it//store/mc/RunIISummer16NanoAODv3/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v3_ext2-v1/270000/42A20D0E-51C9-E811-80A6-A4BF0102A5F9.root as _file0...
(TFile *) 0x3072850
root [1] Events->Draw("1.*TrigObj_filterBits:1.*TrigObj_id","TrigObj_id==13","colz")
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1

**Comment by arizzi** [comment]
I guess this customization should be updated for running on re-miniaod datasets
https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/python/triggerObjects_cff.py#L141

in particular when running nanoaod on latest remini from 2016 the 80X customizations are switched off, meaning also the trigger customization is off.
@peruzzim @fgolf what are the era customization to use for 2016 on reminiaod input?

**Comment by peruzzim** [comment]
Yes, I am afraid that was forgotten. The relevant modifier is run2_nanoAOD_94X2016.

**Comment by arizzi** [comment]
@dellaric can you test a fix that triggers the l1obj definition update also on that era modifier and submit a PR (to this github)?

**Comment by dellaric** [comment]
@arizzi 

I'm afraid don't know how to fix the problem, otherwise I would have done it before writing this report ...

**Comment by peruzzim** [comment]
@dellaric could you please try to change here:

https://github.com/cms-nanoAOD/cmssw/blob/226bca0d9cc12bb2f79b966491341f7383bfc98a/PhysicsTools/NanoAOD/python/triggerObjects_cff.py#L156-L159

to be `(run2_miniAOD_80XLegacy | run2_nanoAOD_94X2016).toModify(...`

**Comment by dellaric** [comment]
@peruzzim 

ok, I've tested the suggested fix using:

cmsDriver.py myNanoProdMc -s NANO --mc --eventcontent NANOAODSIM --datatier NANOAODSIM --no_exec --conditions 94X_mcRun2_asymptotic_v3 --era Run2_2016,run2_nanoAOD_94X2016

but I obtained the error:

  File "/home/dellaric/work/cms/CMSSW_10_2_10/python/PhysicsTools/NanoAOD/triggerObjects_cff.py", line 156, in <module>
    (run2_miniAOD_80XLegacy | run2_nanoAOD_94X2016).toModify(
NameError: name 'run2_nanoAOD_94X2016' is not defined

mmmm ...

**Comment by dellaric** [comment]
Ok, fixed adding at the top:

from Configuration.Eras.Modifier_run2_nanoAOD_94X2016_cff import run2_nanoAOD_94X2016

time to find a file to run a test ...

**Comment by dellaric** [comment]
Test done on 

root://xrootd-cms.infn.it//store/mc/RunIISummer16MiniAODv3/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/MINIAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v3_ext2-v1/270000/FEFC23FC-37C7-E811-97DA-0CC47AA53D86.root

No trigger objects with original PhysicsTools/NanoAOD/python/triggerObjects_cff.py

3 trigger objects for muons with the fixed version.

root [0] 
Attaching file myNanoProdMc_NANO.ORIG.root as _file0...
(TFile *) 0x2f3ea50
root [1] Events->Draw("1.*TrigObj_filterBits:1.*TrigObj_id","TrigObj_id==13","colz")
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
(long long) 0
root [2] .q
farmui01[156]: root-6.12 -l myNanoProdMc_NANO.GOOD.root 
root [0] 
Attaching file myNanoProdMc_NANO.GOOD.root as _file0...
(TFile *) 0x2db2c00
root [1] Events->Draw("1.*TrigObj_filterBits:1.*TrigObj_id","TrigObj_id==13","colz")
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
(long long) 3

patch in attachment

[trigger_Objects_cff_94X2016.txt](https://github.com/cms-nanoAOD/cmssw/files/2783465/trigger_Objects_cff_94X2016.txt)

**Comment by peruzzim** [comment]
Can you please open pull requests?

**Comment by dellaric** [comment]
Unfortunately, I can't, sorry. Please use the patch I attached in my last reply.

**Comment by dellaric** [comment]
Apparently I managed to do a PR using the web interface, please let me know if it is ok.

**Comment by peruzzim** [comment]
Analyzers please note: the selection applied, and the definition of stored quality bits, for electron and tau trigger objects was also incorrectly set to the version suited for 2017.
This was noted first for muons, as no object was passing the wrong selection there.

**Comment by peruzzim** [comment]
Fixed by #296 #297
