### ISSUE TITLE
Loose Muon ID missing in NanoAOD

### ISSUE THREAD

**Issue by mzarucki** [cms-nanoAOD/cmssw#301]
Dear NanoAOD experts,

It seems that the cut-based Loose muon ID is missing in NanoAOD. 

Will this be integrated?

Best regards,
Mateusz

**Comment by peruzzim** [comment]
Dear Mateusz,

 the loose ID is required as a preselection on all muons that get stored in NanoAOD:

https://github.com/cms-nanoAOD/cmssw/blob/ac5914ab1d4192f231b58665c5f040f794177fd5/PhysicsTools/NanoAOD/python/muons_cff.py#L56

**Comment by mzarucki** [comment]
Dear Marco,

Thank you for clarifying this!

Best regards,
Mateusz
