### ISSUE TITLE
High pT muon ID + other additions

### ISSUE THREAD

**Issue by peruzzim** [cms-nanoAOD/cmssw#304]
@Fedespring

**Comment by Fedespring** [comment]
@peruzzim the "other additions" have been included in the miniAOD pat::muon data format few days ago. Therefore, to be propagated to the nanoAOD, I should start from one of the latest integration build releases (10_0_6_X). But your recommendation is to start from 10_4_X/10_5_X. How do you want to proceed?

**Comment by peruzzim** [comment]
#364 #369 

warning, the new version of highPt muon ID is technically not reproducible when running from 102X, and this leads to a different result than when run from 106X

**Comment by Fedespring** [comment]
ciao Marco,
this is expected, since in 10_4_X the cuts insied the HighPtID selector
have been modified. Different results are expected by applying the same
selector in nanoAOD in 10_2 and 10_6
