### ISSUE TITLE
Update leptonMVA training

### ISSUE THREAD

**Issue by peruzzim** [cms-nanoAOD/cmssw#307]
syncing with the updated training to go in UL

@sscruz

**Comment by sscruz** [comment]
ciao @peruzzim 
I have the weights for the updated training here: http://www.hep.uniovi.es/sscruz/LepMVA/, 
and made the necessary changes to the code here: https://github.com/cms-nanoAOD/cmssw/compare/master-102X...sscruz:LepMVA_nanoAOD

**Comment by peruzzim** [comment]
Thanks - but we will need to protect the modifiers currently in use for the NanoAODv4 production campaign with new modifiers. Will keep you posted.

**Comment by peruzzim** [comment]
#336
