### ISSUE TITLE
Additional variables for noise jet rejection

### ISSUE THREAD

**Issue by peruzzim** [cms-nanoAOD/cmssw#312]
store additional jet variables if deemed possibly useful for forward jet cleaning

**Comment by arizzi** [comment]
@lathomas

**Comment by lathomas** [comment]
@arizzi  So we haven't yet identified good variables (on top of what's already saved in NANO) but something that could turn out to be useful is to store the bunch crossing position (maybe it's already there but can't find it). This is only an integer so I guess it should be fine. Can you confirm? 

In fact in the future it would be great to have more information about the bunch crossing structure and the bunch crossing position in a train (for example to study OOT PU) but that requires some work as apparently some of this information is even missing in MINIAOD.

**Comment by arizzi** [comment]
I guess the BX number can be added but then you need a filling schema to know where exactly it is in a train... or you wanted to store directly something more elaborated (e.g. the position in the train?)

**Comment by lathomas** [comment]
For now, the BX number would already be useful to have yes ! Thanks !

**Comment by peruzzim** [comment]
Before starting to add variables to support studies that are not yet really defined - it seems to me - I would suggest to devise a clear strategy to use this information. Tests can be done in small private productions for development.

**Comment by lathomas** [comment]
So the following plots [1-2] were made using this exact information (the bx nb from MINIAOD that I manually mapped to the bx position using the filling schemes from WBM ). 

All I ask for here is an integer (from 0 to ~4000). 

For additional variables, I agree the strategy has to be defined better. 

Thanks, 

[1] https://indico.cern.ch/event/716249/contributions/2944680/attachments/1621895/2580972/METvsbx.pdf
[2] https://indico.cern.ch/event/799011/contributions/3319913/attachments/1796609/2929100/metin2018_bxandPUeffect.pdf

**Comment by lathomas** [comment]
Hello.
For the "noise" in ECAL endcaps, this was to a large extent related to the initial imperfect calibration which is fixed to a large extent in Ultra Legacy. 
Regarding noise in the HF, some HF variables have been added to NANO in this PR: 
https://github.com/cms-sw/cmssw/pull/31271

I think we can therefore close this issue.
