### ISSUE TITLE
Add EGM scales and smearings for 2018 datasets

### ISSUE THREAD

**Issue by peruzzim** [cms-nanoAOD/cmssw#314]

**Comment by peruzzim** [comment]
I can help implementing this if someone from EGM assists me with the technical aspects - @Sam-Harper @lsoffi who can I ask? The recipe on the twiki includes unmerged code... thanks

**Comment by Sam-Harper** [comment]
the scale & smearings for 2018 are not final and thus can not go in the nano. We have the final corrections from Rajdeep but need to validate them.

**Comment by Sam-Harper** [comment]
@rchatter

**Comment by peruzzim** [comment]
#357 #365
