### ISSUE TITLE
Expression parsing not working in object tables

### ISSUE THREAD

**Issue by ktht** [cms-nanoAOD/cmssw#322]
It seems that the parser does not handle long conditionals correctly, eg:
https://github.com/cms-nanoAOD/cmssw/blob/4bbadca4cf241f9536dc6d79d670af03704478fa/PhysicsTools/NanoAOD/python/muons_cff.py#L109

In event `1:6888:978076` in file [*] there's one muon w/ jetRelIso = -2, which should not be possible. However, when I duplicate the same branch and give it a new name (e.g. `jetRelIso_new`) the values in the new branch appear correct. Illustrations:

![Screenshot_20190423_003702](https://user-images.githubusercontent.com/6233872/56533356-285d9c00-6560-11e9-906d-3b688859fdc5.png)
![Screenshot_20190423_003729](https://user-images.githubusercontent.com/6233872/56533422-44613d80-6560-11e9-854e-39b0a3f5c804.png)

The issue seems to affect the `else` part of the ternary operator, i.e. the case when there's no associated jet to the lepton in the current example. I'm now wondering if this bug also affects the evaluation of `mvaTTH` variable because the same syntax (and probably the same parser) is used there:

https://github.com/cms-nanoAOD/cmssw/blob/4bbadca4cf241f9536dc6d79d670af03704478fa/PhysicsTools/NanoAOD/python/muons_cff.py#L67

[*] `/store/mc/RunIISummer16MiniAODv3/ttHToNonbb_M125_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8/MINIAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v3-v2/120000/F24F2D5E-DDEC-E811-AF50-90B11C08AD7D.root`

**Comment by arizzi** [comment]
are you sure it is not a version of NANOAOD affected by this era Switch ?
https://github.com/cms-nanoAOD/cmssw/blob/4bbadca4cf241f9536dc6d79d670af03704478fa/PhysicsTools/NanoAOD/python/muons_cff.py#L133

**Comment by ktht** [comment]
Thanks, I totally overlooked it. I found a similar problem with the same symptoms in my custom NanoAOD code so I assumed that the problem exists here, too, but I was wrong. Sorry for the noise.
