### ISSUE TITLE
Support for re-running E/gamma energy scales & smearing

### ISSUE THREAD

**Issue by Sam-Harper** [cms-nanoAOD/cmssw#323]
There has been a user request to re-run the photon scales & smearing in nanoAOD. This is impossible as it is missing whether the seed crystal is in gain12,6 or 1.

https://hypernews.cern.ch/HyperNews/CMS/get/egamma/2222/1/1.html

Andrea R. suggested to open an issue here. For photon support its relatively trivial, for electron support, it is harder due to the E/p combination and would likely need upto 8 additional variables. 

Is this a workflow we wish to support?

**Comment by arizzi** [comment]
can we compute the uncertainties on the electrons without those 8 variables?

I mean the idea would be 
- compute central values when making nanoaod (with as many vars as you need in input)
- compute variations from nanoaod (hopefully not needing a large number of input variables)

**Comment by Sam-Harper** [comment]
>can we compute the uncertainties on the electrons without those 8 variables?

depends. So the 8 variables are for the E/p combination. For some electrons, the ecal energy is effectively ignored, for some its the sole measurement. So by not doing the combination you dont know which is which.  But thinking about it, if we apply the uncertainties on the ecal energy to the electron energy, at worst we're just conservative (baring edge cases) so I think that would be totally fine. Anybody who really really needs the most precise numbers can use miniAOD. 

So we just need to add a single variable then which  can take 3 values so impact would be small.

**Comment by peruzzim** [comment]
gain of the seed crystal introduced with #341, the rest (variables to rerun the E/p combination) is not in the scope of this data format
