### ISSUE TITLE
Store DeepJet (DeepFlavour) C discriminator

### ISSUE THREAD

**Issue by mondalspandan** [cms-nanoAOD/cmssw#339]
Currently NanoAOD stores only Jet_btagDeepFlavB for the DeepJet tagger (as per the documentation of 102X). We are planning to test DeepJet as a c-tagger for VHcc 2017 & 2018 analysis and would like to have Jet_btagDeepFlavC available in future NanoAOD campaigns.

**Comment by peruzzim** [comment]
#340 #342
