### ISSUE TITLE
Enrich dressed lepton information

### ISSUE THREAD

**Issue by peruzzim** [cms-nanoAOD/cmssw#344]
... with tau inheritance and extended acceptance

@emanca @intrepid42

**Comment by peruzzim** [comment]
done what it could for the moment in #355 #367

**Comment by mariadalfonso** [comment]
@emanca @intrepid42 @peruzzim 

can this item be closed, or something else need an update ?

**Comment by emanca** [comment]
This is enough for now, thanks, we can close the issue.
