### ISSUE TITLE
Add recipe for to use Ele32_WPTight throughout the year for 2017 data

### ISSUE THREAD

**Issue by Sam-Harper** [cms-nanoAOD/cmssw#345]
It would good to allow Ele32 in 2017 to be used in nano AOD.

https://hypernews.cern.ch/HyperNews/CMS/get/egamma-hlt/263/1/1/2/1.html

It shouldnt be overly difficult to do nor take any space, just we need to do it.

**Comment by peruzzim** [comment]
#359 #365
