### ISSUE TITLE
Why do we have both master and master-cmsswmaster?

### ISSUE THREAD

**Issue by andrzejnovak** [cms-nanoAOD/cmssw#346]
It's confusing and not documented in the twiki https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookNanoAOD#Recipe_for_the_current_HEAD_of_N

**Comment by peruzzim** [comment]
It's because of historical reasons, the twiki actually always points to master-cmsswmaster.
I agree it's confusing, we can update it in a moment of less intense development.
