### ISSUE TITLE
NanoGEN

### ISSUE THREAD

**Issue by nsmith-** [cms-nanoAOD/cmssw#350]
Re-opening in correct repo.

I think it would be really useful for many people to be able to easily (e.g. via cmsDriver) add a NanoAOD-like output starting from the GEN data tier, for MC studies.  One would have access to all the nice gen additions included in the current NanoAOD, and any already-produced samples could easily be compared to newly generated samples, which can be made privately quite easily without the necessity for the whole SIM-DIGI-RECO-AOD-MINIAOD chain.

To do this, we just need to separate the gen-only portions of `nanoSequenceMC` from those that require reconstructed objects.  I made a first attempt to remove any reco-related tables and redirect the input sources when they differ, by starting with `cmsDriver.py myNanoProdMc -s NANO --mc --eventcontent NANOAODSIM --datatier NANOAODSIM --no_exec --conditions auto:run2_mc` from the [TWiki](https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookNanoAOD#Running_on_various_datasets_from) and adding the lines shown below, then edited `process.nanoAOD_step = cms.Path(process.nanogenSequence)`:

```python
# Hacking at nanoSequenceMC from PhysicsTools.NanoAOD.nano_cff
process.jetMC.remove(process.jetMCTable)
process.nanogenSequence = cms.Sequence(
    process.genParticleSequence+
    process.genParticles2HepMC+
    process.particleLevel+
    process.genJetTable+
    process.patJetPartons+
    process.genJetFlavourAssociation+
    process.genJetFlavourTable+
    process.genJetAK8Table+
    process.genJetAK8FlavourAssociation+
    process.genJetAK8FlavourTable+
    process.tauGenJets+
    process.tauGenJetsSelectorAllHadrons+
    process.genVisTaus+
    process.genVisTauTable+
    process.genTable+
    process.genWeightsTable+
    process.genParticleTables+
    process.particleLevelTables+
    process.lheInfoTable
)
process.finalGenParticles.src = cms.InputTag("genParticles")
process.genParticles2HepMC.genParticles  = cms.InputTag("genParticles")
process.patJetPartons.particles = cms.InputTag("genParticles")

process.genJetTable.src = cms.InputTag("ak4GenJetsNoNu")
process.genJetFlavourAssociation.jets = process.genJetTable.src
process.genJetFlavourTable.src = process.genJetTable.src
process.genJetFlavourTable.jetFlavourInfos = cms.InputTag("genJetFlavourAssociation")
process.genJetAK8Table.src = cms.InputTag("ak8GenJetsNoNu")
process.genJetAK8FlavourAssociation.jets = process.genJetAK8Table.src
process.genJetAK8FlavourTable.src = process.genJetAK8Table.src
process.tauGenJets.GenParticles = cms.InputTag("genParticles")
process.genVisTaus.srcGenParticles = cms.InputTag("genParticles")
```

**Comment by arizzi** [comment]
I think it may make a difference if plan to have central production of thia nanogen or not. If not any kind of config is fine.
If we plan for central prod I guess we need an official NANOGEN and NANOEDMGEN format/tier and proper adaption of cmsDriver

**Comment by nsmith-** [comment]
I think this is likely not something interesting for central production.  Although, I'd like to get it to work with cmsDriver.  Is there an idiom for adjusting nano configuration via cmsDriver already, say to include extra information as some groups might want to do?

**Comment by arizzi** [comment]
you can use customize, but anything more complex need changes into cmsdriver itself

**Comment by kdlong** [comment]
Personally I think this really could be useful for central production. There would be a lot of advantages to producing samples that people can easily analyze in advance of full production. How much work it would be to support?

**Comment by peruzzim** [comment]
Let's revive this proposal, as we're going to touch the nanoSequence also for other reasons.
Is there a concrete interest from GEN to use this centrally? We should define additional data tiers only if it's really needed.

@agrohsje @qliphy

**Comment by peruzzim** [comment]
any news on this? can you please comment, maybe better via mail rather than here, so we can follow up with all stakeholders? thank you

**Comment by qliphy** [comment]
Sorry for being late and thanks @peruzzim.   I saw you already posted on [gen hn](
https://hypernews.cern.ch/HyperNews/CMS/get/generators/4480.html).  Let's hear more comments and discuss there.    As from GEN, we can arrange some discussions at next GEN meetings, e.g. [Oct 1st](https://indico.cern.ch/event/841562/), if it is not too late.   Anyone is able to give a report there?

BTW:  If the plan is for central productions,  it should involve pdmv.  Probably we need to discuss also at PPD.

**Comment by pgunnell** [comment]
I think the implementation in  central production is quite straightforward. We just need an additional flow.

**Comment by kdlong** [comment]
I'm not sure if this was working for you @nsmith-, but I've been looking at it and made a few modifications, some which were necessary to run (for a variety of setups), and others just to be cleaner

-- Issue I can't get around: I can't get the genMet to work. As far as I can tell, just changing process.metMCTable.src = cms.InputTag("genMetTrue") doesn't work because the slimmedMETs has a vector of different pat::Met, so the access to the values is different. Possible could get around this by creating a dummy slimmedMETs, but I haven't looked into this yet. Error when trying to use genMetTrue as src is here [1].

* Option to consider: Use the full hepMC and genParticles rather than producing the slimmed finalGenParticles and the reduced hepMC from these. 
NOTE: This leads to all the GenParticles being stored. In many gen studies this would be desirable, but in some cases it's just extra bloat, and it leads to a difference between NanoGen and just taking the Gen from a normal Nano file. 

* For reasons I don't understand, I need to remove the command below if I run a single-step production of Gen-->NanoGen and keep the Gen output. I don't really understand the point of it, its added by cmsDriver by default, but they just add a bunch of pat stuff I don't want for this. Does anyone know?
```
from PhysicsTools.PatAlgos.tools.helpers import associatePatAlgosToolsTask
 associatePatAlgosToolsTask(process)
```

* To keep in mind: In CMSSW_7_1X, you have to schedule GenJetsNoNu, GenJets include neutrinos by default

The working config I'm using is here: https://gist.github.com/kdlong/37349d3248556b0712d3ad0e4f49afa9

I'm using it to validate a (huge) simulation planned for the W mass. It would be awesome to do this in central production, does anyone know what it would take to get it to that point?

[1] 
```
----- Begin Fatal Exception 13-Dec-2019 00:29:27 CET-----------------------
An exception of category 'StdException' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'nanoAOD_step'
   [2] Calling method for module SimpleCandidateFlatTableProducer/'metMCTable'
Exception Message:
A std::exception was thrown.
no method or data member named "genMET" found for type "reco::GenMET"
----- End Fatal Exception -------------------------------------------------
```

**Comment by guitargeek** [comment]
Hi Kenneth! Indirectly via Philip and you I learned of the possibility or creating nanos from raw GEN and this would be perfect for us. So your MET problem was now my problem too... Maybe you solved it in the meantime, but here is what I did: just reset the variables which the `metMCTable` fills into it columns (remember before it was `genMET.pt` and `genMET.phi`):
```Python
process.metMCTable.variables = cms.PSet(
       pt  = Var("pt",  float, doc="pt", precision=10),
       phi = Var("phi", float, doc="phi", precision=10),
    )
```
To get the `Var` class, import `PhysicsTools.NanoAOD.common_cff.py`. To make your snipped run, I also needed to comment out the rivet HTXS stuff which I don't think we need and removed the tautagger process. Now it works!

**Comment by kdlong** [comment]
Thanks Jonas, this works for me! 

What CMSSW are you using? The Rivet producer works for me in CMSSW_10_2_X (tried X > 15)

**Comment by guitargeek** [comment]
Yes you are right, it was the version. I used 10_2_3 which didn't include these plugins yet. Cool, so now everything works!

**Comment by nsmith-** [comment]
I think I just dropped genMet because for my purposes I didn't need it and it was not playing nicely.  Seems you've figured it out.  I also ran the NANOGEN in a separate step with something in the 10_2_X branch.

**Comment by guitargeek** [comment]
Cool, thanks Nick for this very valuable insight that something like NanoGEN can be produced!

**Comment by kdlong** [comment]
Starting from Jonas' config, a working cmsDriver implementation is in fact quite simple: 
https://github.com/kdlong/cmssw/blob/NanoGenWithWeights/PhysicsTools/NanoAOD/python/nanogen_cff.py
https://github.com/kdlong/cmssw/commit/a2912ec22d2685d674007d9cbfa88077dffb7dd4

This is built on top of the gen weights stuff I've been slowly converging on but could be trivially made to work with the current Nano producers. Would be cool to have this supported in production.

**Comment by kdlong** [comment]
Hi all,

Like I said, this is currently tied up in the weight refactoring. I could pretty easily separate out the cmsDriver + config working with the current gen/lhe producers in Nano if people are interested in trying it shortly.  Just let me know, and I can prepare a PR.

**Comment by DryRun** [comment]
Hi @kdlong - a little late here, but I'd be interested in trying it out! (It seems straightforward enough, so if you're busy, I'm sure I can put it together myself)

**Comment by DryRun** [comment]
Update: got it working at https://github.com/DryRun/cmssw/tree/CMSSW_10_6_11-NANOGEN

**Comment by kdlong** [comment]
Excellent! I'll try it out today.

**Comment by kdlong** [comment]
Hi @DryRun, all:

I added some additional changes that I'd been working on in another branch. Specifically this should fix the LHEParticles and allow the cmsDriver to work either starting from Gen or starting from MiniAOD (if you wanted to do a NanoGEN keeping more gen particles or genweights). You can find this version here:

https://github.com/kdlong/cmssw/pull/8

I can make a PR to your branch or to cms-sw/cmssw if others think it's ready for that.

One thing to note is that by default this will keep all gen particles, whereas for MiniAOD/NanoAOD there are additional levels of pruning applied. The pruning options could be enabled by inserting additional customize functions that can be called from cmsDriver.

**Comment by kdlong** [comment]
Also worth pointing out that I have some configs and cmsDriver commands that I've been testing here: https://github.com/kdlong/WMassNanoGen

**Comment by kdlong** [comment]
Also to add, I made a version on top of CMSSW_11_0_2 that can be merged with git cms-merge-topic kdlong:NanoGen_11_0_2

**Comment by DryRun** [comment]
@kdlong thanks! I'll just cherry-pick your fixes.

**Comment by mariadalfonso** [comment]
closing this PR 
feature integrated here cms-sw#30306
