### ISSUE TITLE
Producing the right NanoAOD from previous MiniAOD version

### ISSUE THREAD

**Issue by guitargeek** [cms-nanoAOD/cmssw#366]
Hello all,

I tried to find a hypernews about nanoAOD and looked in [1] if there are some instructions on where to ask for NanoAOD support, but I could not find something specific. Therefore, I just ask here. Please tell me if this is not the right place and I will do it right next time!

Now my question: for my analysis I need `WWZJetsTo4L2Nu` samples for 2016, 2017 and 2018. For the last two years, these samples exists:

```
/WWZJetsTo4L2Nu_4f_TuneCP5_13TeV_amcatnloFXFX_pythia8/RunIIAutumn18NanoAODv4-Nano14Dec2018_102X_upgrade2018_realistic_v16-v1/NANOAODSIM
/WWZJetsTo4L2Nu_4f_TuneCP5_13TeV_amcatnloFXFX_pythia8/RunIIFall17NanoAOD-PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/NANOAODSIM
```

For 2016, it's only available in MiniAOD:

```
/WWZJetsTo4L2Nu_4f_TuneCUETP8M1_13TeV_aMCatNLOFxFx_pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v2/MINIAODSIM
```
Can I use this one for a full Run 2 analysis, i.e. is it compatible with the existing 2016 NanoAODv4 samples? Or would I need a MiniAODv3 for that, as hinted by [2]?

If the answer is yes and I can use it, which configuration do I need to reduce that MiniAOD sample to NanoAOD? Sorry, I'm still a bit lost with the different NanoAOD versions and productions.

Thank you very much and cheers,
Jonas

[1] https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookNanoAOD
[2] https://twiki.cern.ch/twiki/bin/viewauth/CMS/PdmVAnalysisSummaryTable

**Comment by peruzzim** [comment]
answered on HN

**Comment by guitargeek** [comment]
Thank you very much, I must have missed the nanoAOD hypernews then. I'll look for it again!
