### ISSUE TITLE
Fix GenDressedLepton_hasTauAnc variable in 102X

### ISSUE THREAD

**Issue by peruzzim** [cms-nanoAOD/cmssw#368]
DQM tests show that this variable is always false when running in 102X, while it shows true for some leptons when running in 106X, on the same MINIAOD files in all releases (102X,94X,80X).

@emanca @intrepid42

**Comment by mseidel42** [comment]
Link to DQM: https://github.com/cms-nanoAOD/cmssw/pull/355#pullrequestreview-238962849

**Comment by peruzzim** [comment]
This was just due to cms-sw#26661 missing in the testing area. Fixed by #375.
