### ISSUE TITLE
Keep lepton transverse mass variable from (mini)AOD?

### ISSUE THREAD

**Issue by mzarucki** [cms-nanoAOD/cmssw#370]
Dear NanoAOD experts,

Would it be desirable to keep the lepton transverse mass variable (mt) that is already stored at AOD and miniAOD levels?

I understand that it's use is analysis-specific and one can have various definitions, so if there are objections, we can re-calculate it privately..

Best regards,
Mateusz

**Comment by peruzzim** [comment]
@mzarucki this is a redundant information, it can be calculated even with a free function, and we would not cover the cases where one wants do also use other objects in the transverse mass.
I think we should not include it, if you want to discuss further please follow up privately.
