### ISSUE TITLE
Sudden spike in memory consumption

### ISSUE THREAD

**Issue by ktht** [cms-nanoAOD/cmssw#373]
While profiling DeepTau IDv2 implementation, I came across a problem where one particular event triggers ~500MB increase in memory consumption (both VSIZE and RSS). This is clearly a problem because the RSS memory goes above 2000MB which is the default limit in CRAB jobs.

The problem is present in vanilla CMSSW 10_2_10 release and in CMSSW 10_2_14 release based on this fork (no bells or whistles, just followed [NanoAOD Workbook](https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookNanoAOD) and merged PRs 26370+
26794 & added missing data files). The problem happens with event 1:97:164559 (or 900th event) in file [*].
It's always reproducable with:

```
cmsDriver.py nanoAOD --step=NANO --mc --era=Run2_2017,run2_nanoAOD_94XMiniAODv2 \
  --conditions=102X_mc2017_realistic_v6 --no_exec --fileout=tree.root \
  --number=2 --eventcontent NANOAODSIM --datatier NANOAODSIM --nThreads=1 \
  --python_filename=cfg.py \
  --customise_commands='process.MessageLogger.cerr.FwkReport.reportEvery = 1; process.source.skipEvents=cms.untracked.uint32(899)' \
  --filein=root://cms-xrd-global.cern.ch//store/mc/RunIIFall17MiniAODv2/ttHJetToNonbb_M125_TuneCP5_13TeV_amcatnloFXFX_madspin_pythia8/MINIAODSIM/PU2017_12Apr2018_new_pmx_94X_mc2017_realistic_v14-v1/100000/7C60AC2B-E76F-E811-9D60-0025905B860C.root

cmsRun cfg.py &> log.txt
```
(Although I used and recommend using local file to exclude effects due to network.)
The job runs over 2 events: 1st event (899th in the file) is to showcase normal memory consumption and the 2nd event (900th) is the triggering event. `SimpleMemoryCheck` [$] prints the following

```
MemoryCheck: event : VSIZE 2060.99 0 RSS 1648.28 0 HEAP-ARENA [ SIZE-BYTES 0 N-UNUSED-CHUNKS 1 TOP-FREE-BYTES 0 ] HEAP-MAPPED [ SIZE-BYTES 0 N-CHUNKS 0 ] HEAP-USED-BYTES 0 HEAP-UNUSED-BYTES 0
MemoryCheck: event : VSIZE 2637.19 0 RSS 2104.69 0 HEAP-ARENA [ SIZE-BYTES 0 N-UNUSED-CHUNKS 1 TOP-FREE-BYTES 0 ] HEAP-MAPPED [ SIZE-BYTES 0 N-CHUNKS 0 ] HEAP-USED-BYTES 0 HEAP-UNUSED-BYTES 0
```

What I find weird, though, is that when I try to run the job with `cmsRunGlibC` instead of `cmsRun` to see the memory consumption per module, I get slightly lower numbers:
```
MemoryCheck: event : VSIZE 1928.11 0 RSS 1472.46 0 HEAP-ARENA [ SIZE-BYTES 949719040 N-UNUSED-CHUNKS 11 TOP-FREE-BYTES 2750144 ] HEAP-MAPPED [ SIZE-BYTES 329121792 N-CHUNKS 204 ] HEAP-USED-BYTES 946967024 HEAP-UNUSED-BYTES 2752016
MemoryCheck: event : VSIZE 2374.58 0 RSS 1922.02 0 HEAP-ARENA [ SIZE-BYTES 986439680 N-UNUSED-CHUNKS 138 TOP-FREE-BYTES 287024 ] HEAP-MAPPED [ SIZE-BYTES 760352768 N-CHUNKS 356 ] HEAP-USED-BYTES 985430192 HEAP-UNUSED-BYTES 1009488
```

The memory report at the end indicates that `basicJetsForMet` consumed by far the largest amount of memory:
```
basicJetsForMet: n = 1 avg = 142.586 max = 142.586 run: 1 lumi: 97 event: 164559 early total: 0.015625 max: 0.015625
```
I also get a similar conclusion when running the job in massif:
![Screenshot_20190527_084309](https://user-images.githubusercontent.com/6233872/58397924-ab8c7900-805b-11e9-972c-8c5f61b2ec78.png)

But when I remove all MET sequences in the job, I still see the spike in memory consumption:

```
MemoryCheck: event : VSIZE 1889.34 0 RSS 1438.88 0 HEAP-ARENA [ SIZE-BYTES 915177472 N-UNUSED-CHUNKS 11 TOP-FREE-BYTES 34992 ] HEAP-MAPPED [ SIZE-BYTES 340193280 N-CHUNKS 213 ] HEAP-USED-BYTES 915140608 HEAP-UNUSED-BYTES 36864
MemoryCheck: event : VSIZE 2341.45 0 RSS 1886.55 0 HEAP-ARENA [ SIZE-BYTES 957337600 N-UNUSED-CHUNKS 86 TOP-FREE-BYTES 5093952 ] HEAP-MAPPED [ SIZE-BYTES 771891200 N-CHUNKS 370 ] HEAP-USED-BYTES 951056592 HEAP-UNUSED-BYTES 6281008
```
And massif doesn't provide any insight into the issue (at least for me):
![Screenshot_20190527_084832](https://user-images.githubusercontent.com/6233872/58398070-4a18da00-805c-11e9-94aa-f10b4acdbb08.png)

---
[*] `/store/mc/RunIIFall17MiniAODv2/ttHJetToNonbb_M125_TuneCP5_13TeV_amcatnloFXFX_madspin_pythia8/MINIAODSIM/PU2017_12Apr2018_new_pmx_94X_mc2017_realistic_v14-v1/100000/7C60AC2B-E76F-E811-9D60-0025905B860C.root`
[$] Add the following lines to `cfg.py`:

```python
process.SimpleMemoryCheck = cms.Service("SimpleMemoryCheck",
  ignoreTotal          = cms.untracked.int32(1),
  oncePerEventMode     = cms.untracked.bool(True),
  moduleMemorySummary  = cms.untracked.bool(True),
  showMallocInfo       = cms.untracked.bool(True),
  monitorPssAndPrivate = cms.untracked.bool(True),
)
```

**Comment by peruzzim** [comment]
the indications you collected do not point to a NanoAOD-specific issue, I suggest you report the issue to the upstream cmssw repository, or on the framework HN

**Comment by ktht** [comment]
Agreed. The jump in memory consumption happens with every module or task. It looks like something causes the event processor to re-read the input file or cache something without cleaning up the memory.

**Comment by peruzzim** [comment]
Will be followed up in cms-sw#26954
