### ISSUE TITLE
jetId in 2018

### ISSUE THREAD

**Issue by dseith** [cms-nanoAOD/cmssw#374]
I would like to know which jetid recommendations are used for 2018 NanoAOD v4 and comming v5 samples for AK4Jets.

Judging from the code it seems to me that currently 2017 recommendations are used also for 2018:
https://github.com/cms-nanoAOD/cmssw/blob/7f9a42e23a5737d1c3c51581c867e14ccab89382/PhysicsTools/NanoAOD/python/jets_cff.py#L60-L65

Also the producer has not been updated yet with the current 2018 recommendations:
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/SelectorUtils/interface/PFJetIDSelectionFunctor.h

Could you confirm whether 2017 or 2018 recommendations are used for the jetid in 2018 NanoAOD samples?

The recommendations are currently the same except for jets with 2.4 < eta < 2.7.
https://twiki.cern.ch/twiki/bin/viewauth/CMS/JetID13TeVRun2018
https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVRun2017

**Comment by arizzi** [comment]
I'm not sure I understand.. the cmssw selector is what is recommended in the Twiki you pointed to.
If there is a discrepancy in the value on the twiki table with those implemented by the producer I guess that's something to report to JME

**Comment by dseith** [comment]
yes thats basically the point. The values in the tables seem to differ from what is implemented in the producer. I will check with jme. 
I was just wondering if you maybe use something else in addition to this producer in NanoAOD production which I missed while checking the code. But it seems not. 
Thanks!
