### ISSUE TITLE
Generator Filter Efficiencies in NanoAOD

### ISSUE THREAD

**Issue by mzarucki** [cms-nanoAOD/cmssw#376]
Dear NanoAOD experts,

I am currently using the nanoAOD framework for our analysis, which interprets in signal models that contain genHT and genMET generator filters. To get the correct weights, we need to know the corresponding filter efficiencies. Previously we calculated these separately using information from the GenFilterInfo header in miniAOD, which does not seem to be stored in nanoAOD.

Therefore, I was wondering if you are aware whether there exists some nanoAOD module that handles this information, so that the correct weights can be used in the flat tuples. For example, it would be nice to store the generator filter efficiency as a nanoAOD branch.

Best regards,
Mateusz

**Comment by peruzzim** [comment]
I don't think we have such a module, if it is based on MiniAOD information you are welcome to contribute it.

**Comment by mariadalfonso** [comment]
this is being done in https://github.com/cms-sw/cmssw/pull/34169
I close this issue and we follow on the PR
