### ISSUE TITLE
DeepTauID for master and UL (106X)

### ISSUE THREAD

**Issue by mbluj** [cms-nanoAOD/cmssw#377]
DeepTauID - tauID based on DNN - has just been added to MiniAOD sequences in both master and UL (106X) branches of official CMSW (cms-sw#26796, cms-sw#27146). Therefore, we (tau POG) would like to store these novel tauID also in NanoAOD (w/o rerunnig the algorithm) aiming for NanoAOD v1 of UL production. Is it still feasible that update via nanoAOD repository goes to UL release? If so, is master-cmsswmaster branch proper one to use for this? If it is not feasible, can we go directly to CMSSW? 
Regardless, the update will contain:
a) addition of 3 new float numbers and 3 new int numbers for DeepTauID;
b) removal of outdated tauIDs: 2 floats and 2 ints (at least).

The changes are not going to be fully backward compatible in the sense that it will not be possible to run such NanoAOD with old 94X/102X MiniAOD as there is not special era for 94X/102X productions which would allow to exclude from reading (non-existing) DeepTauID, but running should be possible for 92X and 80X whose have special eras.

Please let us know if this is acceptable plan or if you have different your proposal.

**Comment by peruzzim** [comment]
Done in cms-sw#27226, cms-sw#27227, exceptionally to allow for a very fast turnaround for UL preparation. Will come to this repository as soon as there is a new version of CMSSW_10_6_X to merge here.
