### ISSUE TITLE
miniaod -> nanoaod bjet Discriminator

### ISSUE THREAD

**Issue by py-craft** [cms-nanoAOD/cmssw#383]
Hello everyone, I am moving from miniaod to nanoaod, and I have some doubts about bjet Discriminators. I used 3 bjet discriminators in my Analyze.
1. "pfDeepCSVJetTags:probb"
2. "pfDeepCSVJetTags:probbb"
3. "pfCombinedInclusiveSecondaryVertexV2BJetTags"

The third one i have found which is the relevant, it is Jet_btagCSVV2.
But first two i am not sure, what are they.

Thanks in advance!
Vardan Aloyan

**Comment by NJManganelli** [comment]
The first and second of these are combined into one discriminant for overall b-tagging of a jet (i.e., not available separately): 
Jet_btagDeepB | Float_t | DeepCSV b+bb tag discriminator

Though you didn't ask, the b-tagging algo DeepJet (formerly known as DeepFlavour) is a combination of all 3 discriminants: b + bb + lepb
Jet_btagDeepFlavB | Float_t | DeepFlavour b+bb+lepb tag discriminator

Cheers,
Nick Manganelli
