### ISSUE TITLE
Storage of GenLumiInfoHeader configDescription

### ISSUE THREAD

**Issue by kpedro88** [cms-nanoAOD/cmssw#385]
Currently, a combination of PAG MC conveners, PPD, and DMWM are pursuing a new strategy for production of large signal scan samples. It uses the "RandomizedParameters" method, invented for and already used by SUSY, to vary the model parameters randomly, generating events for many signal models in a single request.

In order to identify the exact model for any given event, a string is stored in `GenLumiInfoHeader`, accessible via `configDescription()`: https://github.com/cms-sw/cmssw/blob/1f01a45fa4ba4f6003c9f95c9ae11e7e3aa93f4b/SimDataFormats/GeneratorProducts/interface/GenLumiInfoHeader.h#L19

The goal is to use this method for ~all signals in UL. It would be great if nanoAOD supported this in advance, so the associated nanoAOD production for these signal samples is immediately useful.

**Comment by peruzzim** [comment]
I have a prototype implementation of this and will do a PR soon.
Is this string empty when the dataset is not one of those produced with the RandomizedParameters method (in particular on fastsim samples)?
I need a way to detect when to split the weight sums based on this string, and the handles I can think of are: 1) whether the sample is processed with the `--fast` cmsDriver option 2) the string itself

**Comment by kpedro88** [comment]
As far as I know, the configDescription string is only used for RandomizedParameters MC samples. (`setConfigDescription()` is only called here: https://github.com/cms-sw/cmssw/blob/156d29f7e8e2d333783ec6dc0415dc97352d4d02/GeneratorInterface/Core/src/BaseHadronizer.cc#L46.)

Please note that RandomizedParameters can be and has been used with any detector simulation (fast or full).

**Comment by peruzzim** [comment]
addressed in #398
