### ISSUE TITLE
Saving LHE weights in nanoAOD when using randomised parameter scans

### ISSUE THREAD

**Issue by scodella** [cms-nanoAOD/cmssw#389]
Hi,

there is an increasing interest in CMS in using randomised parameter scans for production of BSM model signal events [1]. This has been used in SUSY since long time. The randomised parameter fragment is not using the ExternalLHEProducer, so lhe weights are stored (with different structure) in a GenEventInfoProduct collection rather than a LHEEventProduct collection, and this breaks the storing of lhe weights in nanoaod [2]. I prepare a simple work around to start a discussion (people with more knowledge of the GenEventInfoProduct collection  might give advice on how to improve it). Just  checking the presence of lhe weights in GenEventInfoProduct if no LHEEventProduct is present [3], and eventually calling a dedicated fillLHEWeightTables function to fill the tables [4]. Here, PDF and scale tables can be filled like in here [5], but these lines depend on the details of the generator (MG5 2.6.0 for instance produces much more scale weight entries than 2.4.2), and should be modified accessing to lhe header information that I can not find in  GenEventInfoProduct (my ignorance, or isn't there?). Otherwise, lhe weights might be generically saved like in [6].

that's all, please let me know your opinion on how to procede.

best,
Luca

[1] https://indico.cern.ch/event/837619/contributions/3514503/attachments/1889261/3115360/slides.pdf
[2] https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc#L247-L263
[3] https://github.com/scodella/cmssw/blob/master/PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc#L208-L211
[4] https://github.com/scodella/cmssw/blob/master/PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc#L297-L352
[5] https://github.com/scodella/cmssw/blob/master/PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc#L312-L318
[6] https://github.com/scodella/cmssw/blob/master/PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc#L339-L343

**Comment by peruzzim** [comment]
Please see #398 storing the description string (i.e. the model) from GenLumiInfoHeader.
Could we use that reliably (i.e. non-empty `GenLumiInfoHeader::configDescription()`)  to detect whether a sample is using the randomized parameter scan feature?

**Comment by scodella** [comment]
I made a quick comparison between a file from randomized parameter scan dataset [1] and one from a lhe producer based dataset [2], and seems that indeed the  GenLumiInfoHeader::configDescription() can discriminate the two cases. Could be used instead of [3]. 

It seems also that GenLumiInfoHeader::weightNames() might contains the information on the event weight names used for the randomized parameter scan case (replacing the information in LHEEventProduct::weigths_()::id only available when using lhe producer)

[1] /eos/cms/store/mc/RunIISummer16MiniAODv3/SMS-T2tt_3J_xqcut-20_top-corridor_2Lfilter_TuneCUETP8M2T4_13TeV-madgraphMLM-pythia8/MINIAODSIM/PUMoriond17_pdfweight_94X_mcRun2_asymptotic_v3-v1/260000/A26E3F41-77C5-E911-8BE4-FA163E74B82A.root
[2] /eos/cms/store/mc/RunIISummer16MiniAODv3/SMS-T2tt_3J_xqcut-20_mStop-175_mLSP-1_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/MINIAODSIM/PUMoriond17_pdfweight_94X_mcRun2_asymptotic_v3-v1/260000/38D13DDB-13C5-E911-979F-FA163EA05F24.root
[3] https://github.com/scodella/cmssw/blob/master/PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc#L208

**Comment by peruzzim** [comment]
A first, untested skeleton of a possible implementation is here: https://github.com/cms-nanoAOD/cmssw/compare/master-102X...peruzzim:dev_LHEweightsFromGenInfo_102X
but we should investigate whether `GenLumiInfoHeader::lheHeaders()` also contains useful information, and whether this format is general enough to work for all samples.

let's also get @kdlong @agrohsje @qliphy in the loop here

**Comment by scodella** [comment]
Hi,

I tested the new code on [1] but I get the following exception:
  Called CounterMap::get() before setting the active label
It seems that in setLabel the active_el varibles is not well set. The label passed in the faction is "T2tt-3J_175_10". Do you see what is wrong?




[1] /store/mc/RunIISummer16MiniAODv3/SMS-T2tt_3J_xqcut-20_top-corridor_2Lfilter_TuneCUETP8M2T4_13TeV-madgraphMLM-pythia8/MINIAODSIM/PUMoriond17_pdfweight_94X_mcRun2_asymptotic_v3-v1/130000/322458C0-40D8-E911-B65E-FA163E226E3A.root

**Comment by peruzzim** [comment]
Yes, a mistake in accessing the new data structure, should be fixed now. Could you please test it in more details? I think there are still things to be fixed e.g. in branch titles...

**Comment by scodella** [comment]
I had to change "counterMap->setLabel(label);" for "counterMap.setLabel(label);"
After that, the label passed in the function changes to "T2tt_3J_175_10", but then I get the same exception

**Comment by scodella** [comment]
thanks, now it runs fine. I have the scale weights in the output file when running over [1]. PDF weights are empty, but that must be because of the choice of the pdf set to store. I will do some more extensive test.

[1]  /store/mc/RunIISummer16MiniAODv3/SMS-T2tt_3J_xqcut-20_top-corridor_2Lfilter_TuneCUETP8M2T4_13TeV-madgraphMLM-pythia8/MINIAODSIM/PUMoriond17_pdfweight_94X_mcRun2_asymptotic_v3-v1/130000/322458C0-40D8-E911-B65E-FA163E226E3A.root

**Comment by scodella** [comment]
ok, I can fill PDF weights by changing scalew to pdfw in:
https://github.com/peruzzim/cmssw/blob/920412ca544dd0b0c72bc9c5e3745a4858bc0306/PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc#L685

I will test what we are actually saving, want to be sure the choice we make is flexible enough for all the datasets.

**Comment by scodella** [comment]
So after studying a bit the PDF weights that are  stored, it seems that they correspond to the first PDF set available in the input file out of the list (taken in inverse order) defined in
https://github.com/peruzzim/cmssw/blob/920412ca544dd0b0c72bc9c5e3745a4858bc0306/PhysicsTools/NanoAOD/python/nano_cff.py#L100-L105
so for example for the file I am testing, this will be "NNPDF30_nlo_nf_5_pdfas". If I comment the corresponding line (L105) the PDF set used will be "NNPDF30_lo_as_0130" (since info for "NNPDF30_nlo_nf_4_pdfas" are not available in the input file). Ideally, we would like to pick up (at least) the PDF set used for the default event generation. Would be nice to have this info available in the GenLumiInfoHeader.

**Comment by kdlong** [comment]
Wouldn't it be cleaner and easier to access the weight names from genLumiInfoHead->weightNames()? This is what is done for the PS weights in Rivet: https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/RivetInterface/plugins/RivetAnalyzer.cc#L102-L105

I checked for this file, and the weight info is stored, basically you could use the same regex without the xml tags. If you want to take a quick look: https://gist.github.com/kdlong/fa6c5b96c7d54044845535b5200a8542

**Comment by kdlong** [comment]
Oh I see this comment was already made by @scodella... is there an issue?

**Comment by kdlong** [comment]
@scodella do you know of a SUS request that uses the parameter scan setup and also includes PS weights? I'm interested in how the GenLumiInfoHeader::weightNames() behaves in this case.

**Comment by peruzzim** [comment]
Ok, this is progressing more actively than I expected. I had intended this code just as an example to show how to treat these weights.
Would you will to take my commits, add the needed fixes on top in a branch of yours, and prepare a pull request?

**Comment by scodella** [comment]
> @scodella do you know of a SUS request that uses the parameter scan setup and also includes PS weights? I'm interested in how the GenLumiInfoHeader::weightNames() behaves in this case.

@kdlong see for instance this dataset:
/SMS-TChiWZ_ZToLL_mZMin-0p1_mC1-325to1000_TuneCP2_13TeV-madgraphMLM-pythia8/RunIIAutumn18MiniAOD-GridpackScan_102X_upgrade2018_realistic_v15-v1/MINIAODSIM

**Comment by scodella** [comment]
I uploaded my version of the code in https://github.com/cms-nanoAOD/cmssw/compare/master-102X...scodella:dev_LHEweightsFromGenInfo_102X
With respect to Marco's code, a part of few fixes, I added the PS weights [1], mimicking what is done in the code working for LHEproducer (who needs anyway a fix [2]), and inverted the loops on the preffered PDF sets and the GenInfo PDF sets [3], so that we store the PDF weights for the variations of the first PDF set found in the GenInfo and not the last PDF set specified in nano_cff. I also added the NNPDF31_lo_as_0130 to the preferred PDF sets [4] as this is largely used in SUSY signal samples. 

[1] https://github.com/scodella/cmssw/blob/dev_LHEweightsFromGenInfo_102X/PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc#L367-L375
[2] https://github.com/cms-nanoAOD/cmssw/issues/381 
[3] https://github.com/scodella/cmssw/blob/dev_LHEweightsFromGenInfo_102X/PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc#L736-L744
[4] https://github.com/scodella/cmssw/blob/dev_LHEweightsFromGenInfo_102X/PhysicsTools/NanoAOD/python/nano_cff.py#L106

**Comment by scodella** [comment]
I just submitted a PR:
https://github.com/cms-nanoAOD/cmssw/pull/441

**Comment by vlimant** [comment]
please ping/re-open in cms-sw if needed
