### ISSUE TITLE
Mass in gen partilces needed for SUSY particles for m <= 10 GeV

### ISSUE THREAD

**Issue by GonzalezFJR** [cms-nanoAOD/cmssw#409]
The mass of gen SUSY particles is needed also for m <= 10 GeV. In particular, I cannot distinguish between neutralinos with m = 1 GeV and m = 10 GeV in my SUSY T2tt scan.

https://github.com/cms-nanoAOD/cmssw/blob/9e97a8fb55d9fc3f0d168b36e375f9e7d342fcb4/PhysicsTools/NanoAOD/python/genparticles_cff.py#L44

**Comment by gpetruc** [comment]
Could you make a PR to save the mass also for BSM particles (should be `abs(pdgId) > 1000000`, I think, but please check...)

**Comment by peruzzim** [comment]
Yes that's the way to go, please do this PR on top of the master-cmsswmaster branch. Thanks!

**Comment by peruzzim** [comment]
fixed in #415
