### ISSUE TITLE
muon scale corrections

### ISSUE THREAD

**Issue by gpetruc** [cms-nanoAOD/cmssw#41]
should we apply them? (saving also the factor to go back, as for muons)
which ones?

@drkovalskyi  @folguera

**Comment by drkovalskyi** [comment]
Most physics analyses won't benefit the muon scale corrections. I don't think we should apply them by default, but it can be useful to provide them as a correction factor that anyone can add. Can we store it as one more float per muon?

**Comment by arizzi** [comment]
are the correction computed only vs pt/eta/phi or they are function of inputs not available in nano?

**Comment by folguera** [comment]
they are computed as a function of pt/eta/phi:  https://twiki.cern.ch/twiki/bin/view/CMS/MuonReferenceScaleResolRun2

**Comment by drkovalskyi** [comment]
Not all the inputs are available in NanoAOD. For example one needs trackerLayersWithMeasurement. Gen pt can also be useful (not sure if you have it). Overall it's a quite special correction that is not always available quickly enough for a typical production cycle.

**Comment by arizzi** [comment]
ok, then we store it (and it should be cheap enough)

**Comment by drkovalskyi** [comment]
In principle we need to store two numbers: correction and uncertainty and the uncertainty requires ~100 of iterations checking different variations and propagating them. It will require some code development and getting parameters for new data. The latest one that we have is for Run2016. So it's something that we may want to have ready for legacy re-miniaod with 94X release.

**Comment by arizzi** [comment]
can you guys implement this at least for 80X-2016 sample via Era switches?
Do I understand correctly that one of the two calibration (Bachtis,Rolandi,Manca) doesn't require trackerLayersWithMeasurement hence can be computed on top on nanoaod?

**Comment by arizzi** [comment]
anyhow trackLayersWithMeasurement is probably the only thing that is missing...so perhaps we can just store that (it is cheaper probably than the correction itself) and compute the correction from miniaod.

**Comment by drkovalskyi** [comment]
Both corrections are optional, i.e. not required by Muon POG and very few analyses need them. I can add it to my todo list, but realistically don't expect it to get to the top of my list anytime soon.

In general I think it would help to have some specific time lines for NanoAOD "releases". I don't see much use for it till we have MiniAOD v2. With proper planning it can be easier to find time to get things implemented and tested.

**Comment by arizzi** [comment]
I added the nTrackerLayers so we can at least run the calib in the tools (we can easily import there the existing code)

Concerning longer term it is probably best if muon pog integrates the code in the cmssw release and then we can have different payloads to be picked up when available

**Comment by vlimant** [comment]
ping / reopen if needed
