### ISSUE TITLE
Secondary vertices: store additional variables and relax preselection

### ISSUE THREAD

**Issue by gouskos** [cms-nanoAOD/cmssw#411]
Store two additional variables: dxy and dxySignificance 
relax preselection on d3Dsig from 3 sigma to 1 sigma

These are necessary for soft b-tagging algorithm used in many susy and Higgs analyses, but also for the calibration of some of the DeepAK8 score.

I will make a PR now with the changes.

**Comment by peruzzim** [comment]
additional variables implemented in #412, looser preselection is rather for a dedicated calibration workflow
