### ISSUE TITLE
ImportError: No module named MuonFSRProducer_cfi

### ISSUE THREAD

**Issue by andreypz** [cms-nanoAOD/cmssw#427]
Hello,

I'd like to contibute to NanoAOD, so I set-up a fresh release, with following:
```
cmsrel CMSSW_10_2_16_UL
cd CMSSW_10_2_16_UL/src/
git cms-init
git cms-merge-topic cms-nanoAOD:master-102X
git checkout -b nanoAOD cms-nanoAOD/master-102X
cmsenv
scram b -j8
cd PhysicsTools/NanoAOD/
```

Then I run cmsdriver command:
```
cmsDriver.py myNanoProd_Creg2017 -s NANO --mc --eventcontent NANOAODSIM --datatier NANOAODSIM  --no_exec  --conditions 102X_mc2017_realistic_v7 --era Run2_2017,run2_nanoAOD_94XMiniAODv2 --customise_commands="process.add_(cms.Service('InitRootHandlers', EnableIMT = cms.untracked.bool(False)))"
```
but it gives me an error:

>  File "CMSSW_10_2_16_UL/python/PhysicsTools/NanoAOD/muons_cff.py", line 95, in <module>
>     from MuonAnalysis.MuonAssociators.MuonFSRProducer_cfi import MuonFSRProducer
> ImportError: No module named MuonFSRProducer_cfi

What am I missing?

**Comment by arizzi** [comment]
this was due to a request from RECO conveners to put a lower case "M" in the MuonFSRProducer and MuonFSRAssociator

I guess marco will fix this side effect today, but if you want to quickly continue just change the capital M in lower case m

**Comment by andreypz** [comment]
Ok, I see... But just changing the name does not work.
In fact, this FSR .cfi file does not exist here: 
https://github.com/cms-sw/cmssw/tree/master/MuonAnalysis/MuonAssociators/python
Perhaps I need to merge some other topic for this?

**Comment by arizzi** [comment]
the cfi file is autogenerated in your crab area under cfipython (one level below the root /src )

the lowercase "m" is both for the cfi name and the module name

**Comment by arizzi** [comment]
see here for the fix https://github.com/cms-sw/cmssw/pull/28122/commits/34f6c30520fdef723945d7fbe8bb635c1b703506

**Comment by andreypz** [comment]
Hmm... Still does not work...
I don't see the file under cfipython either.
Here is all I have there:
```
CMSSW_10_2_16_UL/src$ ls ../cfipython/slc7_amd64_gcc700/PhysicsTools/NanoAOD/
BJetEnergyRegressionMVA_cfi.py        ElectronJetVarProducer_cfi.pyc       MuonJetVarProducer_cfi.py             genJetFlavourTable_cfi.pyc
BJetEnergyRegressionMVA_cfi.pyc       EnergyRingsTable_cfi.py              MuonJetVarProducer_cfi.pyc            genWeightsTable_cfi.py
BTagWeightTable_cfi.py                EnergyRingsTable_cfi.pyc             PhoIsoValueMapProducer_cfi.py         genWeightsTable_cfi.pyc
BTagWeightTable_cfi.pyc               IsoTrackIsoValueMapProducer_cfi.py   PhoIsoValueMapProducer_cfi.pyc        isFromLostTrackMapProducer_cfi.py
EleIsoValueMapProducer_cfi.py         IsoTrackIsoValueMapProducer_cfi.pyc  PhoVIDNestedWPBitmapProducer_cfi.py   isFromLostTrackMapProducer_cfi.pyc
EleIsoValueMapProducer_cfi.pyc        JetRegressionVarProducer_cfi.py      PhoVIDNestedWPBitmapProducer_cfi.pyc  lheInfoTable_cfi.py
EleVIDNestedWPBitmapProducer_cfi.py   JetRegressionVarProducer_cfi.pyc     PhotonEnergyVarProducer_cfi.py        lheInfoTable_cfi.pyc
EleVIDNestedWPBitmapProducer_cfi.pyc  L1TriggerResultsConverter_cfi.py     PhotonEnergyVarProducer_cfi.pyc       muonIDTable_cfi.py
ElectronEnergyVarProducer_cfi.py      L1TriggerResultsConverter_cfi.pyc    candMcMatchTable_cfi.py               muonIDTable_cfi.pyc
ElectronEnergyVarProducer_cfi.pyc     MuonIsoValueMapProducer_cfi.py       candMcMatchTable_cfi.pyc              puTable_cfi.py
ElectronJetVarProducer_cfi.py         MuonIsoValueMapProducer_cfi.pyc      genJetFlavourTable_cfi.py             puTable_cfi.pyc
```
I tried to re-run `scram b` after changing the 'm' letter - such file still does not appear.

**Comment by arizzi** [comment]
it should be under  MuonAnalysis.MuonAssociators not under PhysicsTools/NanoAOD

At this point I suspect you have a coherent capital "M"  setup but for some reason the sparse-checkout of git does not include MuonAnalysis/MuonAssociators 

so edit .git/info/sparse-checkout and add MuonAnalysis/MuonAssociators 
then git checkout -- MuonAnalysis

(then perhaps you need to rever to uppercase M)

**Comment by andreypz** [comment]
Indeed, the ` MuonAnalysis.MuonAssociators ` was not checked out.
However, editing `sparse-checkout`  file and doing  `git checkout -- MuonAnalysis` did not work.
Instead, I checked out the package with `git cms-addpkg MuonAnalysis/MuonAssociators`. That worked, and it compiled. However, after compilation there is no cfi file... In fact, the directory `cfipython/slc7_amd64_gcc700/MuonAnalysis/MuonAssociators/` is empty.
So the cmsDriver command crashes either with "m" or "M".

**Comment by peruzzim** [comment]
please follow the temporary instructions here
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookNanoAOD#Recipe_for_the_current_HEAD_of_N

there are a couple of merge-topic needed

**Comment by arizzi** [comment]
can you verify that under "plugins" the MuonFSRAssociator and producer exists?  I guess not... ok just seen Marco post .. so take his full recipe :-)

**Comment by andreypz** [comment]
Ok, with additional merge-topics this works.
However, it says on the twiki not to commit to nanoAOD repo with these. But that's exactly what I want to do. So, should I do that anyway, or should I wait till everything is merged (how long)?

**Comment by peruzzim** [comment]
It means that, if you open a PR to this repository for a new feature, you should please rebase it on the current masteer of this repo, without including the commits added by the merge-topic in it.

I close this issue as it's fixed.
