### ISSUE TITLE
FatJet - GenJetAK8 matching

### ISSUE THREAD

**Issue by bartokm** [cms-nanoAOD/cmssw#428]
There is no variable for matched GenJetAK8 in FatJet, similarly like Jet_genJetIdx in AK4 jets.
This information would be needed if one would like to calculate b-tagging SFs for AK8 jets.
Alternatively a FatJet_hadronFlavour variable could be added, which is actually needed for the SFs.

**Comment by peruzzim** [comment]
done in #456
