### ISSUE TITLE
Update b-jet energy regression with latest weights

### ISSUE THREAD

**Issue by andreypz** [cms-nanoAOD/cmssw#432]
The energy regression in NanoAOD is not up-to-date.
It should be updated with the latest weights, described here:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/HiggsWG/BJetRegression#Reccomendation_for_13_Main_TeV_d
Hopefully, this should be done before next Nano production campaign.
I'm going to work on the PR for this.

**Comment by arizzi** [comment]
I'm afraid NanoV6 train already left...request for update was sent out in June ...

**Comment by andreypz** [comment]
Ok, well, then we'll wait for the next train...

**Comment by capalmer85** [comment]
Has V6 production started?

**Comment by arizzi** [comment]
I let @peruzzim comment for the details, but currently even the nano productions are undergoing full validations as standard campaigns (this will be reviewed in the future). So AFAIK nanoV6 is about to be launched after full validation is finished.

**Comment by peruzzim** [comment]
#433
