### ISSUE TITLE
Implement trigger object matching for HLT_Ele*_CaloIdVT_GsfTrkIdT* paths

### ISSUE THREAD

**Issue by sethcooper** [cms-nanoAOD/cmssw#434]
No trigger object matching is currently available for electron CaloIdVT_GsfTrkIdT paths.  To fix this, a quality bit like the following should be added to the electron trigger objects:
`"2048*filter('hltEle*CaloIdVTGsfTrkIdTGsfDphiFilter')"`

**Comment by sethcooper** [comment]
Hi,

I see that the selections80X at least for electrons have significantly fewer qualityBits than the nominal selection qualityBits. Can these not be kept in sync with the nominal selection qualityBits, or is it just a matter of validating all the filter names with the 2016 HLT?  It seems like it would be good to keep the same bit definitions throughout eras if possible, in which case I can't simply add the new bit on top of the existing selections80X qualityBits. I note that there is a FIXME in the relevant part of the cff.

**Comment by peruzzim** [comment]
If you have expertise on this topic, it would be extremely valuable to have a look at all years and try to uniformize the bits. Maybe it will not be possible to do it fully, but maybe we can improve over the current situation, trying to change minimally the current setup for 2017/2018. The differences you see are indeed due to the fact that the path names are different in different menus.
Would you have a chance to follow up on this? Thank you

**Comment by sethcooper** [comment]
Hi @peruzzim ,

I wouldn't say I'm an "expert" but in any case, it depends on how much detail is required in the checks.  I'm considering the electron quality bits only here.  I had a bit of time to look at a single HLT menu from 2016.

The first 3 quality bits in fact use the same regex's for 2016 and 2017/2018.  For the 4th quality bit, the regex's are slightly different between 2016 and 2017-2018. The 2016 version matches the two filters in the 2016 menu which have "SingleIsoEle" in their names in addition to those matched by the 2017/2018 version. Thus one could consider using the more inclusive 2016 version (one additional asterisk) for all years.

So all the 2017/2018 regex's except for the last Ele32 one (which I understand is 2017/2018 specific) match at least _some_ filters in the 2016 menu. Perhaps this is a good enough check.

I'd still like to add the regex that was the point of this issue (which should work in 2016, 2017, and 2018).


Cheers,
Seth

**Comment by peruzzim** [comment]
@sethcooper @IzaakWN I notice - only now, preparing backports - that #455 later modified the filter from `hltEle*CaloIdVTGsfTrkIdTGsfDphiFilter` to `hltEle*CaloIdVTGsfTrkIdTGsf*Filter`

can you confirm this is ok?

**Comment by IzaakWN** [comment]
It should be OK, as far as I can tell by [checking trigger filter patterns](https://github.com/IzaakWN/TriggerChecks/blob/4de3f8c83499a09621f4a3e72a1bc72a82de791c/output/triggers_SingleElectron.log#L733-L794), the only matches for the last wildcard in `hltEle*CaloIdVTGsfTrkIdTGsf*Filter` are `Dphi` or `Deta`. Our targeted single electron trigger always have both, and the last filter always has `Dphi`. So this last wildcard is actually redundant...

**Comment by sethcooper** [comment]
@IzaakWN How does one know that the matched objects passed the `Dphi` filter (the last filter as you mentioned) and not only the `Deta` filter?

**Comment by IzaakWN** [comment]
Sorry, maybe I misunderstand your question, and I am also no trigger expert by any means, but as far as I can tell from the checks in the trigger menu, a trigger object of e.g. `HLT_Ele115_CaloIdVT_GsfTrkIdT` always passes both `hltEle115CaloIdVTGsfTrkIdTGsfDetaFilter` _and_ `hltEle115CaloIdVTGsfTrkIdTGsfDphiFilter`.

Even still, if an object would pass only one of the two–which shouldn't happen, the wildcard would catch both cases. Does that answer your question, or am I misunderstanding you?

**Comment by sethcooper** [comment]
Thanks.  I probably just missed it in the menu, but I'm just not seeing why the trigger object should always pass both `Deta` and `Dphi` filters.

**Comment by IzaakWN** [comment]
The way I check the filters in the Run-II trigger menus was with [this script](https://github.com/IzaakWN/TriggerChecks#list-filters), and it finds all the available module (filters and producers) with [this line](https://github.com/IzaakWN/TriggerChecks/blob/ff6ca4d81f0417e99a51add261e2454585824232/plugins/CheckTriggers.cc#L134).
With this script, I have printed out all triggers in Run-II data and MC that have modules satisfying the `hltEle*CaloIdVTGsfTrkIdTGsf*Filter` pattern. The print out is [here](https://github.com/IzaakWN/TriggerChecks/blob/ff6ca4d81f0417e99a51add261e2454585824232/output/filters_hltEle-CaloIdVTGsfTrkIdTGsf-Filter.log#L627-L684), and you can see that the two above-mentioned filters always appear together in the list of filter for a given trigger, meaning each object belonging to this trigger should have pass both of them.

**Comment by sethcooper** [comment]
Maybe I'm still missing something.  Here's an example that hopefully better illustrates my point:
1. An object `o1` passes the `dEta` filter. Because `saveTags = True`, it is saved in the event, and then during Nano production the wildcard pattern matches it and it gets stored in NanoAOD.
2. The same object `o1` then fails the `dPhi` (last) filter.
3. A second object `o2` passes both `dEta` and `dPhi` filters.  This object `o2` also passes the wildcard filter and is saved in the NanoAOD. Object `o2`, of course, is the one that caused the trigger to fire.

When looking at the NanoAOD, I want to see the trigger objects which caused the trigger to fire.  So I select events for which the trigger passed, and examine the trigger objects which match this wildcard pattern.  In this case I will see both `o1` and `o2` matching the wildcard pattern. This would lead me to conclude that both `o1` and `o2` passed all the filters, while only `o2` did.  I would expect to see only `o2` as a matching trigger object.

**Comment by IzaakWN** [comment]
Finally see what you mean... Apologies.

My implicit assumption was that object `o1` in your example trigger was not saved in miniAOD, or that those flags are not saved. Can every (electron) trigger object, even those corresponding to other triggers than we are targeting here, have these filters saved in their list if they pass it, even if it's part of a dead end? If so, we should replace the wildcard back to `Dphi`, in order to make sure it only includes objects like `o2` in your examples.

@peruzzim, can you remove the wildcard yourself to be on the safe side?

**Comment by sethcooper** [comment]
OK, glad we're on the same page.

As far as I know, `saveTags = True` means that the trigger objects passing that filter will be saved in the event. I think I looked at some other regex's before to see that they were matching last filters only, but that could be checked again.

**Comment by IzaakWN** [comment]
I don't know about `saveTags`, but from the code it does looks like the filter matching looks at any filter that is saved in the filter list of a trigger object, not just the last one: The pattern matching we are using for the nanoAOD filter bits uses [`TriggerObjectStandAlone::filter`](https://github.com/cms-sw/cmssw/blob/master/DataFormats/PatCandidates/interface/TriggerObjectStandAlone.h#L175), which can be traced back to [`TriggerObjectStandAlone::hasFilterOrCondition`](https://github.com/cms-sw/cmssw/blob/638845f76e2d305c383b757fd44b59502eda9f04/DataFormats/PatCandidates/src/TriggerObjectStandAlone.cc#L182-L191). You can see that it loops over all filters in the trigger object's filter list.

**Comment by peruzzim** [comment]
please cross-check that https://github.com/cms-nanoAOD/cmssw/pull/478/commits/d4547df66329465c8b033751c104b1896dae63a0 does what you have agreed to be the right thing

**Comment by IzaakWN** [comment]
Yes, that looks to be correct. Thanks for the fix!
