### ISSUE TITLE
New b-tagging SFs available

### ISSUE THREAD

**Issue by ktht** [cms-nanoAOD/cmssw#437]
DeepCSV is old & DeepFlavor is available:
https://github.com/cms-nanoAOD/cmssw/blob/2d621cab1f8493a580a5cd4744530e075afe3c82/PhysicsTools/NanoAOD/python/nano_cff.py#L73-L76
Plus, there are SFs for all three eras now.

**Comment by arizzi** [comment]
btw it is also outdated for 2018, creating SF of average value ~1.08 that are completely different wrt the actual values

**Comment by peruzzim** [comment]
@ktht could you please take care of updating them and opening a PR?

**Comment by ktht** [comment]
Sorry, forgot about this thread. I can update them, however, it seems that there are separate b-tagging SFs available for 2016 TuneCP5 samples ([link](https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation2016Legacy)). The tune information should be accessible from the input files, but I'm not sure if it's worth the effort as it would also imply drastic changes in `BTagSFProducer` in order to support multiple SFs per one era -- unless we just make certain assumptions about the CSV file names (for instance assume TuneCP5 in the CSV file name when running on the TuneCP5 sample).

**Comment by mariadalfonso** [comment]
closing this, 
The BTV SF will be distributed via json and read with correction lib
