### ISSUE TITLE
follow up non-deterministic beaviour

### ISSUE THREAD

**Issue by gpetruc** [cms-nanoAOD/cmssw#44]
~for e/gamma: https://github.com/cms-sw/cmssw/pull/20878~

there's also something in trigger objects and isolated tracks that appear to change slightly event by event, according to the [dqm comparison](http://nanoaod.cern.ch:8060/dqm/dev/start?runnr=1;dataset=/RelVal_MC_TTbar/CMSSW_9_4_0_pre2-test_pr_34/DQM;sampletype=offline_relval;filter=alarms;workspace=Everything;root=Physics/NanoAODDQM;referenceshow=all;referencenorm=False)

**Comment by gpetruc** [comment]
e/gamma is ok, but iso track and trig obj are still non-deterministic

**Comment by arizzi** [comment]
in #21  a similar effect is seen  for GenJet extension table

**Comment by arizzi** [comment]
can we close now?

**Comment by gpetruc** [comment]
let me check the dqm of the test of #63. if that shows no unexpected
changes, then yes.

**Comment by arizzi** [comment]
is the "ref" in dqm updated when we rerun master?

**Comment by gpetruc** [comment]
yes
