### ISSUE TITLE
Store x1 and x2, plus add the mass for high mass gen particles

### ISSUE THREAD

**Issue by arizzi** [cms-nanoAOD/cmssw#45]
as @azzurip suggested we should store Energy rather than Mass for GenPart so that incoming partons x1, x2 can be computed

**Comment by gpetruc** [comment]
i'd rather store x1 and x2 separately.

for most of the other particles, the mass is both more practical and better
compressed.

Giovanni

Il 11 Ott 2017 09:17, "arizzi" <notifications@github.com> ha scritto:

**Comment by arizzi** [comment]
another option is to store pz or energy only for particles with eta > 1000
"?abs(eta)>1000?E():0"

**Comment by arizzi** [comment]
@azzurrip

**Comment by azzurrip** [comment]
Ok the pz of partons at very large eta seems fine to me

**Comment by arizzi** [comment]
@gpetruc do you have a definition of x1 and x2 that is good for all generators? Othwise I'd go for eta >1000 and store pz of all of them

**Comment by arizzi** [comment]
I mean: are we sure that x1 and x2 can be taken from first two genparts?

**Comment by gpetruc** [comment]
the x1 and x2 are in the generator block

Il 11 Ott 2017 12:34, "arizzi" <notifications@github.com> ha scritto:

**Comment by azzurrip** [comment]
Would also be nice to have the incoming parton ids of the hard process.


On 11 Oct 2017, at 13:00, Giovanni Petrucciani <notifications@github.com<mailto:notifications@github.com>> wrote:

the x1 and x2 are in the generator block

Il 11 Ott 2017 12:34, "arizzi" <notifications@github.com<mailto:notifications@github.com>> ha scritto:

**Comment by gpetruc** [comment]
https://github.com/cms-sw/cmssw/blob/master/SimDataFormats/GeneratorProducts/interface/GenEventInfoProduct.h
--->
https://github.com/cms-sw/cmssw/blob/master/SimDataFormats/GeneratorProducts/interface/PdfInfo.h

**Comment by arizzi** [comment]
- mass for all => 48byte/ev 
- mass for m > 1 GeV => 27 byte ev
- m >10 or (pdgId=22 && m>1) => 17byt/ev

**Comment by arizzi** [comment]
what is the difference between "x" and "xPDF" and which one do we want to store?

**Comment by arizzi** [comment]
@perrozzi @bendavid can some of you clarify the difference between x and xPDF ?

**Comment by arizzi** [comment]
#54
