### ISSUE TITLE
Add storage of supercluster energy to electrons

### ISSUE THREAD

**Issue by sethcooper** [cms-nanoAOD/cmssw#457]
The unregressed (and uncorrected) supercluster energy is an important variable for electron scale factors, fake rates, etc. Propose to add this to the electron object.

**Comment by peruzzim** [comment]
We need to discuss this, what are the analysis-level corrections that have to be applied as a function of these variables?

**Comment by sethcooper** [comment]
HLT scale factors, for example (IIUC HLT uses supercluster Et).  Also, fake rates (using loose electron IDs) have been affected at least in the past by regression issues and would typically use supercluster Et.

I suppose one could alternatively add the ratio of SCEt/Pt (similar to the ECorr).
