### ISSUE TITLE
Save additional LHE level particles with status=+2

### ISSUE THREAD

**Issue by ktht** [cms-nanoAOD/cmssw#461]
For context, see: https://hypernews.cern.ch/HyperNews/CMS/get/generators/4553/2/1/1.html
Also, introduce the `LHEPart_status` attribute to distinguish LHE level particles with different statuses. I expect that the increase in file size is negligible, because there aren't that many LHE particles to begin with.
I can prepare a PR if there's any interest.

**Comment by peruzzim** [comment]
We could do this, but it really looks like a hack to get information from an old GEN setup.
It would not be nice to add a variable that is going to be fully redundant from now on, so it could be added under the appropriate modifier to only activate it where needed (2016 samples?).

Can you please investigate with GEN if this is indeed something we do not have anymore in recent samples? Is there a concrete use case foreseen?
The Higgs (pt,eta) might be accessed e.g. via the HTXS information, which could be a workaround, or reconstructed from the taus, as the HN message seems to suggest.

**Comment by vlimant** [comment]
ping / reopen if needed
