### ISSUE TITLE
Trigger Object Triple b-tag triggers for Run 2

### ISSUE THREAD

**Issue by fravera** [cms-nanoAOD/cmssw#465]
Good morning,
I would like to include  in the trigger objects for the Jets the filter used for the triple b-tag HLTs of Run2:

HLT_QuadJet45_TripleBTagCSV (Run2016)
HLT_DoubleJet90_Double30_TripleBTagCSV (Run2016)
HLT_HT300PT30_QuadJet_75_60_45_40_TripeCSV_p07_v3 (Run2017B)
HLT_PFHT300PT30_QuadPFJet_75_60_45_40_TriplePFBTagCSV_3p0_v3 (Run2017CDEF)
HLT_PFHT330PT30_QuadPFJet_75_60_45_40_TriplePFBTagDeepCSV (Run2018)

And in particular I would like to modify the current jet trigger object module to accomodate our needs (I assumed that the current one is just a place older). Since the modifications are minimal, I added the PSet for the jets I would like to add at the end of the issue message.

I was trying to verify that the modification works for the 3 years before opening the PR, but I encountered some issues.
As suggested in the twiki, I'm using CMSSW_11_0_0_pre11 on CC7 and I retrieved the latest updates from cms-nanoAOD/master-cmsswmaster.

Then I produced a config with the command
cmsDriver.py RECO -s NANO --nThreads 2 --data --era Run2_2017,run2_nanoAOD_106Xv1 --conditions 106X_dataRun2_v20 --eventcontent NANOEDMAOD --datatier NANOAOD --filein /store/data/Run2017B/SingleMuon/MINIAOD/09Aug2019_UL2017-v1/50000/62AF1C59-4BF5-9042-B450-0328A721B54F.root -n 100 --python_filename=nano_Run2017_SingleMuon.py --no_exec

But when I run it I got an error:
Exception Message:
edm::FileInPath unable to find file PhysicsTools/NanoAOD/data/creg_training_2017.pb anywhere in the search path.

Could you please cross check if I'm missing something?
Once I will be able to test it and you give me the green light I will proceed with the PR

Many thanks in advance.
Cheers,
Fabio

        cms.PSet(
            name = cms.string("Jet"),
            id = cms.int32(1),
            sel = cms.string("( type(0) || type(85) || type(86) || type(-99) )"), 
            # l1seed = cms.string("type(-99)"), l1deltaR = cms.double(0.3),
            # l2seed = cms.string("type(85) || type(86) || type(-99)"),  l2deltaR = cms.double(0.3),
            qualityBits = cms.string(
                "1         * filter('hltBTagCaloCSVp087Triple') + " \
                "2         * filter('hltDoubleCentralJet90') + " \
                "4         * filter('hltDoublePFCentralJetLooseID90') + " \
                "8         * filter('hltL1sTripleJetVBFIorHTTIorDoubleJetCIorSingleJet') + " \
                "16        * filter('hltQuadCentralJet30') + " \
                "32        * filter('hltQuadPFCentralJetLooseID30') + " \
                "64        * max(filter('hltL1sQuadJetC50IorQuadJetC60IorHTT280IorHTT300IorHTT320IorTripleJet846848VBFIorTripleJet887256VBFIorTripleJet927664VBF'), filter('hltL1sQuadJetCIorTripleJetVBFIorHTT')) + " \
                "128       * filter('hltQuadCentralJet45') + " \
                "256       * filter('hltQuadPFCentralJetLooseID45') + " \
                "512       * max(filter('hltL1sQuadJetC60IorHTT380IorHTT280QuadJetIorHTT300QuadJet'), filter('hltL1sQuadJetC50to60IorHTT280to500IorHTT250to340QuadJet')) + " \
                "1024      * filter('hltQuadCentralJet30') + " \
                "2048      * filter('hltCaloJetsQuad30ForHt') + " \
                "4096      * filter('hltHtMhtCaloJetsQuadC30') + " \
                "8192      * max(filter('hltCaloQuadJet30HT300'), filter('hltCaloQuadJet30HT320')) + " \
                "16384     * max(filter('hltBTagCaloCSVp05Double'), filter('hltBTagCaloDeepCSVp17Double')) + " \
                "32768     * filter('hltPFCentralJetLooseIDQuad30') + " \
                "65536     * filter('hlt1PFCentralJetLooseID75') + " \
                "131072    * filter('hlt2PFCentralJetLooseID60') + " \
                "262144    * filter('hlt3PFCentralJetLooseID45') + " \
                "524288    * filter('hlt4PFCentralJetLooseID40') + " \
                "1048576   * filter('hltPFCentralJetLooseIDQuad30forHt') + " \
                "2097152   * filter('hltHtMhtPFCentralJetsLooseIDQuadC30') + " \
                "4194304   * max(filter('hltPFCentralJetsLooseIDQuad30HT300'), filter('hltPFCentralJetsLooseIDQuad30HT330')) + " \
                "8388608   * max(filter('hltBTagPFCSVp070Triple'), filter('hltBTagPFDeepCSV4p5Triple'))" \
                ), 
            qualityBitsDoc = cms.string(
                "Jet bits: bit 0 for hltBTagCaloCSVp087Triple, bit 1 for hltDoubleCentralJet90, bit 2 for hltDoublePFCentralJetLooseID90," \
                " bit 3 for hltL1sTripleJetVBFIorHTTIorDoubleJetCIorSingleJet, bit 4 for hltQuadCentralJet30, bit 5 for hltQuadPFCentralJetLooseID30," \
                " bit 6 for hltL1sQuadJetC50IorQuadJetC60IorHTT280IorHTT300IorHTT320IorTripleJet846848VBFIorTripleJet887256VBFIorTripleJet927664VBF or hltL1sQuadJetCIorTripleJetVBFIorHTT," \
                " bit 7 for hltQuadCentralJet45, bit 8 for hltQuadPFCentralJetLooseID45," \
                " bit 9  for hltL1sQuadJetC60IorHTT380IorHTT280QuadJetIorHTT300QuadJet or hltL1sQuadJetC50to60IorHTT280to500IorHTT250to340QuadJet, bit 10 for hltQuadCentralJet30," \
                " bit 11 for hltCaloJetsQuad30ForHt, bit 12 for hltHtMhtCaloJetsQuadC30, bit 13 for hltCaloQuadJet30HT300 or hltCaloQuadJet30HT320," \
                " bit 14 for hltBTagCaloCSVp05Double or hltBTagCaloDeepCSVp17Double, bit 15 for hltPFCentralJetLooseIDQuad30, bit 16 for hlt1PFCentralJetLooseID75," \
                " bit 17 for hlt2PFCentralJetLooseID60, bit 18 for hlt3PFCentralJetLooseID45, bit 19 for hlt4PFCentralJetLooseID40, bit 20 for hltPFCentralJetLooseIDQuad30forHt," \
                " bit 21 for hltHtMhtPFCentralJetsLooseIDQuadC30, bit 22 for hltPFCentralJetsLooseIDQuad30HT300 or hltPFCentralJetsLooseIDQuad30HT330," \
                " bit 23 for hltBTagPFCSVp070Triple or hltBTagPFDeepCSV4p5Triple "),
        ),

**Comment by peruzzim** [comment]
please do a
`git clone https://github.com/cms-nanoAOD/PhysicsTools-NanoAOD.git $CMSSW_BASE/external/$SCRAM_ARCH/data/PhysicsTools/NanoAOD/data`
and recompile

(updating the workbook now)
