### ISSUE TITLE
HTML documentation for NanoAOD versions used in central production

### ISSUE THREAD

**Issue by pieterdavid** [cms-nanoAOD/cmssw#466]
The HTML pages that list the contents of the NanoAODs for the different branches, e.g. https://cms-nanoaod-integration.web.cern.ch/integration/master-102X/mc94X2016_doc.html , are very useful, but they track a branch (e.g. 10_6_X, master) or a specific PR.
Would it be possible to also have them for the versions of the code that were used in production, e.g. https://cms-nanoaod-integration.web.cern.ch/integration/NanoAODv6/mc94X2016_doc.html etc.?

**Comment by vlimant** [comment]
ping / reopen if needed
