### ISSUE TITLE
GenPart mass

### ISSUE THREAD

**Issue by nsmith-** [cms-nanoAOD/cmssw#483]
As @dntaylor pointed out in https://github.com/CoffeaTeam/coffea/issues/252 the GenPart_mass is zeroed for almost all particles with `pdg < 1000000`:
https://github.com/cms-nanoAOD/cmssw/blob/master-cmsswmaster/PhysicsTools/NanoAOD/python/genparticles_cff.py#L44

That's odd, what if someone wants to know what their super light Z' (32) or DM particle (51-53) mass is?  Sure it might be in the sample name but if the width is large or it is a parameter scan sample, important information is lost.
How about instead, a specific list of the most common final state particles: leptons pions protons etc.?

**Comment by nsmith-** [comment]
In a semileptonic ttbar sample from v6, the first 40 abs(pdg) account for 99.5% of the saved particles.

abspdg | count | frac
 -- | -- | --
21 | 5132878 | 0.187228
5 | 2177222 | 0.266644
11 | 2156068 | 0.345290
6 | 2070464 | 0.420812
24 | 1874716 | 0.489195
2 | 1283407 | 0.536008
22 | 1232330 | 0.580959
421 | 1165374 | 0.623467
1 | 1126924 | 0.664573
3 | 871381 | 0.696358
4 | 696062 | 0.721748
111 | 660295 | 0.745833
13 | 623898 | 0.768590
12 | 616228 | 0.791068
14 | 605473 | 0.813153
411 | 570826 | 0.833975
16 | 508380 | 0.852518
511 | 469848 | 0.869657
521 | 469413 | 0.886779
413 | 450484 | 0.903211
423 | 440867 | 0.919292
523 | 322499 | 0.931056
513 | 322043 | 0.942803
431 | 304688 | 0.953916
15 | 284229 | 0.964284
211 | 208156 | 0.971877
433 | 166132 | 0.977937
531 | 104342 | 0.981743
4122 | 89624 | 0.985012
533 | 71666 | 0.987626
221 | 63937 | 0.989958
5122 | 40499 | 0.991435
2101 | 26634 | 0.992407
2203 | 16998 | 0.993027
443 | 14731 | 0.993564
4132 | 11045 | 0.993967
223 | 10878 | 0.994364
4232 | 10568 | 0.994749
2103 | 10330 | 0.995126
445 | 9884 | 0.995487

`/store/mc/RunIIFall17NanoAODv6/TTToSemiLeptonic_TuneCP5_PSweights_13TeV-powheg-pythia8/NANOAODSIM/PU2017_12Apr2018_Nano25Oct2019_102X_mc2017_realistic_v7-v1/280000/B3005832-E5C9-1046-8976-7F31041E5C34.root`

**Comment by dntaylor** [comment]
I've closed the issue I created. I'll just mention what I posted there.
If the decision is not made to switch to explicit exclusion rather than explicit inclusion, adding the following will work for my use case:

`(abs(pdgId)>6 && abs(pdgId)<11) || (abs(pdgId)>16 && abs(pdgId)<21) || (abs(pdgId)>22 & abs(pdgId)<81)`

**Comment by nsmith-** [comment]
I ran a NanoAOD producer over 10k events of another dataset (`ZJetsToQQ_HT600to800`) with all mass filters disabled, and then checked the LZMA-9 compression ratio after zeroing progressively more particles.  Zeroing the top 20 `|pdg|` already led to a compression ratio better than the nominal scheme (`0.093`), somehow.  The list would be:


 abspdg | count | frac | ratio | name | nominalmass
 -- | -- | -- | -- | -- | --
21 | 230218 | 0.397389 | 0.593931 | g | 0.000000
23 | 57753 | 0.497079 | 0.541601 | Z0 | 91.187600
2 | 39558 | 0.565361 | 0.486578 | u | 0.002160
22 | 38615 | 0.632016 | 0.396971 | gamma | 0.000000
1 | 34877 | 0.692219 | 0.330045 | d | 0.004670
11 | 34605 | 0.751952 | 0.311872 | e- | 0.000511
111 | 28039 | 0.800351 | 0.280180 | pi0 | 0.134977
3 | 22007 | 0.838338 | 0.221823 | s | 0.093000
421 | 14428 | 0.863243 | 0.202324 | D0 | 1.864830
4 | 13944 | 0.887312 | 0.179795 | c | 1.270000
5 | 12219 | 0.908404 | 0.164563 | b | 4.180000
411 | 7271 | 0.920955 | 0.150167 | D+ | 1.869650
423 | 5335 | 0.930164 | 0.140805 | D*(2007)0 | 2.006850
413 | 5319 | 0.939345 | 0.127189 | D*(2010)+ | 2.010260
13 | 3442 | 0.945287 | 0.121658 | mu- | 0.105658
12 | 3425 | 0.951199 | 0.107387 | nu(e) | 0.000000
14 | 3190 | 0.956705 | 0.091927 | nu(mu) | 0.000000
431 | 3131 | 0.962109 | 0.083455 | D(s)+ | 1.968340
521 | 3081 | 0.967428 | 0.079161 | B+ | 5.279330
511 | 3048 | 0.972689 | 0.071193 | B0 | 5.279640

**Comment by nsmith-** [comment]
Closed by #498 thanks @dntaylor !
