### ISSUE TITLE
GenVisTau_genPartIdxMother does not correspond to the real mother

### ISSUE THREAD

**Issue by andreypz** [cms-nanoAOD/cmssw#486]
Hello,
I am looking at **H->tautau** events in [this file](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=file+file%3D%2Fstore%2Fmc%2FRunIIFall17NanoAODv5%2FZHToTauTau_M125_13TeV_powheg_pythia8%2FNANOAODSIM%2FPU2017_12Apr2018_Nano1June2019_102X_mc2017_realistic_v7-v1%2F40000%2FF1048FBC-1E3C-B041-92CE-C563322C9D93.root).
It seems to me that `GenVisTau_genPartIdxMother` does not really correspond to the index of the mother. For example, in some events this index is even larger than the total number of `GenPart` collection. Likely those indexes were not re-linked. Could you confirm?

Inside the `GenPart` collection the linking seems fine - mothers are what I expect them to be.

```
    genTaus = Collection(event, "GenVisTau")
    genParti = Collection(event, "GenPart")

    for gp in genParti:
        print("I am %i" % gp.pdgId)
        if gp.genPartIdxMother >= 0:
            print("\t and my mother is %i" % genParti[gp.genPartIdxMother].pdgId)

    for gt in genTaus:
        print("Tau: I am Tau")
        if gt.genPartIdxMother >= 0 and gt.genPartIdxMother<len(genParti):
            print("\t and my mother is %i" % genParti[gt.genPartIdxMother].pdgId)
```

**Comment by mariadalfonso** [comment]
@andreypz
is still issue present in recent UL nano ?

@mbluj
what do you think about this issue ?

**Comment by mbluj** [comment]
> 
> 
> @andreypz
> is still issue present in recent UL nano ?
> 
> @mbluj
> what do you think about this issue ?

Sorry, I read the issue only now.
From a quick check is seems that an incorrect collection is used to find an index of GenVisTaus' mother. Namely, `prunedGenParticles` are used in GenVisTauProducer [here](https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/taus_cff.py#L183) instead of  `finalGenParticles`.
@andreypz, could you check if it fixes the issue, please? And then, if it is the case, prepare a PR to the official CMSSW?

**Comment by mariadalfonso** [comment]
@andreypz did you have a chance to look into @mbluj suggestion ?

**Comment by andreypz** [comment]
Hi, 
No, unfortunately, I did not have time to test this. 
I think the suggestion by @mbluj makes sense, so someone should just make a PR.
Unfortunately, I no longer have a setup to test it, but I could maybe try to get it done later this week, or next week. But if you want the PR earlier - please do this yourself.

**Comment by mbluj** [comment]
I've made a quick test and it looks that the fix works, but if @andreypz has time to test it carefully with his framework it will be helpful. If it is not doable we (Tau POG) will try to test and implement the fix ourselves.
BTW, the gen particle collection should be changed in two places: L178 and L183.

**Comment by andreypz** [comment]
Sorry, I won't have time this week either to test this. Please go ahead without my checks and implement the fix by yourself as you suggested.

**Comment by mbluj** [comment]
@mariadalfonso, please assign me to this issue.

I have checked with a few thousands of taus from DY that switch of collection used to build genVisTaus from `prunedGenParticles` (miniAOD collection) to `finalGenParticles` (nanoAOD collection):
* fixes reported issue (as expected),
* has marginal impact on produced genVisTaus - with the new setup there is ~4/10000 less genVisTaus than with previous setup which is acceptable.

PR to master will be created soon, a backport to 106X will follow.

**Comment by mariadalfonso** [comment]
closing this issue, since is being addressed in the two PRs linked
