### ISSUE TITLE
Add di-muon vertex refit information

### ISSUE THREAD

**Issue by peruzzim** [cms-nanoAOD/cmssw#488]
@gkaratha please open the relevant PR

**Comment by gkaratha** [comment]
Dear Marco,

Thanks for reminder and many sorry for the delay. I opened it here: https://github.com/cms-nanoAOD/cmssw/pull/490 
Thanks and sorry again.

Best,
George

**Comment by vlimant** [comment]
please ping/re-open in cms-sw if needed
