### ISSUE TITLE
Update jet PU ID to 2017 version

### ISSUE THREAD

**Issue by peruzzim** [cms-nanoAOD/cmssw#492]

**Comment by nurfikri89** [comment]
@peruzzim I will be making the PR for this but I am a bit unsure of the workflow here. So @alefisico had made a [PR](https://github.com/cms-sw/cmssw/pull/28827) in the main cms-sw/cmssw to update the pile up jet ID parameters with the 94X and 102X training. Should I wait for that PR to be merged first or should I just start making my PR from my [branch](https://github.com/nurfikri89/cmssw/blob/nano_pileupjet_add94X102Xtraining/PhysicsTools/NanoAOD/python/jets_cff.py)? The changes will be [here](https://github.com/nurfikri89/cmssw/blob/nano_pileupjet_add94X102Xtraining/PhysicsTools/NanoAOD/python/jets_cff.py#L143-L144), [here](https://github.com/nurfikri89/cmssw/blob/nano_pileupjet_add94X102Xtraining/PhysicsTools/NanoAOD/python/jets_cff.py#L218-L221) and [here](https://github.com/nurfikri89/cmssw/blob/nano_pileupjet_add94X102Xtraining/PhysicsTools/NanoAOD/python/jets_cff.py#L635-L640).

Edit: Ignore the branch I had referenced above. The branch that I used for the PR is [this](https://github.com/nurfikri89/cmssw/tree/nanoMain_pileupjet_add94X102Xtraining/PhysicsTools/NanoAOD/python/jets_cff.py).

**Comment by peruzzim** [comment]
@nurfikri89 please open the PR to this repo with only nanoAOD-specific changes, I will add the PR to central CMSSW to the testing environment.

**Comment by camclean** [comment]
Small comment: Can we change the note for the pileup ID flags [here ](https://github.com/nurfikri89/cmssw/blob/nano_pileupjet_add94X102Xtraining/PhysicsTools/NanoAOD/python/jets_cff.py#L219) to make it clear that these are only for 80X? E.g. " puId = Var("userInt('pileupJetId:fullId')",int,doc="Pileup ID flags with 80X training.")"

**Comment by nurfikri89** [comment]
@camclean I will make this change in my next commit.

**Comment by camclean** [comment]
Thanks!

**Comment by camclean** [comment]
@peruzzim Do you want three discriminators for each sample or an era-dependent discriminator?

**Comment by camclean** [comment]
Suggestion from @peruzzim:

Include 80X flags for each year. 
Include only one set of discriminants per year using an era-dependent modifier (example [here](https://github.com/cms-sw/cmssw/blob/6399ee12ffb5414bcdf79f90b0938e4f04403246/PhysicsTools/NanoAOD/python/jets_cff.py#L75)):
- default 2018 config
- custom run2_jme_2016, run2_jme_2017

Changes to names and documentation:
**puId80XDisc** = Var("userFloat('pileupJetId:fullDiscriminant')",float,doc="Pilup ID discriminant with 80X **(2016)** training",precision=10),
**puId80X** = Var("userInt('pileupJetId:fullId')",int,doc="Pilup ID flags with 80X **(2016)** training"),
puId94XDisc = Var("userFloat('puId94XDisc')",float,doc="Pileup ID discriminant with 94X **(2017)** training",precision=10),
_**Remove:** puId94X = Var("userInt('puId94X')",int,doc="Pilup ID flags with 94X training"),_
puId102XDisc = Var("userFloat('puId102XDisc')",float,doc="Pileup ID discriminant with 102X **(2018)** training",precision=10),
_**Remove:** puId102X = Var("userInt('puId102X')",int,doc="Pilup ID flags with 102X training"),_

**Comment by nurfikri89** [comment]
@camclean Got it. I will make the changes today.

**Comment by peruzzim** [comment]
done in #493
