### ISSUE TITLE
Mistaken use of pt instead of phi in JetCorrectionUncertainty

### ISSUE THREAD

**Issue by jrueb** [cms-nanoAOD/cmssw#495]
I noticed the following line https://github.com/cms-nanoAOD/cmssw/blob/df7f0eed48ea04a2cb2e7487275c06e1ea076758/CondFormats/JetMETObjects/src/JetCorrectionUncertainty.cc#L124
It looks like it's supposed to push back phi (`result.push_back(mJetPhi);`) but instead it actually pushes pt. The pushing of pt is done already in the lines above it. Isn't this a mistake?

**Comment by peruzzim** [comment]
please report this in cms-sw/cmssw repository for JME to follow up, it's not a nanoAOD-specific issue

@lathomas @ahinzmann FYI
