### ISSUE TITLE
Vanilla CMSSW_11_0_0_pre13 nano sequence broken?

### ISSUE THREAD

**Issue by adewit** [cms-nanoAOD/cmssw#499]
Just using the instructions here: https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookNanoAOD#Recipe_for_the_current_HEAD_of_N for CMSSW_11_0_0_pre13, using this cmsDriver command `cmsDriver.py myNanoProdTestMC -s NANO --mc --eventcontent NANOAODSIM --datatier NANOAODSIM  --no_exec  --conditions 102X_upgrade2018_realistic_v15 --era Run2_2018,run2_nanoAOD_102Xv1 --customise_commands="process.add_(cms.Service('InitRootHandlers', EnableIMT = cms.untracked.bool(False)))"` to generate a config, and running on a file from a miniAOD sample with the corresponding GT, I get
```
----- Begin Fatal Exception 10-Feb-2020 16:46:32 CET-----------------------
An exception of category 'NoProxyException' occurred while
   [0] Processing  Event run: 1 lumi: 598 event: 2985003 stream: 0
   [1] Running path 'nanoAOD_step'
   [2] Calling method for module PATTauDiscriminationByMVAIsolationRun2/'patTauDiscriminationByIsolationMVArun2v1DBoldDMwLTraw'
Exception Message:
No data of type "GBRForest" with label "RecoTauTag_tauIdMVAIsoDBoldDMwLT" in record "GBRWrapperRcd"
 Please add an ESSource or ESProducer to your job which can deliver this data.
----- End Fatal Exception -------------------------------------------------
```
In CMSSW_10_6_X the same steps (modulo the merge topic using the CMSSW_10_6_X branch instead of cmssw-master) work fine. Not being an expert on the tau sequences I wasn't able to figure out quickly what is supposed to be happening here. Is this a known problem?

**Comment by peruzzim** [comment]
It's due to TAU moving the payloads for ID into the GT with the 11_0_X series, so you should use a 110X_something GT when running from that release (but note I don't think we have GTs in 110X for all years with latest JEC etc., to my knowledge).
I will close this issue as it's understood, please reopen if the problem persists.
