### ISSUE TITLE
Relationship between NanoAOD version and ntuple content

### ISSUE THREAD

**Issue by andreypz** [cms-nanoAOD/cmssw#500]
I just found out experimentally that content of nanoAODv6 is different depending on the era:
- for 2016 samples the `110X` version is used
- for 2017 samples the `106X` version was used
I think this is not clear from the twiki or names of the sampled and it would be useful if this was more clearly documented.
Also, is there a plan to unify the content for all three years (if that's possible)? Apart from trigger names probably this should be possible.

**Comment by peruzzim** [comment]
which content are you referring to? all central productions of Run-2 samples were done in 10_2_X

**Comment by andreypz** [comment]
Yes, central production.
Well, if I take [this file](https://cmsweb.cern.ch/das/request?input=file%3D%2Fstore%2Fmc%2FRunIISummer16NanoAODv6%2FZH_HToCC_ZToLL_M-125_TuneCUEP8M1_13TeV-powheg-pythia8%2FNANOAODSIM%2FPUMoriond17_Nano25Oct2019_102X_mcRun2_asymptotic_v7-v1%2F270000%2F08C5B3E0-5BBA-F54E-AD09-43F0851FFB6D.root&instance=prod/global) (2016 MC sample) it has a variable names `Photon_cutBased`,
but if I take [this one](https://cmsweb.cern.ch/das/request?input=file%3D%2Fstore%2Fmc%2FRunIIFall17NanoAODv6%2FZH_HToCC_ZToLL_M125_13TeV_powheg_pythia8%2FNANOAODSIM%2FPU2017_12Apr2018_Nano25Oct2019_102X_mc2017_realistic_v7_ext1-v1%2F70000%2FE6A356F9-294A-E74F-BE19-CE58A0D17C7E.root&instance=prod/global) (2017 MC sample) it does not have `cutBased` - instead it contains `Photon_cutBasedBitmap` variable. Both are NanoAODv6, if I understand correctly.
To me that would correspond to `110X` and `106X` (or `102X`) production respectively, according to the [content auto-description on the wtiki](https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookNanoAOD#Content_auto_documentation)

**Comment by andreypz** [comment]
In addition to the above, it seems like in 2016 samples (`110X` content) the `Photon_cutBased` is not a bitMap, but rather an integer with values 0, 1, 2, 3. Is it so?

**Comment by vlimant** [comment]
please ping/re-open in cms-sw if needed
