### ISSUE TITLE
Masses of gen particles

### ISSUE THREAD

**Issue by ktht** [cms-nanoAOD/cmssw#51]
Hi,

Is there a standard way to get the masses of generator level particles based on their PDG id? My first idea was to use ROOT's [TDatabasePDG](https://root.cern.ch/doc/master/classTDatabasePDG.html) class, but the database coming with the ROOT package is [outdated](https://github.com/root-project/root/blob/efbbe8f3a6a684383e21ed90883aa9be95c567a8/etc/pdg_table.txt#L310) and won't be fixed [any time soon](https://sft.its.cern.ch/jira/browse/ROOT-7242).

What would be the correct and standard way to get the masses of generator level particles?

Thanks

**Comment by arizzi** [comment]
see #45

**Comment by arizzi** [comment]
actually this could still be relevant for low mass stable particles, but likely more in NanoAOD-tools than in NanoAOD.

**Comment by arizzi** [comment]
when you say it is not updated, which relevant particles for which we would not store the mass are missing ? (I imagine, leptons, pions, B/D hadrons etc.. are there)

**Comment by ktht** [comment]
All particles are there but, for instance, Higgs mass is at [80 GeV](https://github.com/root-project/root/blob/efbbe8f3a6a684383e21ed90883aa9be95c567a8/etc/pdg_table.txt#L310). I haven't cross-checked other masses.

**Comment by ktht** [comment]
I think it would be possible to create a version of the PDG table and use that. But then someone needs to check if all the masses are correct. Indeed, this could be done in a post-processing step with the nanoAOD-tools.

The third option would be a histogram (or some other representation) that maps the PDG IDs to the particle masses. But I'm not sure if that's a good solution if you want to keep everything in TTrees.

**Comment by arizzi** [comment]
if you check #45 the proposal is to store masses of particles above 10GeV so Higgs is not a problem (plus a  pdgId derived mass for massive objects is useless as we often have samples with different higgs masses, exotics models, off shell particles etc..)

**Comment by arizzi** [comment]
#54 please reopen the issue about PDGid lookup (if still relevant) under nanoAOD-tools
