### ISSUE TITLE
Electron IP sign

### ISSUE THREAD

**Issue by swertz** [cms-nanoAOD/cmssw#514]
In #479 the sign of the 2D IP (dxy) for muons was fixed, and if I understand correctly the issue was fixed upstream in PAT (here https://github.com/cms-sw/cmssw/pull/28753) by switching from using `IPTools::signedTransverseImpactParameter()` to ` reco::TrackBase::dxy()`.

However it seems that PAT electrons still use `signedTransverseImpactParameter()`: https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/PatAlgos/plugins/PATElectronProducer.cc#L1150-L1159

Is there a reason why this wasn't changed for electrons?

**Comment by peruzzim** [comment]
to be discussed offline

**Comment by arizzi** [comment]
was it discussed?

**Comment by swertz** [comment]
Didn't have any reply, I'll send a reminder.

**Comment by swertz** [comment]
Fixed in https://github.com/cms-sw/cmssw/pull/30738 (+ backport to 106X). Not sure if a fix a la #479 for non-UL is also needed?

**Comment by mariadalfonso** [comment]
@swertz 
Thanks for this check.
indeed a fix like this for the OLD miniAOD is beneficial especially if we go for the re-nano of the UL before doing the re-mini.

**Comment by mariadalfonso** [comment]
For miniAOD it's taken care starting from the reminiAOD of the UL.
For nano made from previously made mini, the PR linked above fixed the issue.
