### ISSUE TITLE
Store energy scale and resolution uncertainties for electrons and photons?

### ISSUE THREAD

**Issue by nurfikri89** [cms-nanoAOD/cmssw#515]
This issue is related to the hypernews thread [1] on retrieving and applying energy scale and resolution uncertainties for electrons and photons at the level of nanoAOD post-processing in nanoAOD-tools. In the thread, it was pointed out [2] that 

> these scale systematics are applied on the 
> ecal energy only (uncorrected for scales but corrected for regression due to loss etc)
> and then further combined an E-p combination is performed to get the final post 
> scale-smearing corrected p4.

Should we identify these missing variables and add them into nanoAODs? An alternative suggestion is to directly store the scaled (up & down) and smeared energy 
I suppose this involves adding the following floats for electrons and photons:
userFloat("energyScaleUp")
userFloat("energyScaleDown")
userFloat("energySigmaUp")

Kind regards,
Fikri

[1] https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3713.html
[2] https://hypernews.cern.ch/HyperNews/CMS/get/physTools/3713/1/1/1/2/1.html

**Comment by mariadalfonso** [comment]
this is being done in cms-sw/32966

**Comment by mariadalfonso** [comment]
closing this since has been handled
