### ISSUE TITLE
Update EGM 2016 effective areas to latest recommended version (Fall17v2)

### ISSUE THREAD

**Issue by peruzzim** [cms-nanoAOD/cmssw#518]

**Comment by mariadalfonso** [comment]
@shilpi @peruzzim

does this items still need an update ?

**Comment by mariadalfonso** [comment]
This is my understanding.
2016-17-18 use the same corrections and those from Fall17 are the latest ones to use for the UL 
used in 
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/photons_cff.py#L63-L65
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/electrons_cff.py#L131-L132

For Electron
https://github.com/cms-sw/cmssw/blob/CMSSW_10_2_X/RecoEgamma/ElectronIdentification/data/Fall17/effAreaElectrons_cone03_pfNeuHadronsAndPhotons_94X.txt

For Photons
https://github.com/cms-sw/cmssw/blob/CMSSW_10_2_X/RecoEgamma/PhotonIdentification/data/Fall17/effAreaPhotons_cone03_pfChargedHadrons_90percentBased_V2.txt
https://github.com/cms-sw/cmssw/blob/CMSSW_10_2_X/RecoEgamma/PhotonIdentification/data/Fall17/effAreaPhotons_cone03_pfNeutralHadrons_90percentBased_V2.txt
https://github.com/cms-sw/cmssw/blob/CMSSW_10_2_X/RecoEgamma/PhotonIdentification/data/Fall17/effAreaPhotons_cone03_pfPhotons_90percentBased_V2.txt
