### ISSUE TITLE
Add tauID against electrons in deadECAL regions

### ISSUE THREAD

**Issue by mbluj** [cms-nanoAOD/cmssw#519]
As title says it is about adding tauID against electrons in deadECAL regions - one boolean.

Update of nanoAOD should be preformed on top of updates to the tauID as in the following PRs respectively for 11_1_X, 10_6_X, and 10_2_X https://github.com/cms-sw/cmssw/pull/29627, https://github.com/cms-sw/cmssw/pull/29739, and https://github.com/cms-sw/cmssw/pull/29747.

Please let us know what is best way to proceed to have this tauID as soon as possible integrated to production versions of nanoAOD: should we wait with including this tauID to nanoAOD until the PRs are merged, or build PRs to nanoAOD repo on top of PRs to CMSSW, or include updates related to nanoAOD to PRs to CMSSW? The latter possibility can be fine assuming that nanoAOD in the main CMSSW repo (for release series of interest) is well synced with corresponding development versions in the nanoAOD repo.

**Comment by mariadalfonso** [comment]
Integrated in nanoAOD in CMS cms-sw 11_2 and 10_6: see PR31077 PR31065
