### ISSUE TITLE
suggestion on implementing the flag to decide DeepMET calculation or extraction for Nano?

### ISSUE THREAD

**Issue by yongbinfeng** [cms-nanoAOD/cmssw#524]
Dear experts,

we are working on adding DeepMET into NanoAOD: it can be calculated on the fly and written to nano. But we expect in the future DeepMET would have already been calculated and saved in MiniAOD, such that in the nano step we only need to do the extractions rather than recalculating.

Any suggestions on how to implement such a flag to make the extraction/calculation decision? We are thinking about era modifiers but apparently there are too many eras for the past.

Thanks a lot. 

@steggema @intrepid42

@lathomas @ahinzmann @saghosh

**Comment by ahinzmann** [comment]
Here is an example for PUPPI, which is usually not computed for Mini, but only in certain reMiniAODs:
https://github.com/cms-sw/cmssw/pull/29826/files#diff-416ad16d53535660648a4a4bb98636d6R25

This example hold for MiniAOD, where the default behavior is to not recompute PUPPI, but only do it for re-minis.

I'm not sure if the same kind of eras exist for NanoAOD campaigns as well?
adding also @peruzzim for this

**Comment by steggema** [comment]
@peruzzim @fgolf @gouskos would be great if someone responsible for the NanoAOD campaigns could comment! This should be a simple question so I hope you can answer in the next few days.

The default would be to just use what is pre-calculated in MiniAOD, which will be available in all future campaigns and in campaigns that produce MiniAOD and NanoAOD concurrently. The question is if there is an era modifier (or a list of era modifiers) that we can use to identify all (upcoming) NanoAOD campaigns that use already existing MiniAOD, for which we would have to calculate DeepMET in the NanoAOD step. Or maybe there's no such scenario planned or used in testing, and we don't need any of this and can just assume that it's pre-calculated in MiniAOD?

**Comment by mariadalfonso** [comment]
issue resolved.
the DeepMET has been added in the nano.
