### ISSUE TITLE
genEventSumw is called genEventSumw_ in some UL NanoAOD samples

### ISSUE THREAD

**Issue by pieterdavid** [cms-nanoAOD/cmssw#530]
@kjaffel and I noticed that some NanoAOD samples do not have the usual branches in the `Runs` tree - but they appear to be there with an extra underscore at the end (so `genEventSumw_` instead of `genEventSumw`), and the content seems to be correct.
This is only the case for some samples, a few examples are:
```
/DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer19UL17NanoAOD-106X_mc2017_realistic_v6-v2/NANOAODSIM
/TTToHadronic_TuneCP5_13TeV-powheg-pythia8/RunIISummer19UL17NanoAOD-106X_mc2017_realistic_v6-v4/NANOAODSIM
/ST_tW_antitop_5f_DS_NoFullyHadronicDecays_TuneCP5_13TeV-powheg-pythia8/RunIISummer19UL17NanoAOD-106X_mc2017_realistic_v6-v1/NANOAODSIM
/W2JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer19UL17NanoAOD-106X_mc2017_realistic_v6-v2/NANOAODSIM
/W3JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer19UL17NanoAOD-106X_mc2017_realistic_v6-v2/NANOAODSIM
/W4JetsToLNu_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer19UL17NanoAOD-106X_mc2017_realistic_v6-v2/NANOAODSIM
```

We didn't dig deeper to find out what may be causing it yet (it is also easy to work around, only a bit annoying), just reporting to save other people some time, and to make sure this does not go unnoticed.

**Comment by swertz** [comment]
Wasn't this fixed in #478 ?

**Comment by mariadalfonso** [comment]
@swertz @pieterdavid 
please confirm that this issue is fixed already for the nanoV7 as indicated in https://github.com/cms-nanoAOD/cmssw/issues/530#issuecomment-659922227
so that we can close this issue

**Comment by pieterdavid** [comment]
@mariadalfonso for NanoAODv7 it is `genEventSumw` everywhere indeed - but this was for UL NanoAOD (which I assumed was "newer" also in terms of code - I'm sorry for the noise if that was not the case)

**Comment by mariadalfonso** [comment]
@pieterdavid 

I see that you are looking at the V6 version of the nano UL made out of the Summer19 for 2017.
The first good version for the nano for UL analysis will be the V8, that inherit the code from the V7 and will then contain the fix.
We will renano with a V8 version all the Summer19 and Summer20 miniAOD soon.

I close this issue then as no other fixes will be required.

**Comment by pieterdavid** [comment]
@mariadalfonso I did not notice the "v6" - thanks for clarifying!
