### ISSUE TITLE
Missing selection on EM energy fraction in jets in CorrT1METJet

### ISSUE THREAD

**Issue by andrey-popov** [cms-nanoAOD/cmssw#531]
The standard type 1 correction to missing p<sub>T</sub> is [done](https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETRun2Corrections#Type_I_Correction_Propagation_of) using jets with the electromagnetic energy faction of less than 0.9. While it is available for the main collection of jets via branches `Jet_chEmEF` and `Jet_neEmEF`, these energy fractions are not stored in collection `CorrT1METJet`. I thought that maybe the jets in that collection have already been filtered, but this doesn't seem to be the case: here is the [source and cut](https://github.com/cms-sw/cmssw/blob/CMSSW_10_2_23/PhysicsTools/NanoAOD/python/nano_cff.py#L192-L193) of the corresponding table, and the source collection is defined [here](https://github.com/cms-sw/cmssw/blob/CMSSW_10_2_23/PhysicsTools/NanoAOD/python/jets_cff.py#L172). This problem was already reported in cms-nanoAOD/nanoAOD-tools#238.

I doubt we need the energy fractions per se in `CorrT1METJet`. Instead, it would be sufficient to add a boolean branch indicating whether the jet passes the selection. Alternatively, we could not store jets that don't pass the cut on the energy fraction, but this is less desirable since people might be using those jets for purposes other than the type 1 correction. I can try to prepare a pull request if needed. Please let me know.

**Comment by mariadalfonso** [comment]
@andrey-popov 
was this handled ?

@lathomas
@alkaloge

**Comment by vlimant** [comment]
closing. please ping/reopen in cms-sw if necessary
