### ISSUE TITLE
features for V8 nanoAOD

### ISSUE THREAD

**Issue by mariadalfonso** [cms-nanoAOD/cmssw#533]
-------- **GEN**--------

PS weights
- [x] https://github.com/cms-sw/cmssw/pull/31276 (bug-fixes; added option to save all 150 weights, no changes to central nano, genNano updated)
- [x] backport https://github.com/cms-sw/cmssw/pull/31564
- [x] backport 10_2 https://github.com/cms-sw/cmssw/pull/31620

LHEweights fix with newer MadGraph
- [x] https://github.com/cms-sw/cmssw/pull/31680
- [x] backport  https://github.com/cms-sw/cmssw/pull/32105

PS weight fix for newer CMSSW
- [x] https://github.com/cms-sw/cmssw/pull/31982
- [x] backport https://github.com/cms-sw/cmssw/pull/32105

PDF (LHAPDF NNPDF3.1)
- [x] https://github.com/cms-sw/cmssw/pull/31946
- [x] backport https://github.com/cms-sw/cmssw/pull/32105

EWK weights for Wmass 
- [x] https://github.com/cms-sw/cmssw/pull/31939
- [x] backport https://github.com/cms-sw/cmssw/pull/32105

Fix PSnnlo weights
- [x] https://github.com/cms-sw/cmssw/pull/32071
- [x] backport https://github.com/cms-sw/cmssw/pull/32105

GenVertex
- [x] https://github.com/cms-sw/cmssw/pull/32008
- [x] backport https://github.com/cms-sw/cmssw/pull/32127

-------- **TAU**--------
Tau dead Ecal
- [x] master https://github.com/cms-sw/cmssw/pull/31077 _feature **added** consistently in all datasets_
- [x] backport https://github.com/cms-sw/cmssw/pull/31065 _(recomputed in ~devel, added in devel)_

Tau antiElectron
- [x] master cms-sw#27465 + [x] cms-sw#31302
- [x] backport https://github.com/cms-sw/cmssw/pull/31065 _anti-electron ID updated for devel while is unchanged in previous eras_ (consistent with master branch)

-------- **JetMET**--------
MET filters.  _( new badMuon filter available only for new miniAOD )_
- [x] master https://github.com/cms-sw/cmssw/pull/30015 + [x] https://github.com/cms-sw/cmssw/pull/30974  + [x] https://github.com/cms-sw/cmssw/pull/31432. + need to  fix and re-run on previous nano
- [x] backport https://github.com/cms-sw/cmssw/pull/31087

DeepMET
- [x] master https://github.com/cms-sw/cmssw/pull/30291 _feature **added** consistently in all datasets_
- [x] backport https://github.com/cms-sw/cmssw/pull/31120  _(recomputed in ~devel or added in devel, new branches will be available)_

Fix Puppi MET
- [x] master https://github.com/cms-sw/cmssw/pull/30922 _puppiMET_ type1 fixed + for the UL we switch to v15 puppi_
- [x] backport https://github.com/cms-sw/cmssw/pull/31638

ParticleNet AK8
- [x] https://github.com/cms-sw/cmssw/pull/31096 _feature **added** consistently in all datasets_
- [x] backport https://github.com/cms-sw/cmssw/pull/31244 _( added in devel otherwise recomputed, new branch "ParticleaNet" will be available)_

Cleanup the duplicate ECF
- [x] https://github.com/cms-sw/cmssw/pull/31213  + [x] https://github.com/cms-sw/cmssw/pull/31303
backport not planned

HF showershapes _feature **added** consistently in all datasets_
- [x] https://github.com/cms-sw/cmssw/pull/31271 + [x] https://github.com/cms-sw/cmssw/pull/31446
- [x] backport https://github.com/cms-sw/cmssw/pull/31420

HF noise filter
- [x] https://github.com/cms-sw/cmssw/pull/31328 _( new filter available only for new miniAOD )_
- [x] backport https://github.com/cms-sw/cmssw/pull/31413

PU-MC info
- [x] https://github.com/cms-sw/cmssw/pull/31831 (off by default)
- [x] backport https://github.com/cms-sw/cmssw/pull/31872

-------- **BTV** --------

General update of discriminators 
- [x] https://github.com/cms-sw/cmssw/pull/31618 + https://github.com/cms-sw/cmssw/pull/31786
- [x] backport https://github.com/cms-sw/cmssw/pull/31847

Add nTracks in SV
- [x] https://github.com/cms-sw/cmssw/pull/31696
- [x] backport https://github.com/cms-sw/cmssw/pull/31825

-------- **EGM**--------

EGAMMA gainSwitch Fix
- [x] https://github.com/cms-sw/cmssw/pull/31293
- [x] https://github.com/cms-sw/cmssw/pull/31497

EGAMMA fixIP for the old miniAOD
- [x] https://github.com/cms-sw/cmssw/pull/31495
- [x] backport https://github.com/cms-sw/cmssw/pull/31805

Scale and Smearing for UL 2017-2018
- [x] https://github.com/cms-sw/cmssw/pull/31974
- [x] backport https://github.com/cms-sw/cmssw/pull/32002

-------- **Leptons**--------

additional informations for MVA
- [x] https://github.com/cms-sw/cmssw/pull/31944
- [x] backport https://github.com/cms-sw/cmssw/pull/32024

---- features for the GEN Custom-NanoAODs:

master:
- [x] https://github.com/cms-sw/cmssw/pull/30306
- [x] https://github.com/cms-sw/cmssw/pull/31591
- [x] https://github.com/cms-sw/cmssw/pull/31973

- [x] backport https://github.com/cms-sw/cmssw/pull/31909

---- features for the JME Custom-NanoAODs:

QGL :  
- [x] master https://github.com/cms-sw/cmssw/pull/29257 
 backport https://github.com/cms-sw/cmssw/pull/29290 (closed, not needed)

jets format: 
- [x] master https://github.com/cms-sw/cmssw/pull/30674 
- [x] backport https://github.com/cms-sw/cmssw/pull/31124 +  [x] https://github.com/cms-sw/cmssw/pull/31207

ak4 particleNet: 
- [x] master https://github.com/cms-sw/cmssw/pull/31714 
- [x] backport https://github.com/cms-sw/cmssw/pull/31717

**Comment by ahinzmann** [comment]
Jet ID for central NanoAODs:

- [x] master cms-sw#31125
- [x] backport #31126

**Comment by mariadalfonso** [comment]
I document here the modifiers to be used in master:

```
EOY 2016
'run2_nanoAOD_94X2016'

EOY 2017
'run2_nanoAOD_94XMiniAODv1'
'run2_nanoAOD_94XMiniAODv2'

EOY 2018 
'run2_nanoAOD_102Xv1'

UL
'run2_nanoAOD_106Xv1'
```

Modifier to be used in 10_6 is:
use `'run2_miniAOD_devel' ` : we will change in `'run2_miniAOD_UL'` all at once when introducing a proper workflow.

For other older version of Run2 data/mc, modifications are optional: `'run2_nanoAOD_92X' 'run2_miniAOD_80XLegacy'`

**Comment by mariadalfonso** [comment]
PR listed in https://github.com/cms-nanoAOD/cmssw/issues/533#issue-672678596 and https://github.com/cms-nanoAOD/cmssw/issues/533#issuecomment-672931455
entered 10_6_19 (candidate release for V8)

Still being worked the following

Finalize Puppi MET with puppiV15; update PUjetID
- [x] master https://github.com/cms-sw/cmssw/pull/31927
- [x] backport https://github.com/cms-sw/cmssw/pull/32076

**Comment by mariadalfonso** [comment]
finalized release for the nano V8nano is this one with the all the items from this issue
https://github.com/cms-sw/cmssw/releases/tag/CMSSW_10_6_19_patch1

**Comment by mariadalfonso** [comment]
Fix crash and really enable puppiV15 in 10_6; 

- [x] https://github.com/cms-sw/cmssw/pull/32328
- [x] https://github.com/cms-sw/cmssw/pull/32329

release for nanoV8 here
https://github.com/cms-sw/cmssw/releases/tag/CMSSW_10_6_19_patch2
