### ISSUE TITLE
Wrong gainSeed value for EGM objects

### ISSUE THREAD

**Issue by peruzzim** [cms-nanoAOD/cmssw#534]
there is a bug in the producer of seed gain values for EGM objects

https://github.com/cms-sw/cmssw/blob/503f8053329b5587411ab9607f14955428587ccf/PhysicsTools/NanoAOD/plugins/EGMSeedGainProducer.cc#L77

@jwill24

**Comment by mariadalfonso** [comment]
addressed in cms-sw, see PR31293
