### ISSUE TITLE
Anomalous HF signal  in the region eta=3-3.2.

### ISSUE THREAD

**Issue by mariadalfonso** [cms-nanoAOD/cmssw#536]
There is residual HFnoise (instrumental, non collisional ?) in the region eta=3-3.2.

Two things can be done:

1. add some variable that help with a JetID
See Laurent presentation
https://indico.cern.ch/event/944298/#sc-10-4-hf-noise-study-on-aod

2. keep the list of the reducedHcalHits with all the hits flagged by the HCAL severity level in the miniAOD as well (for now are only in the AOD).

**Comment by lathomas** [comment]
Ongoing. See: 
https://github.com/cms-sw/cmssw/pull/31271
https://github.com/cms-sw/cmssw/pull/31328
https://github.com/cms-sw/cmssw/pull/31375 
https://github.com/cms-sw/cmssw/pull/31446

**Comment by mariadalfonso** [comment]
addressed in cms-sw, see list of PR in https://github.com/cms-nanoAOD/cmssw/issues/536#issuecomment-691958906
