### ISSUE TITLE
LHEScaleWeight includes seemingly duplicate entries

### ISSUE THREAD

**Issue by jrueb** [cms-nanoAOD/cmssw#537]
For data sets that were generated more recently with MadGraph, the resulting NanoAOD contains 44 floats per event in the `LHEScaleWeight` branch instead of the usual 9. An example data set for this is `/HscalarToTTbarToDiLep_M-400_noHadTausFilter_TuneCP5_PSweights_interference_13TeV-madgraph_pythia8/RunIIFall17NanoAODv7-PU2017_12Apr2018_Nano02Apr2020_102X_mc2017_realistic_v8-v1/NANOAODSIM`. The documentation string of the `LHEScaleWeight` makes it look like each number is repeated 5 times.
The cause of this seems to be that newer MadGraph data sets also contain dynamical scale choices on top of different choices for mur and muf. These additional dynamical scale variations get omitted in the documentation string.
I think the proper solution for this would be to skip the values coming from the dynamical scale choices and keep putting only 9 entries into `LHEScaleWeight`.

**Comment by vlimant** [comment]
part of GEN weight refactoring  please follow up in https://github.com/cms-sw/cmssw/pull/32167
