### ISSUE TITLE
Bug for MC genweight vector of size 1 

### ISSUE THREAD

**Issue by agrohsje** [cms-nanoAOD/cmssw#538]
Dear all,
there is a bug in this line:
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc#L438
double w0 = weights.at(1);
The number of elements in GEN weight vector needs to be checked first. There can be events with single-entry weight vector, see e.g. these requests [1].
Cheers, Alexander.
[1] https://its.cern.ch/jira/browse/CMSCOMPPR-16642#add-comment

**Comment by mariadalfonso** [comment]
addressed in cms-sw the PR31276
