### ISSUE TITLE
L1 and HLT prescale values

### ISSUE THREAD

**Issue by gouskos** [cms-nanoAOD/cmssw#544]
Include L1 and HLT prescale values in nanoAOD (or in nanoAOD-tools)
(a) useful in multiple areas: Jet and met calibration, trigger efficiency, fake rate studies in analyses [e.g., SUSY multileptons], CRs in hadronic searches, etc..
(b) how to best implement it - work in progress

**Comment by mariadalfonso** [comment]
some comment at the CMSweek plenary

* size
we can store with lumi granularity and not at each event

* what analysis need this ?
some SMP analysis use them (from Rappoccio)

**Comment by mariadalfonso** [comment]
some information:

standalone access this outside of the CMSSW framework.
https://twiki.cern.ch/twiki/bin/viewauth/CMS/HLTStandAlonePrescaleInformation

can be retrieve from this getPreScColumn()
https://github.com/cms-sw/cmssw/blob/master/DataFormats/L1TGlobal/interface/GlobalAlgBlk.h#L70

**Comment by vlimant** [comment]
dully noted.
