### ISSUE TITLE
Jet Cleanup

### ISSUE THREAD

**Issue by mariadalfonso** [cms-nanoAOD/cmssw#547]
https://cms-nanoaod-integration.web.cern.ch/integration/pr31618/mc106Xul18_size_report.html#Jet

- [ ] redefine the precision of the jet eta/phi

currently 
jet eta/phi are saved with high precision ~ 12 as leptons
while the pt are redefined with precision 10

https://github.com/cms-sw/cmssw/blob/540da10c5a27a2dadb0b06c28b5ca5db3a2f58f5/PhysicsTools/NanoAOD/python/jets_cff.py#L261
https://github.com/cms-sw/cmssw/blob/540da10c5a27a2dadb0b06c28b5ca5db3a2f58f5/PhysicsTools/NanoAOD/python/jets_cff.py#L548

- [ ] the HFnoise variables added for the v8 (two ints and two floats) can be translated to one bool given the cut in slide3/4
https://lathomas.web.cern.ch/lathomas/JetMETStuff/HFNoiseStudy/HFNoise_VBFHinv_Laurent.pdf
the basic variables can stay in the JMEnano

DQM
- [ ] the SD mass is defined as positive so can restrict the range here https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/nanoDQM_cfi.py#L165
- [ ] the SumET has a lot of underflow https://gouskos.web.cern.ch/gouskos/xpog/nanoaod-v9/puppimet/plots/RawPuppiMET_sumEt.pdf

- [x] the variables Jet_chFPV0EF, Jet_chFPV1EF,Jet_chFPV2EF,Jet_chFPV3EF  can be moved to the JMEnano and removed from central

Self-Documentation:
- [ ]  i.e. jet_id would be good to be more verbose i.e. bit0= loose, bit1 == medium, bit2 == tight see here the generic comment
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/jetsAK4_CHS_cff.py#L151

**Comment by lathomas** [comment]
Hello, 
For the HF variables, we are still optimizing the cuts (and at least one analysis is using the full variable in NANO). These variables however only apply for high pt HF jets so I suspect the size should be heavily compressed compared to usual Floats (?)

**Comment by mariadalfonso** [comment]
> * [ ]  the variables Jet_chFPV0EF, Jet_chFPV1EF,Jet_chFPV2EF,Jet_chFPV3EF  can be moved to the JMEnano and removed from central

this is done in cms-sw/33824

**Comment by vlimant** [comment]
noted
