### ISSUE TITLE
electron scale and smearing for UL-106Xv1

### ISSUE THREAD

**Issue by mariadalfonso** [cms-nanoAOD/cmssw#548]
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/electrons_cff.py#L168-L187
The scale and smearing of the ULnano should be properly set for  run2_nanoAOD_106Xv1

corrections already available for 2017 UL
https://github.com/cms-sw/cmssw/blob/master/RecoEgamma/EgammaTools/python/calibratedEgammas_cff.py#L5

Need a mechanism to switch among the years (2018 will be delivered soon)

@jainshilpi

**Comment by jainshilpi** [comment]
@mariadalfonso based on our discussions, I will get back to it this week. thanks

**Comment by mariadalfonso** [comment]
done in cms-sw 31974
