### ISSUE TITLE
cleanup GenWeightsTableProducer.cc

### ISSUE THREAD

**Issue by mariadalfonso** [cms-nanoAOD/cmssw#553]
- [ ] remove the std::cout comment https://github.com/cms-sw/cmssw/pull/31939#issuecomment-718118083

- [ ] add comments in the code to specify with part of the code handle which exceptions https://github.com/cms-sw/cmssw/pull/31680#issuecomment-720600890

**Comment by vlimant** [comment]
dully noted.
