### ISSUE TITLE
features for V9 nanoAOD

### ISSUE THREAD

**Issue by mariadalfonso** [cms-nanoAOD/cmssw#555]
-------- **PPS**--------

Data table
- [x] master 11_3 https://github.com/cms-sw/cmssw/pull/31531
- [x] backport 10_6 https://github.com/cms-sw/cmssw/pull/32616

-------- **JetMET**--------
 
2016: puJetID for Ul16 + QGL 2016
- [x] master https://github.com/cms-sw/cmssw/pull/33925
- [x] backport 10_6 https://github.com/cms-sw/cmssw/pull/33964

2016: AK8 gen match 
- [x] master https://github.com/cms-sw/cmssw/pull/33839
- [x] backport 10_6 https://github.com/cms-sw/cmssw/pull/33990

2016: JetID
- [x] master https://github.com/cms-sw/cmssw/pull/33826
- [x] backport 10_6 https://github.com/cms-sw/cmssw/pull/33843
 
cleanup JetVariables
- [x] master https://github.com/cms-sw/cmssw/pull/33824
- [x] backport 11_2 https://github.com/cms-sw/cmssw/pull/33834
- [x] backport 10_6 https://github.com/cms-sw/cmssw/pull/33835

Pileup Id training for UL18
- [x] master 11_3 https://github.com/cms-sw/cmssw/pull/32887
- [x] backport 11_2 https://github.com/cms-sw/cmssw/pull/32995
- [x] backport 10_6  https://github.com/cms-sw/cmssw/pull/32951

Fat Jets constituents 
- [x] master 11_3 https://github.com/cms-sw/cmssw/pull/32927
- [x] backport 11_2 https://github.com/cms-sw/cmssw/pull/32928
- [x] backport 10_6  https://github.com/cms-sw/cmssw/pull/32930

FatJet particleNet Mass regression
- [x] master https://github.com/cms-sw/cmssw/pull/33483
- [x] backport 10_6 https://github.com/cms-sw/cmssw/pull/33588

-------- **L1 trigger**--------

Fix crash
- [x] master https://github.com/cms-sw/cmssw/pull/33920
- [x] backport 10_6 https://github.com/cms-sw/cmssw/pull/33924

ECAL L1 prefiring maps
- [x] master 11_3 https://github.com/cms-sw/cmssw/pull/32728
- [x] backport 10_6 https://github.com/cms-sw/cmssw/pull/33759

Muon Prefiring + new ECAL L1 prefixing maps updates
- [x] master https://github.com/cms-sw/cmssw/pull/33758
- [x] backport https://github.com/cms-sw/cmssw/pull/33759

-------- **Leptons**--------

leptonPT for tag and probe (muon/isoTrack)
- [x] master 11_3 https://github.com/cms-sw/cmssw/pull/32103 + [x]  https://github.com/cms-sw/cmssw/pull/33208
- [x] backport https://github.com/cms-sw/cmssw/pull/32107

electron genmmatch improvement
- [x] master 11_3 https://github.com/cms-sw/cmssw/pull/32966
- [x] backport 10_6 https://github.com/cms-sw/cmssw/pull/33347

leptons W/Z increase precision:
- [x] master 11_3https://github.com/cms-sw/cmssw/pull/33212
- [x] backport 10_6 https://github.com/cms-sw/cmssw/pull/32107

2016 EGM scale +  (4+4) variable needed for the uncertainties
- [x] master 11_3 https://github.com/cms-sw/cmssw/pull/33030
- [x] backport https://github.com/cms-sw/cmssw/pull/33376

cleanup electron never recommended for Run2 V1 variables
- [x] master 12_X https://github.com/cms-sw/cmssw/pull/33701
- [x] backport 10_6 https://github.com/cms-sw/cmssw/pull/33724

LowPt electrons
- [x] master 12_X https://github.com/cms-sw/cmssw/pull/33817 + [ ] https://github.com/cms-sw/cmssw/pull/34005
- [x] backport 10_6 https://github.com/cms-sw/cmssw/pull/33992

-------- **TAU**--------

Cleanup of IDs
- [x] master https://github.com/cms-sw/cmssw/pull/33513
- [x] backport 10_6 https://github.com/cms-sw/cmssw/pull/33658

GenVisTau
- [x] master https://github.com/cms-sw/cmssw/pull/33522 + [ ] https://github.com/cms-sw/cmssw/pull/33586
- [x] backport 10_6 https://github.com/cms-sw/cmssw/pull/33525 + [ ] https://github.com/cms-sw/cmssw/pull/33590

Boosted Tau
- [x] master https://github.com/cms-sw/cmssw/pull/33528 + 
- [x] backport 10_6 https://github.com/cms-sw/cmssw/pull/33587

-------- **BTV**--------

add SVcharge
- [x] master 11_3 https://github.com/cms-sw/cmssw/pull/32874
- [x] backport 11_2 https://github.com/cms-sw/cmssw/pull/32965
- [x] backport https://github.com/cms-sw/cmssw/pull/33075

-------- **GEN**--------

Fix customisation function
- [x] master https://github.com/cms-sw/cmssw/pull/32431
- [x] backport 10_6 https://github.com/cms-sw/cmssw/pull/33688

particleMass precision (nano + nanoGEN)
- [x] master https://github.com/cms-sw/cmssw/pull/33637
- [x] backport 10_6 https://github.com/cms-sw/cmssw/pull/33688

-------- **Update for custom nano**--------

JMEnano
- [x] master 11_3 https://github.com/cms-sw/cmssw/pull/32722
- [x] backport 11_2 https://github.com/cms-sw/cmssw/pull/32760
- [x] backport 10_6 https://github.com/cms-sw/cmssw/pull/32759

updates in PATJetUpdater
- [x] master 11_3 https://github.com/cms-sw/cmssw/pull/32297
- [x] backport 10_6 https://github.com/cms-sw/cmssw/pull/32298

**Comment by mariadalfonso** [comment]
reminder on modifiers:
https://github.com/cms-nanoAOD/cmssw/issues/533#issuecomment-672971478

to safeguard the current ongoing v8 production in 10_6_X
(run2_nanoAOD_106Xv1 & ~run2_nanoAOD_devel).toModify(xyzTable , xyxVariable = None)

**Comment by qliphy** [comment]
@mariadalfonso  Apart from  cms-sw#33759,  are there other PRs missing to start the build of 10_6_X for nanoAOD V9?

**Comment by mariadalfonso** [comment]
we compared the following releases with the run2_nanoAOD_106Xv2
CMSSW_10_6_X_2021-06-09-2300
CMSSW_12_0_X_2021-06-09-2300

We see some difference in the 1) METsignificance and 2) puppiMET.
We are investigating possible fixes for the 10_6.
as a note: we already had to customise this part already a lot for the nanov8
https://github.com/cms-nanoAOD/cmssw/issues/533
see in particular 
https://github.com/cms-sw/cmssw/pull/32329 and https://github.com/cms-sw/cmssw/pull/32076
we let you know in a few hours the PR with the fix

**Comment by mariadalfonso** [comment]
fix for METsignificance is here https://github.com/cms-sw/cmssw/pull/34096

**Comment by mariadalfonso** [comment]
all above is merged in
https://github.com/cms-sw/cmssw/releases/CMSSW_10_6_26
