### ISSUE TITLE
add lowPT electron

### ISSUE THREAD

**Issue by mariadalfonso** [cms-nanoAOD/cmssw#557]
propagate to nano from the ULreminiAOD production.
need to rerun the regression since was descoped from the reminiAOD

**Comment by mariadalfonso** [comment]
being done in cms-sw/33817 + cms-sw/34005 and back ports

**Comment by mariadalfonso** [comment]
This lowPt module is the largest CPU consuming step.
We need to re-run for the nanov9 as wasn't in the mini-V2.
We need to understand when can be disabled in the future
<img width="1284" alt="LowPtElectron" src="https://user-images.githubusercontent.com/5656714/127733905-a543dc31-b0a8-4cfe-8e28-9ce1076e025f.png">

**Comment by mariadalfonso** [comment]
need to add a "cross-cleaning" index (against standard electrons)

**Comment by bainbrid** [comment]
An issue remains concerning the cross-linking between LowPtElectrons and Electrons. See here: https://github.com/cms-sw/cmssw/pull/37137#issuecomment-1123805384

To be resolved ...

**Comment by vlimant** [comment]
looks done!
