### ISSUE TITLE
Does the weight interface work with randomized scans ?

### ISSUE THREAD

**Issue by mariadalfonso** [cms-nanoAOD/cmssw#569]
https://its.cern.ch/jira/browse/CMSCOMPPR-17185
This is the request:
https://cms-pdmv.cern.ch/mcm/requests?member_of_chain=EXO-chain_RunIIFall17GS_flowRunIIFall17DRPremixPU2017_flowRunIIFall17MiniAODv2_flowRunIIFall17NanoAODv7-01058&page=0&shown=524319

**Comment by vlimant** [comment]
looks like gen followed up on this
