### ISSUE TITLE
update btag discriminator choice, save b-tagging scale factor weights

### ISSUE THREAD

**Issue by arizzi** [cms-nanoAOD/cmssw#57]
store csvv2, cmva, deep b+bb
instead of current set

**Comment by arizzi** [comment]
also add eventWeight for SF central value

**Comment by arizzi** [comment]
also add DeepCSV in 80X running

**Comment by arizzi** [comment]
#61  implements first part of this.

**Comment by arizzi** [comment]
added deepflavour.

#120 should address the remaining part (but is currently stuck)

**Comment by mariadalfonso** [comment]
clowing this old issue, as we have been updated the tag discriminator continuously,
