### ISSUE TITLE
cleanup the UChar_t

### ISSUE THREAD

**Issue by mariadalfonso** [cms-nanoAOD/cmssw#573]
There UChar_t is not a real format https://github.com/cms-sw/cmssw/blob/master/DataFormats/NanoAOD/interface/FlatTable.h#L40-L45

However many of them appear in the documentation
https://cms-nanoaod-integration.web.cern.ch/integration/cms-swmaster/mc106Xul18_size_report.html#GenPart
and are likely a conversion between the original mini format and nano table

**Comment by vlimant** [comment]
please clarify and reopen in cms-sw if necessary
