### ISSUE TITLE
nano sw improvements

### ISSUE THREAD

**Issue by mariadalfonso** [cms-nanoAOD/cmssw#578]
- [ ] simplify the token as `iEvent.get(token)`
- [ ] update the fillDescription of https://github.com/cms-sw/cmssw/tree/master/PhysicsTools/NanoAOD/plugins so that the python code is slimmer
- [ ] clean thread usafe const_cast https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-39b0b1/15738/llvm-analysis/. (line 67 and 54 of PhysicsTools/NanoAOD/plugins/SummaryTableOutputBranches.cc)

**Comment by vlimant** [comment]
dully noted
