### ISSUE TITLE
need to add recent object boostedTau and lowPtElectron to the "linkedObjets"

### ISSUE THREAD

**Issue by mariadalfonso** [cms-nanoAOD/cmssw#579]
process.linkedObjects = cms.EDProducer("PATObjectCrossLinker",
    electrons = cms.InputTag("finalElectrons"),
    jets = cms.InputTag("finalJets"),
    muons = cms.InputTag("finalMuons"),
    photons = cms.InputTag("finalPhotons"),
    taus = cms.InputTag("finalTaus")
)

**Comment by mariadalfonso** [comment]
boostedTauMC and lowPtElectronMCTask should be added also to nanogen

**Comment by vlimant** [comment]
does not seem like this was added. where was the request coming from ?

**Comment by vlimant** [comment]
dully noted

**Comment by swertz** [comment]
note that lowptelectrons are already in the cross linker: https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/nano_cff.py#L42
