### ISSUE TITLE
tight and loose WP are swapped for the PU-jetID 2016

### ISSUE THREAD

**Issue by mariadalfonso** [cms-nanoAOD/cmssw#583]
https://github.com/cms-sw/cmssw/blob/CMSSW_10_6_26/RecoJets/JetProducers/python/PileupJetIDCutParams_cfi.py#L82-L101

@camclean

**Comment by nurfikri89** [comment]
@mariadalfonso I will make a PR for this fix.

**Comment by mariadalfonso** [comment]
> @mariadalfonso I will make a PR for this fix.

thanks, for now the master is enough; for the backport in 10_6 better wait (as for now no new production are foreseen) and fix will impact both the mini and nano production

**Comment by nurfikri89** [comment]
Merged in master cms-sw/cmssw#35443

**Comment by mariadalfonso** [comment]
we still need the fix for nano: every time we are going to read the mini-V2 of the UL we will need the swap implemented

**Comment by nurfikri89** [comment]
@mariadalfonso this means we should have a backport for the PR right?

**Comment by mariadalfonso** [comment]
> @mariadalfonso this means we should have a backport for the PR right?

I assume that the PU-id is already stored in the mini (V2 as swapped). So nano should just read from the mini and store (if you re-run that's bad from CPU point of view as you see).

When in the future we remake with master the nano out of the mini-v2 you need to re-run or make the swap.

**Comment by nurfikri89** [comment]
> > @mariadalfonso this means we should have a backport for the PR right?
> 
> I assume that the PU-id is already stored in the mini (V2 as swapped). So nano should just read from the mini and store (if you re-run that's bad from CPU point of view as you see).
> 
> When in the future we remake with master the nano out of the mini-v2 you need to re-run or make the swap.

For UL17 MiniAODv2, this is fine but for UL18, UL16APV and UL16, the PU-id was not calculated using their respective dedicated training. The trainings did not make it in time for their respective MiniAODv2 CMSSW releases [1], which was why we have to re-run PU-id calculation for NanoAODv9 of those eras.

[1] UL18: https://github.com/cms-sw/cmssw/blob/CMSSW_10_6_20/RecoJets/JetProducers/python/PileupJetID_cfi.py#L36 
UL16APV and UL16: https://github.com/cms-sw/cmssw/blob/CMSSW_10_6_25/RecoJets/JetProducers/python/PileupJetID_cfi.py#L40
