### ISSUE TITLE
CorrT1METJet should have pt and rawFactor instead of rawPt

### ISSUE THREAD

**Issue by jrueb** [cms-nanoAOD/cmssw#584]
Currently there is `CorrT1METJet_rawPt` but no `CorrT1METJet_pt` and `CorrT1METJet_rawFactor` (defined the same way as `Jet_pt` and `Jet_rawFactor`). I think there should rather be `CorrT1METJet_pt` and `CorrT1METJet_rawFactor`.

Please let me know if I'm misunderstanding something or there is an intention behind this choice other than the space reduction, this would probably help me improving my code. But with this choice right now I see two major downsides:
- When applying type-1 MET corrections because of varying jet uncertainties, one depends on the entire JEC computation (FactorizedJetCorrector and JetCorrectionUncertainty). With rawFactor and pt, FactorizedJetCorrector would become unnecessary.
- When applying different JEC than what is already applied in NanoAOD, the difference between the NanoAOD JEC of the jets in CorrT1METJet and the new JEC is unknown. However, this difference is needed in order to propagate the change to MET. With pt and rawFactor it would be trivial to compute.

What do you think?

**Comment by mariadalfonso** [comment]
@camclean @kirschen @lathomas
please comment

**Comment by vlimant** [comment]
dully noted
