### ISSUE TITLE
btagWeightTable slow and outdated

### ISSUE THREAD

**Issue by mariadalfonso** [cms-nanoAOD/cmssw#585]
The BTagSFProducer.cc is very slow (see pie charts)
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/plugins/BTagSFProducer.cc
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/btagWeightTable_cff.py

In addition thes two floats here are using an outdated SF set 94X CSV files
https://cms-nanoaod-integration.web.cern.ch/integration/cms-swmaster/mc106Xul16_doc.html#btagWeight

15% of theCPU is consumed in reading the BTag csv files
https://cms-reco-profiling.web.cern.ch/cms-reco-profiling/cgi-bin/igprof-navigator/releases/CMSSW_12_1_0_pre4/11834.21/step5/cpu_endjob/37

Short term plan:

- [ ] remove this from the Run3 sequence  (can be applied anyway a posteriori when correct calibration is available)

- [ ] update the BTagSFProducer reading the json format if deemed necessary

![memory_highStat](https://user-images.githubusercontent.com/5656714/137683209-6b9393d2-dff8-4ced-b8af-adb6078bb41b.png)
![cpu_highStat](https://user-images.githubusercontent.com/5656714/137683220-84adf7f9-d313-4463-8560-9a316ea9fb8a.png)

**Comment by mariadalfonso** [comment]
@mondalspandan

**Comment by mariadalfonso** [comment]
speed up in cms-sw/35856

**Comment by mariadalfonso** [comment]
we can close this issues, now the BTags weights are applied as json and with correctionlib

**Comment by swertz** [comment]
I think the btag weight is still being produced, I see it in the [v9 docs](https://cms-nanoaod-integration.web.cern.ch/integration/cms-swCMSSW_10_6_X/mc106Xul17v2_doc.html#btagWeight) and [here](https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/nano_cff.py#L107)... shouldn't we just remove it?
