### ISSUE TITLE
Save a custom table inside LuminosityBlock

### ISSUE THREAD

**Issue by simonepigazzini** [cms-nanoAOD/cmssw#593]
Dear Nano experts,

are there examples on how to produce private nanoAOD with additional information stored in the LuminosityBlock tree?

My use case would be to save the data from this object:
https://gitlab.cern.ch/spigazzi/PhiSym/-/blob/Run2017/EcalCalibDataFormats/interface/PhiSymRecHit.h
into private nanoAOD. At the moment, the objects in my workflow are already produced per lumi block and I'm wondering if I have to write a dedicated table producer or if I can use anything from this producer:
https://cmssdt.cern.ch/dxr/CMSSW/source/PhysicsTools/NanoAOD/plugins/NanoAODOutputModule.cc

Thank you,

simone

**Comment by mariadalfonso** [comment]
done on PR 36902
