### ISSUE TITLE
Save Z bosons in LHEPart collection

### ISSUE THREAD

**Issue by andreypz** [cms-nanoAOD/cmssw#598]
It seems to me that in the current version (v9) Z bosons are not saved in LHEPart collection.
Simple check:
```
root -l root://xrootd-cms.infn.it//store/mc/RunIISummer20UL17NanoAODv9/DYJetsToLL_M-50_TuneCP5_13TeV-amcatnloFXFX-pythia8/NANOAODSIM/106X_mc2017_realistic_v9-v2/100000/04426F83-BF53-0440-B2D1-F2DD9AB96EB8.root
Events->Draw("LHEPart_pdgId")
```
There are no `pdgid=23` on the plot (and this is Z -> LL sample)...
It applies to other files/samples that I have checked.
I think it's useful to save Z bosons. (Also W and H, but I have not checked if those are saved in LHEPart or not).

**Comment by mariadalfonso** [comment]
will be added in the v10 https://github.com/cms-sw/cmssw/pull/35753
