### ISSUE TITLE
handshake cross-POG repositories

### ISSUE THREAD

**Issue by mariadalfonso** [cms-nanoAOD/cmssw#600]
NANO integration
- [x] cms-sw: PRs signatures ( this is our package https://github.com/cms-sw/cmssw/tree/master/PhysicsTools/NanoAOD)
- [x] git lab for DQM based testing https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/
- [x] virtial machine https://its.cern.ch/jira/browse/CMSVOC-294
- [x] website https://cms-nanoaod-integration.web.cern.ch/integration/
- [x] issues to track down missing features https://github.com/cms-nanoAOD/cmssw/issues
- [x] nano docs https://gitlab.cern.ch/cms-nanoAOD/nanoaod-doc

JSON file for corrections
- [x]  git lab for testing https://gitlab.cern.ch/cms-nanoAOD/jsonpog-integration
once merged the files get copied into /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG
- [x] correction Lib.  https://github.com/cms-nanoAOD/correctionlib (before pushing into cms-sw)
- [x] website for self documentation https://cms-nanoaod-integration.web.cern.ch/commonJSONSFs/

ANALYSIS TOOLS
- [x] cms-nanoAOD (tools) [ deprecated ? ] https://github.com/cms-nanoAOD/nanoAOD-tools

indico 
- [x] https://indico.cern.ch/category/5517/

mattermost
- [x] https://mattermost.web.cern.ch/cms-exp/channels/xpog-coordination

**Comment by mariadalfonso** [comment]
<img width="774" alt="Screen Shot 2022-05-22 at 19 57 44" src="https://user-images.githubusercontent.com/5656714/169709037-0d375704-50ea-4e67-9870-77eb92bec5da.png">

**Comment by vlimant** [comment]
in https://docs.google.com/document/d/1zSRNXsBw_cwQjLdxehz-hv8qMRU14HfoA86_4JdybYo/edit?usp=sharing
