### ISSUE TITLE
GEN refactoring

### ISSUE THREAD

**Issue by mariadalfonso** [cms-nanoAOD/cmssw#601]

**Comment by mariadalfonso** [comment]
Refactoring started here, need to be tested extremely well
- [ ] master https://github.com/cms-sw/cmssw/pull/32167

**Comment by vlimant** [comment]
we will keep track of things for V11 in the googledoc : https://docs.google.com/document/d/1UaAEmLBbA8upMzIZ4Rnv5__ychOsEVBDecca0zHAQ4I/edit?usp=sharing
