### ISSUE TITLE
unclustered met uncertainties

### ISSUE THREAD

**Issue by arizzi** [cms-nanoAOD/cmssw#7]
need to add unclustered met uncertainties

**Comment by arizzi** [comment]
@zdemirag @seemasharmafnal

**Comment by arizzi** [comment]
@zdemirag can you post an example to access it or even directly send a PR on this repository against nano_94X branch?

**Comment by zdemirag** [comment]
generic usage is: met.shiftedXyz(uncertainty, level) 

* xyz can be: Pt, P2, P3, P4, Px, Py, Pz, Phi, SumEt
* uncertainty can be: http://cmsdoxygen.web.cern.ch/cmsdoxygen/CMSSW_8_0_11/doc/html/db/deb/classpat_1_1MET.html#a5c8ea7c9575730bedb6f1639140a7422
* level can be:
http://cmsdoxygen.web.cern.ch/cmsdoxygen/CMSSW_8_0_11/doc/html/db/deb/classpat_1_1MET.html#a266ab5a1249b3b428162c633a02c95a9

a full example would be:
met.shiftedPt(pat::MET::UnclusteredEnUp, pat::MET::Type1)

**Comment by gpetruc** [comment]
closing, as it's addressed by #31 and the discussion is happening there
