### ISSUE TITLE
All tauID bitmapped branches have only two bins

### ISSUE THREAD

**Issue by ktht** [cms-nanoAOD/cmssw#71]
I found that the following variables are evaluated to exactly two values only -- 0 and 1 -- instead of what is expected (shown in parentheses):

- Tau_idAntiMu (0, 1, 3)
- Tau_idAntiEle (0, 1, 3, 7, 15, 31)
- Tau_idMVAnewDM (0, 1, 3, 7, 15, 31, 63)
- Tau_idMVAoldDM (0, 1, 3, 7, 15, 31, 63)
- Tau_idMVAoldDMdR03 (0, 1, 3, 7, 15, 31, 63)

In other words, it looks as if the taus can only pass VLoose working points
 (or Loose WP in case of Tau_idAntiMu) and nothing beyond that. By looking at individual branches from which the tau ID bitmaps are generated (see [here](https://github.com/cms-nanoAOD/cmssw/blob/76ecbb10921fd1a478e8da86603df593012e7b59/PhysicsTools/NanoAOD/python/taus_cff.py#L16-L24) and [here](https://github.com/cms-nanoAOD/cmssw/blob/76ecbb10921fd1a478e8da86603df593012e7b59/PhysicsTools/NanoAOD/python/taus_cff.py#L62-L66)), and trying to reproduce the bitmap with custom tools, I get the expected number of bins. On the left in the attached picture is the output with the current implementation and on the right is the expected output. The attached image is generated by saving all tauID variables on separate branches and then post-processing the ROOT file with a custom nanoAOD-tools module (used the same file as currently specified in `nano_cfg.py`).
![tauids](https://user-images.githubusercontent.com/6233872/32946777-82ce9e0a-cba1-11e7-898b-02d16d31f56c.png)

I believe that the problem comes from [this line](https://github.com/cms-nanoAOD/cmssw/blob/76ecbb10921fd1a478e8da86603df593012e7b59/PhysicsTools/NanoAOD/python/taus_cff.py#L17) -- the tauID function returns a boolean, which upon multiplying with an integer still leaves it boolean (no implicit conversion to int!); addition apparently works as OR operator. I don't know how to fix it since I'm not familiar with this syntax.

**Comment by peruzzim** [comment]
I think this was due to the bug fixed in #70.
Can you verify if the problem is still present after the fix?
From the last DQM validation of #68, it seems solved to me.

**Comment by ktht** [comment]
Yes, the issue is fixed indeed. Hadn't updated my local checkout for a week or so, my bad. Thanks again!
