### ISSUE TITLE
Rivet analyses

### ISSUE THREAD

**Issue by arizzi** [cms-nanoAOD/cmssw#8]
Investigate rivet stuff

**Comment by perrozzi** [comment]
The idea is to add GEN collections obtained via Rivet cfr https://github.com/cms-sw/cmssw/pull/18402

**Comment by arizzi** [comment]
is there a standard set of rivet collections?
or each analysis need something different

**Comment by perrozzi** [comment]
standard. @intrepid42 can you please some tests/integration?

**Comment by arizzi** [comment]
do you have a sequence to run rather than the unscheduled?
should we consider the config in release good for all?
@kreczko you said there were multiple configurations that is in contrast with what @perrozzi states above.
Can we please clarify this point.

**Comment by intrepid42** [comment]
Hi, there is some flexibility but I think we can use the [standard settings](https://github.com/cms-sw/cmssw/blob/master/GeneratorInterface/RivetInterface/python/particleLevel_cfi.py), I would just lower the jet pt to 20 GeV, then most analyses should be covered. I can make a pull request for that.

**Comment by kreczko** [comment]
@arizzi @intrepid42 
I was simply concerned about the final jet collections.
If the lepton pT cuts vary per analysis, then the jet collections will as well.

That said, I am all in favour of standardization, so I would follow whatever @intrepid42 suggests.

**Comment by intrepid42** [comment]
Indeed, leptons with pt>15 are considered lepton candidates right now, and are not clustered into the jets. That is fine for low pt analyses but not really for high-pt...

Or we set `excludePromptLeptonsFromJetClustering = cms.bool(False),` and do/advise a dR cleaning?

**Comment by kreczko** [comment]
If it is as simple as dR cleaning (I thought the clustering did more complex things), then we can use NanoAOD's masking mechanism for the default leptons
and everyone not using the default would have the possibility to clean against their leptons.

**Comment by intrepid42** [comment]
The current default is `excludePromptLeptonsFromJetClustering = cms.bool(True),`, so the leptons are excluded from jet clustering.

Reading the option name again, I see that this applies only to *prompt leptons* (=not from hadron decay), so we will still cluster all those from heavy hadron decays into the jets.

Should be fine to leave it like that as default option then!

**Comment by arizzi** [comment]
if you set 
`excludePromptLeptonsFromJetClustering = cms.bool(False)`

how would that differ exactly from normal GenJets ?

**Comment by intrepid42** [comment]
~~The normal GenJets still exclude muons from W~~

I checked again and see that `slimmedGenJets=ak4GenJetsNoNu`, so that unholy exclusion of muons from W was discarded :)

So, indeed, with `excludePromptLeptonsFromJetClustering = cms.bool(False)` we would have `RivetJets=GenJets` (modulo the cuts). If it is decided to just go for GenJets, we would still need the hadron-based flavor information associated to them (there are events with more GenJets than Jets, so Jet_hadronFlavour does not help), and that mask for the lepton overlap.

**Comment by arizzi** [comment]
I think we added in miniAOD the hadronFlavour so in principle this should be available without reclustering

**Comment by arizzi** [comment]
#21 merged
