### ISSUE TITLE
Review Jet TriggerObjects and add b-tag trigger objects

### ISSUE THREAD

**Issue by arizzi** [cms-nanoAOD/cmssw#81]
- add LooseId jet collection
- possibly add "uncorrected" pt as additional possible layer for trigger objects
- add HLT btag information

**Comment by rappoccio** [comment]
I think we also need to add the AK8 jets here (I can handle that), but does anyone have expertise with the btagging information at the HLT level?

**Comment by rappoccio** [comment]
The AK8 jets are implemented. 

I don't have the expertise for the HLT btag information. 

I am unsure if we need the uncorrected pt or the looseid jet collections??? @arizzi any thoughts there?

**Comment by arizzi** [comment]
don't we have the rawFactor to get back to raw pt?

**Comment by rappoccio** [comment]
We have rawFactor in the AK4 collection and now in the AK8 collection at reco level. Is that what you mean?

**Comment by vlimant** [comment]
too ancient to be relevant
