### ISSUE TITLE
Effective areas for electron isolation: Spring15 -> Summer16?

### ISSUE THREAD

**Issue by ktht** [cms-nanoAOD/cmssw#86]
https://github.com/cms-nanoAOD/cmssw/blob/564c740f3b595d579a012659cba71b3bf706e9b9/PhysicsTools/NanoAOD/python/electrons_cff.py#L70

Shouldn't the input txt file be updated to: `RecoEgamma/ElectronIdentification/data/Summer16/effAreaElectrons_cone03_pfNeuHadronsAndPhotons_80X.txt`?

**Comment by arizzi** [comment]
@peruzzim @emanueledimarco  can you comment/fix?

**Comment by peruzzim** [comment]
For miniIso we are still using Spring15 (very small difference), so for the ease of synchronization I would not change it now.
I propose we update it together with the switch to the new 94X ID, that should be ready soon.

**Comment by arizzi** [comment]
@peruzzim now that EGM ID are being finalized, what should we do here? Are we planning to keep Spring15 versions for 80X running and adapt only for 2017?

**Comment by peruzzim** [comment]
I'm taking care of this now, together with updating the lepton MVA to its latest 94X training

**Comment by gpetruc** [comment]
in #133
