### ISSUE TITLE
Monitor CMSSW-master branch

### ISSUE THREAD

**Issue by gpetruc** [cms-nanoAOD/cmssw#90]
We periodically need to make sure the 10_1_X (master) branch stays aligned with the 9_4_X branch.
I'm creating this github issue so that the bot can do the monitoring and use it to post integration failures.

**Comment by arizzi** [comment]
update up to #100

**Comment by arizzi** [comment]
updated to #101

**Comment by arizzi** [comment]
failures are due to base IB not having new accessor

**Comment by arizzi** [comment]
should be rerun after https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/pipelines/293295 is completed

**Comment by arizzi** [comment]
#126 CMSSW 10_1_0_pre3
#127 sync up to 123 (excluding 108 and 120)

**Comment by arizzi** [comment]
update gitlab to 10_1_1 (just out). DQM update is pending as the branch has been used in a cmssw PR

**Comment by arizzi** [comment]
it seems this https://github.com/cms-sw/cmsdist/pull/3887 is only in 10_2_X, not in 10_1_X

is 10_1_0 a nano target?

**Comment by arizzi** [comment]
@slava77 this last was a test of CMSSW_10_2_X_2018-04-22-2300 (that I think includes  https://github.com/cms-sw/cmssw/pull/22914)

**Comment by arizzi** [comment]
the link needs a redirect if you are outside cern.
In fact the DQM does not monitor the indices but I verified those by
hand downloading the artifacts root files (and the indices are ok).
Can you confirm that the IB CMSSW_10_2_X_2018-04-22-2300 contained
andreas PR ?

**Comment by slava77** [comment]
On 4/23/18 5:39 AM, arizzi wrote:
> Can you confirm that the IB CMSSW_10_2_X_2018-04-22-2300 contained
> andreas PR ?


yes
https://cmssdt.cern.ch/SDT/html/showIB.html
that PR is included starting CMSSW_10_2_X_2018-04-21-1800

**Comment by mariadalfonso** [comment]
closing this issue, since now we moved integration of PR direction in cms-sw with master first and then backport
