### ISSUE TITLE
Variable length arrays in FlatTable

### ISSUE THREAD

**Issue by matt-komm** [cms-nanoAOD/cmssw#92]
Dear developers,

I like to adapt the nanoaod format for my analysis to store additional information about each jet constituent.
I am wondering if you consider to extend the FlatTable class to support arrays of variable length. Currently only single values are possible which have to be one of the following types (FloatColumn, IntColumn, UInt8Column, BoolColumn) if I am not mistaken.

**Comment by arizzi** [comment]
how would you make persistent in bare root such format?
1D array are supported and are persisted as Object_member[n] 
but if you want to store jet constituents you need to go 2D.. and I'm not sure root supports 2D variable length.

**Comment by matt-komm** [comment]
Can you not store the length of the 2D array 2nd dimension in a 1D array and then flattened 2D to 1D? So in my case the tree would have an additional branch e.g. nChargedConstituents (1D array of length nJet) and an additional branch e.g. cpf_ptrel (1D array of length nJet*nChargedConstituents) which contains then the 2D array data.

**Comment by arizzi** [comment]
nChargedConstituents is not the same for all jets, I doubt the size of cpf_ptrel can be nJet*nChargedConst, it could be Sum(nChargedConts).
Anyhow the access to this would be painful and very "custom".
If you want to store this info that way I suggest you just create a FlatTable of length Sum(nChargedConsts) and you fill it the way you said.

**Comment by matt-komm** [comment]
> nChargedConstituents is not the same for all jets

that's why it is a 1D array of size nJet. Anyway I will now go with my hacky solution yet in the future it could be nice to have some convenience functions to support this ...

**Comment by arizzi** [comment]
do you agree that if nChargedConstituents is not constant, and it is not, then the size of cpf_ptrel cannot be 
nJet*nChargedConstituents ? (in fact such operation is not even among "scalars" because nChargedConstituents is a vector)

**Comment by matt-komm** [comment]
ah sorry, I wrote it to quickly: the flattened 1D array has the size sum(nChargedConstituents[i]) for i=0..nJet

**Comment by nsmith-** [comment]
One way to accomplish this while restricted to 1D arrays is to use references into a separate array.
For example, consider an event with 3 jets, having 1, 0, 4 constituents, respectively.  One could fill arrays so that:
```c++
int nJets = 3;
int Jet_ConstituentIdxStart[nJets] = {0, 1, 1};
int Jet_ConstituentIdxStop[nJets] = {1, 1, 5};
int nJetConstituents = 5;
double JetConstituent_pt[nJetConstituents] = {12., 4., 7., 4., 9.}
```
Then a user could access these via a double loop:
```c++
for (int iJet=0; iJet < nJets; iJet++) {
  for (int iCand=Jet_ConstituentIdxStart[iJet]; iCand < Jet_ConstituentIdxStop[iJet]; iCand++) {
    auto candpt = JetConstituent_pt[iCand];
    // do stuff
  }
}
```
This is essentially how [JaggedArray](https://github.com/scikit-hep/awkward-array) works.  There's some more compacting that can be done if having starts and stops seems like too much redundancy: an offsets array with length `nJets+1` can encode the same info.
A generalization of the cross-linking code could be flexible enough to do this (and keep more than the first N matches, whatever N was chosen to be!)

**Comment by arizzi** [comment]
... or you can just navigate backwards, i.e. store the 
PFCands_pt
PFCands_eta
PFCands_phi
PFCands_jetIdx
if candidates are sorted by jetIdx the compression should be quite effective in reducing the size of this

**Comment by nsmith-** [comment]
`Jet_PFCandOffsets` would have less entries than `PFCands_jetIdx` and be equally compressible.  Plus, computing the inverse in the analysis code would be slightly more complicated: at best `while(PFCands_jetIdx[iCand++]==iJet)`, and at worst (i.e. someone will write it this way) a full scan each time.

**Comment by vlimant** [comment]
ping / reopen if needed
