### ISSUE TITLE
nTruePU: incorrect numeric type?

### ISSUE THREAD

**Issue by mbluj** [cms-nanoAOD/cmssw#95]
The `nTrueInt` variable stored in the `puTable` [1] is, as its name suggests, the true mean number of the Poisson distribution of pileup interactions for the event which stored as an integer number. However, the true  (mean) number of PU interactions is not necessary an integer number and it is why the `getTrueNumInteractions()` method [2] returns a floating point number (float). Do we want store it as an integer? If so [3], it will be good to round properly a float to an integer during casting, i.e. replace `getPU_NumInteractions()` by `getPU_NumInteractions()+0.5`

[1] [PhysicsTools/NanoAOD/python/globals_cff.py : puTable](https://github.com/cms-nanoAOD/cmssw/blob/master/PhysicsTools/NanoAOD/python/globals_cff.py#L12)

[2] [PileupSummaryInfo::getTrueNumInteractions()](https://github.com/cms-nanoAOD/cmssw/blob/master/SimDataFormats/PileupSummaryInfo/interface/PileupSummaryInfo.h#L80)

[3] For <PU>~20 typical for 2016 integer means ~3.5% of precision, so probably it is sufficient.

**Comment by gpetruc** [comment]
i agree, it's likely a mistake, it should bea float.

Giovanni

Il 18 Gen 2018 15:04, "mbluj" <notifications@github.com> ha scritto:

**Comment by emanueledimarco** [comment]
Yes, my bad. It should be a float number.

**Comment by mbluj** [comment]
OK, thanks for confirmation. Are you going to fix it?

**Comment by gpetruc** [comment]
I think the fix can go in as part of #96

**Comment by emanueledimarco** [comment]
Yes

**Comment by emanueledimarco** [comment]
OK so @rappoccio will do it in #96 ? Thanks

**Comment by rappoccio** [comment]
I will fix it in #96.
